### ISSUE TITLE
property 'identifier' not found on object of type 'SKProductDiscount *'

### ISSUE THREAD

**Issue by JonasJW** [RevenueCat/purchases-flutter#10]
I get this error when running on an iOS Simulator

`````
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'in_app_purchase')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'in_app_purchase')
    warning: Capabilities for Runner may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'Runner')
    /Users/jonas/Projects/ProjectFit/mobile/training_hub_flutter/ios/Pods/Purchases/Purchases/RCPromotionalOffer.m:21:48: error: property 'identifier' not found on object of type 'SKProductDiscount *'
            self.offerIdentifier = productDiscount.identifier;
                                                   ^
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description
Could not build the application for the simulator.
Error launching application on iPhone 8.

**Comment by vegaro** [comment]
What version of the simulator are you running?

**Comment by JonasJW** [comment]
iPhone 8, iOS Version 12.1 and I'm using purchases_flutter: ^0.3.2

**Comment by JonasJW** [comment]
Anything I can try here? I would really like to keep using revenuecat with flutter...

**Comment by vegaro** [comment]
That's a really weird issue, but I have seen similar problems where the identifier is also nil for `SKProduct`, when it shouldn't be. I will add some protective nil checks to make sure this doesn't crash hard. 

Thanks for reporting!

**Comment by vegaro** [comment]
Hey @JonasJW  sorry I misread the output first time. Is it possible you're running an older version of XCode?

**Comment by JonasJW** [comment]
Thank you! Updating XCode and afterwards reinstalling cocoa pods with `sudo gem install cocoapods` seems  to have fixed it.

**Comment by wmonecke** [comment]
I have this error as well.
@JonasJW  Do you know by any chance what XCode version you had when you found this issue? I am on XCode 10.1 and a bit afraid to upgrade.

**Comment by JonasJW** [comment]
@wmonecke Sorry, I don't know. I'm currently on 11.2.1 and it seems to work fine but I don't know my when I previously updated and what version I had before

**Comment by vegaro** [comment]
@wmonecke you should be using XCode 10.2+
