### ISSUE TITLE
Because no versions of purchases_flutter match 1.3.0 and no versions of purchases_flutter match >1.3.0 <2.0.0, purchases_flutter ^1.3.0 is forbidden. So, because cosmeticscanner depends on purchases_flutter ^1.3.0, version solving failed. pub get failed (1; So, because cosmeticscanner depends on purchases_flutter ^1.3.0, version solving failed.)

### ISSUE THREAD

**Issue by abaturyna** [RevenueCat/purchases-flutter#101]
Because no versions of purchases_flutter match 1.3.0 and no versions of purchases_flutter match >1.3.0 <2.0.0, purchases_flutter ^1.3.0 is forbidden.
So, because cosmeticscanner depends on purchases_flutter ^1.3.0, version solving failed.
pub get failed (1; So, because cosmeticscanner depends on purchases_flutter ^1.3.0, version solving failed.)

**Comment by aboedo** [comment]
it looks like you may need to update the sources where flutter is looking up dependencies.
Does
`flutter channel master`
`flutter upgrade`

fix it?

**Comment by aboedo** [comment]
@abaturyna hi, thanks for reporting. What version of flutter are you using on your project?

**Comment by abaturyna** [comment]
@aboedo 

> it looks like you may need to update the sources where flutter is looking up dependencies.
> Does
> `flutter channel master`
> `flutter upgrade`
> 
> fix it?

Hi @aboedo , unfortunately it did not help. :( tried latest versions from channels 'master', 'dev' and 'stable' :/

**Comment by abaturyna** [comment]
My flutter doctor is : 

nastya@MacBook-Pro-Nastya ios % flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.368, on Mac OS X 10.15.6 19G73 x86_64, locale ru-BY)
    • Flutter version 1.22.0-10.0.pre.368 at /Users/nastya/Dropbox/BUSINESS/Soft/flutter 1.2.13
    • Framework revision 4eedca089f (11 минут назад), 2020-09-25 11:17:03 -0700
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nastya/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.97

[✓] Connected device (3 available)
    • nastenka’s iPhone (mobile) • 00008030-000A113802E2802E • ios            • iOS 14.0.1
    • Web Server (web)           • web-server                • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 85.0.4183.121

• No issues found!

**Comment by vegaro** [comment]
Did you try?

```
flutter clean
flutter pub get
```

**Comment by abaturyna** [comment]
of course i tried. This issue can be closed as new version 1.3.1 is released .

**Comment by aboedo** [comment]
I'm glad this got solved. @abaturyna for future reference, could you share your `pubspec.yaml` entry for `purchases-flutter`? I'm still not sure why this was targeting versions `> 1.3.0`

**Comment by rkotzy** [comment]
Closing this out due to inactivity.
