### ISSUE TITLE
purchaserInfoUpdateListener not triggered when subscription is cancelled

### ISSUE THREAD

**Issue by narcodico** [RevenueCat/purchases-flutter#107]
**Describe the bug**
`purchaserInfoUpdateListener` is not called when a subscription is cancelled. Seems normal to not fire it as long as the subscription has remaining time. But once it reaches the end I would expect the listener to be called, otherwise a user could just stay within app and keep the pro status.
I hope this is a bug and not intended. Can someone shed some light on this manner ? Thanks!

1. Environment
    1. Platform: flutter
    2. SDK version: ^1.3.1
    3. OS version: win10
    4. vscode version: 1.49.2
    5. How widespread is the issue: 100%

**Comment by rkotzy** [comment]
The listener will fire whenever the SDK receives an updated purchaser info object from calls to `getPurchaserInfo()`, `purchasePackage()`, `purchaserProduct()`, or `restoreTransactions()`. 

Purchaser Info updates are not *pushed* to your app from the RevenueCat backend, updates can only happen from an outbound network request to RevenueCat.

**Comment by narcodico** [comment]
Thanks for details @rkotzy but it seems a bit counterintuitive.
What the purpose of having that listener if I still have to call some method to get the latest status ?
You could just set up a periodic stream that calls `getPurchaserInfo()` every x min.

**Comment by rkotzy** [comment]
Some developers prefer to isolate subscription status changes to a single place in their application and this listener can assist with that. Since the purchaser info is cached on device, you can call `getPurchaserInfo()` as often as needed (every time user is accessing "premium" content) and the caches will update in the background and hit the listener with any changes.

**Comment by narcodico** [comment]
On a second thought, the listener is helpful when subscribing since it will trigger instantly.
I'm not a big fan of having to call a method each time the user accesses something which might be premium content.
I'd rather have a push mechanism which notifies parts of the app about the user pro status.
Your answer was helpful though, so thanks for your time 👋
