### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by NashIlli** [RevenueCat/purchases-flutter#1092]
I am developing a Flutter application that targets Windows users and would like to integrate in-app purchases (IAP) with Microsoft Store using RevenueCat. Currently, the RevenueCat Flutter package does not support Windows, which limits the potential user base and revenue streams for Windows apps.

Supporting Windows would greatly benefit developers who are targeting multiple platforms with Flutter. RevenueCat's unified solution for IAP and subscription management is highly valuable, and extending this support to Windows would enhance its utility and appeal to a broader developer community.

Thank you for considering this feature request. I look forward to the possibility of using RevenueCat for Windows apps.

**Comment by Jethro87** [comment]
Hi @NashIlli! Thanks for posting this. I have notified our product team of your request and will close this issue for now.

**Comment by mregnauld** [comment]
I would definitely be interested in that too!

**Comment by freak4pc** [comment]
Wondering if there are any updates/plans around this?

**Comment by andreykuzmenko** [comment]
+1

**Comment by tjkh** [comment]
I am also waiting for this feature.

**Comment by AminDhouib** [comment]
i need this feature included to process MS Store payments. Are there any updates? cc @Jethro87 

Regardless, thank you for your awesome efforts made to make RevenueCat an awesome product!

**Comment by pandabossli** [comment]
I am also waiting for this feature.

**Comment by finnvyrn** [comment]
+1

**Comment by kenzo-ai** [comment]
+1
