### ISSUE TITLE
Deprecation error message for syncObserverModeAmazonPurchase

### ISSUE THREAD

**Issue by JaseElder** [RevenueCat/purchases-flutter#1114]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

# ‼️ Required data ‼️ #
**Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

There are a lot of things that can contribute to things not working. Having a very basic understanding of your environment will help us understand your issue faster!

## Environment ##
- [x] Output of `flutter doctor`
```
[✓] Flutter (Channel stable, 3.22.2, on macOS 13.6.7 22G720 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3.5)
[✓] Connected device (3 available)
[✓] Network resources
```

- [x] Version of `purchases-flutter`
`purchases_flutter: ^6.30.0`
- [x] Testing device version e.g.: iOS 15.5, Android API 30, etc.
Android API 28

- [x] How often the issue occurs- every one of your customers is impacted? Only in dev?
Shows on build

- [ ] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
- [ ] Steps to reproduce, with a description of expected vs. actual behavior
**Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

## Describe the bug ##
Getting this message on build:
```
...pub-cache/hosted/pub.dev/purchases_flutter-6.30.0/android/src/main/java/com/revenuecat/purchases_flutter/PurchasesFlutterPlugin.java:551: warning: [deprecation] syncObserverModeAmazonPurchase(String,String,String,String,Double) in Purchases has been deprecated
        Purchases.getSharedInstance().syncObserverModeAmazonPurchase(productID, receiptID,
                                     ^

```

**Comment by tonidero** [comment]
Hi @JaseElder, thanks for reporting this! #1115 should fix the warning, but we will be actually deprecating that API soon. It will still be usable, but we would suggest a new one to use instead.

**Comment by JaseElder** [comment]
No worries. 
I don't know if it matters, but as far as I know I wasn't using it. I'm only testing Play Store functionality at the moment.
