### ISSUE TITLE
No virtual method getIntroductoryPriceCycles

### ISSUE THREAD

**Issue by umutcoskun** [RevenueCat/purchases-flutter#112]
E/AndroidRuntime( 6699): java.lang.NoSuchMethodError: No virtual method getIntroductoryPriceCycles()Ljava/lang/String; in class Lcom/android/billingclient/api/SkuDetails; or its super classes (declaration of 'com.android.billingclient.api.SkuDetails' appears in /data/app/com.kuzgun.giftplay-ar6sv6IU8E_1KRf4PmY1WQ==/base.apk)
E/AndroidRuntime( 6699):        at io.flutter.plugins.inapppurchase.Translator.fromSkuDetail(Translator.java:27)
E/AndroidRuntime( 6699):        at io.flutter.plugins.inapppurchase.Translator.fromSkuDetailsList(Translator.java:49)
E/AndroidRuntime( 6699):        at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl$1.onSkuDetailsResponse(MethodCallHandlerImpl.java:185)
E/AndroidRuntime( 6699):        at com.android.billingclient.api.zzj.run(com.android.billingclient:billing@@3.0.0:8)
E/AndroidRuntime( 6699):        at android.os.Handler.handleCallback(Handler.java:888)
E/AndroidRuntime( 6699):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 6699):        at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime( 6699):        at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime( 6699):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6699):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime( 6699):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Process ( 6699): Sending signal. PID: 6699 SIG: 9

**Describe the bug**
This is a JAVA error.

1. Environment
    1. Platform: Android
    2. SDK version: 1.3.1
    3. OS version:
    4. XCode/Android Studio version: VSCODE

**Additional context**
I get the error when I try to initialize RevenueCat. (Purchases.setup)

**Comment by rkotzy** [comment]
That error looks to be from another plugin, `io.flutter.plugins.inapppurchase`?

**Comment by vegaro** [comment]
Someone opened a very similar issue not long ago, just in case it helps https://github.com/RevenueCat/purchases-flutter/issues/89
