### ISSUE TITLE
No implementation found for method setupPurchases on channel purchases_flutter

### ISSUE THREAD

**Issue by umutcoskun** [RevenueCat/purchases-flutter#116]
I get the error when I try to get offerings:

E/flutter (10393): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method setupPurchases on channel purchases_flutter)

1. Environment
    1. Platform: Android
    2. SDK version:
    3. OS version:
    4. XCode/Android Studio version:  VSCODE
    5. How widespread is the issue. Percentage of devices affected.

Added plugin to pubspec.yaml, added BILLING permission to the manifest.

**Comment by rkotzy** [comment]
👋  hi! Thanks for opening an issue, however this doesn't appear to be a reproducible issue with the Flutter SDK.

If you're able to provide details with specific steps to reproduce we can reopen the issue.

If you need help getting set up, you can connect with other developers in [our community](https://spectrum.chat/) or contacting our support team through the [Help Center](https://support.revenuecat.com/hc/en-us).

**Comment by CiriousJoker** [comment]
I also have the same issue..

**Comment by CiriousJoker** [comment]
This can be reproduced with the example you provided on pub.dev.

[RC-Demo-Error.zip](https://github.com/RevenueCat/purchases-flutter/files/5447660/RC-Demo-Error.zip)

If this doesn't reproduce it, it could be a Flutter issue.

Here's my version:
```
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (12 days ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
```

Here's this demo project hosted on Flutlab:
https://api.flutlab.io/res/projects/46944/kbw3pbykq0ypksq6mgfh/index.html#/

**Comment by CiriousJoker** [comment]
Oh no, I just realized this package has no Flutter Web support 😫. That's a dealbreaker :(

**Comment by Albert-Jan** [comment]
Are there any plans regarding adding web support with a Stripe implementation? This might be extra interesting now Flutter 2.0 promotes Web to the stale channel :P
