### ISSUE TITLE
PurchaserInfo missing properties

### ISSUE THREAD

**Issue by magnuswikhog** [RevenueCat/purchases-flutter#12]
The [documentation](https://docs.revenuecat.com/docs/purchaserinfo) mentions that the `PurchaserInfo` has two properties called `Request Date` and `Original Application Version`, but they don't seem to be present in the Flutter version of `PurchaserInfo`?

The documentation even specifically says that you should user `Request  Date` rather than device time to make time comparisons.

**Comment by vegaro** [comment]
Fixed on https://github.com/RevenueCat/purchases-flutter/releases/tag/1.0.0
