### ISSUE TITLE
[MacOS] dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by EliasDeuss** [RevenueCat/purchases-flutter#125]
Getting this error when trying to update the podfile with ```pod update```

Error:
```
[!] CocoaPods could not find compatible versions for pod "purchases_flutter":
  In Podfile:
    purchases_flutter (from `Flutter/ephemeral/.symlinks/plugins/purchases_flutter/macos`)

Specs satisfying the `purchases_flutter (from `Flutter/ephemeral/.symlinks/plugins/purchases_flutter/macos`)` dependency were found, but they required a higher minimum deployment target.
```

Flutter doctor -v:
```
[✓] Flutter (Channel dev, 1.24.0-3.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-US)
    • Flutter version 1.24.0-3.0.pre at /Users/eliasdeuss/flutter
    • Framework revision 2783f8e2e1 (7 days ago), 2020-10-22 09:36:06 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.10.0
```

**Comment by aboedo** [comment]
what do you have set as the deployment target for macOS? 
The plugin needs it to be at least 10.12, as defined here: https://github.com/RevenueCat/purchases-flutter/blob/develop/macos/purchases_flutter.podspec#L20.

**Comment by EliasDeuss** [comment]
> what do you have set as the deployment target for macOS? 
> 
> The plugin needs it to be at least 10.12, as defined here: https://github.com/RevenueCat/purchases-flutter/blob/develop/macos/purchases_flutter.podspec#L20. 

@aboedo I have it set to 10.13.

**Comment by aboedo** [comment]
Make sure that you have the value set in the podfile itself https://docs.revenuecat.com/docs/flutter#ios-deployment-target

**Comment by EliasDeuss** [comment]
<img width="345" alt="Screenshot_9" src="https://user-images.githubusercontent.com/13773566/97757977-219bd780-1abb-11eb-97e8-b60299ff286b.png">

@aboedo I have it also set to 10.13

**Comment by EliasDeuss** [comment]
Nevermind it was set in the package to .14 when I was going through it.

**Comment by manel00** [comment]
How to solve this problem? Thank you

It never ends with Capacitor Local Notifications

**Comment by aboedo** [comment]
@manel00 as mentioned before, make sure that the deployment target is correctly set, both in the `Podfile` and in the project.

**Comment by manel00** [comment]
The problem I have, It is changing to default (11.0) where is the source where it gets it? Ionic 5 + Capacitor 2

**Comment by aboedo** [comment]
@manel00 you should follow up with our support team at https://support.revenuecat.com so they can help you get set up. We reserve Github Issues for bug reports. 
I believe that you can configure the value through config.xml, as demonstrated here https://stackoverflow.com/a/36806063/5074358. But if you struggle with that, I recommend again that you follow up with our support team who can better assist you.
