### ISSUE TITLE
Invalid Play Store credentials errors. Please don't ignore.

### ISSUE THREAD

**Issue by chirag-chopra** [RevenueCat/purchases-flutter#131]
Anyone please help me in implementing this plugin.
I am getting this error
[Invalid Play Store credentials errors
](https://docs.revenuecat.com/discuss/5ea749abbbfeff0018f166f3)
I tried this solution but still getting same error. There is already a project in Google Cloud Platform(that is created automatically by firebase when I implemented google login using firebase) but when I go to Google Play Console to link that project then I am unable to find that project in existing projects in Api Access section of Google Play Console. I don't know what's wrong I am doing.

Do I need to do anything special to make that existing Google Cloud Platform to see in Api Access of my google play console?
If yes the please update documentation.
Please HELP...!

**I use VSCODE for development**
C:\Users\DELL>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.51.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by aboedo** [comment]
@chirag-chopra I did find a ticket in our support system from you, and we sent a reply on Nov 2nd. Did you not receive the reply? You might want to check your spam folder just in case. We're sending you another response through support just in case.

**Comment by rkotzy** [comment]
Going to close this out since it's not a specific issue with the Flutter SDK. You can contact our support team through the [Help Center](https://support.revenuecat.com/hc/en-us) if you need any assistance getting set up and we'll be happy to help!

**Comment by esconts** [comment]
@chirag-chopra Did you solve this problem?
