### ISSUE TITLE
Unable to Archive (IOS)

### ISSUE THREAD

**Issue by signshah** [RevenueCat/purchases-flutter#133]
**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue.

1. Mac OS
    1. Output of `flutter doctor`
      [✓] Flutter (Channel stable, 1.22.3, on macOS 11.0.1 20B29, locale en-US)
 
      [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
      [✓] Xcode - develop for iOS and macOS (Xcode 12.2)
      [!] Android Studio (version 4.1)
           ✗ Flutter plugin not installed; this adds Flutter specific functionality.
           ✗ Dart plugin not installed; this adds Dart specific functionality.
       [!] VS Code (version 1.51.1)
           ✗ Flutter extension not installed; install from
          https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
       [!] Connected device
           !No devices available
    
version **purchases_flutter: ^1.4.3**

Since I added **purchases_flutter** in my project I am facing problems every time I want to release an **IOS** version. Last week somehow I managed to release my app by clearing the cache and **derived data** folder. But today nothing is working. 

I am getting following error when I try to archive:
**Declaration of 'RCPurchases' must be imported from module 'Purchases' before it is required**

<img width="1275" alt="Screen Shot 2020-11-25 at 4 39 40 PM" src="https://user-images.githubusercontent.com/28952828/100284208-d4394b80-2f3c-11eb-80b8-064fbdf4955e.png">

**Comment by aboedo** [comment]
@signshah did you figure this out?

**Comment by metarsul** [comment]
same problem here! any updates?

**Comment by signshah** [comment]
Actually I am even not sure what worked for me.. but I cleared the cache, restated the XCode and what not... my client is little frustrated now and we are looking for some other alternative or completely remove this module and handle the payment using some other flutter package...

**Comment by aboedo** [comment]
@signshah I believe in @metarsul's case the issue was a missing setting for the iOS deployment target. 
If you're still experiencing issues, we're here to help.

**Comment by metarsul** [comment]
> Actually I am even not sure what worked for me.. but I cleared the cache, restated the XCode and what not... my client is little frustrated now and we are looking for some other alternative or completely remove this module and handle the payment using some other flutter package...

Edit your iOS/Podfile an set it to:
`platform :ios, '12.0'`

that worked for me!

**Comment by smkhalsa** [comment]
@aboedo I think this issue should be re-opened. 

I've tried updating `platform :ios, '12.0'`, but I'm still getting this error. The app builds fine otherwise.

I should note that I was getting other errors previously and had to add the empty swift file to add the bridging headers to get iOS to build.

**Comment by aboedo** [comment]
@smkhalsa I'm sorry you're experiencing issues. 
This message can be caused by a few things, could you give us a bit more context for your particular case? 
i.e.: which exact version of the sdk are you using? What's the exact error message? Do you also get this issue when running locally if you select the release scheme instead of debug?

**Comment by metarsul** [comment]
@smkhalsa another thing i Did beside setting ios to 12, was 'update to recommended settings' in xcode!

![scsht](https://user-images.githubusercontent.com/60826242/102252228-99e02000-3ee4-11eb-9c1a-e4a99b17965e.png)

**Comment by smkhalsa** [comment]
After several hours of trial and error, I was able to get it working.

I believe the thing that made it work was deleting my `Podfile` and letting flutter generate a new one for me which added the lines noted below:

```
target 'Runner' do
  // next two lines added
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by aboedo** [comment]
@smkhalsa I'm glad you got it working, and I'm sorry it was tricky. I'm frankly still not sure what's causing this inconsistency across dev setups, I think cocoapods and flutter build systems may be fighting each other here. I'll continue digging into it.
