### ISSUE TITLE
restoreTransactions returned PurchaserInfo with no entitlements

### ISSUE THREAD

**Issue by guilhermeagostinelli** [RevenueCat/purchases-flutter#135]
Hello,

Recently, `restoreTransactions` returned a `PurchaserInfo` object with no entitlements after what seemed to be a successful restoration i.e. the purchase has been properly recognized by RevenueCat (it's appearing in the dashboard as if the user indeed has an active subscription and an active entitlement).

This is the output I have in my logs * for the returned object:

> PurchaserInfo{entitlements: EntitlementInfos{all: {}, active: {}}, latestExpirationDate: null, allExpirationDates: {}, allPurchaseDates: {}, activeSubscriptions: [], allPurchasedProductIdentifiers: [], firstSeen: 2020-12-05T07:18:36.000Z, originalAppUserId: CWsIOebqLZOfhSuCYRs4654CN3B3, requestDate: 2020-12-05T07:18:39.000Z, originalApplicationVersion: null, originalPurchaseDate: null, managementURL: null, nonSubscriptionTransactions: []}

\* logged on December 5, 2020 at 4:18:50 AM UTC-3

The error occurred in production.

It should have returned a `PurchaserInfo` with an active entitlement.

It's the first problem among other ~450 restorations in which this problem did not happen.

-------------------------------

```
$ flutter doctor -v

[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.2 at /home/guilherme/Downloads/flutter
    • Framework revision 84f3d28555 (8 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/guilherme/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = /home/guilherme/Android/Sdk
    • Java binary at: /home/guilherme/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/guilherme/Downloads/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by vegaro** [comment]
Hi @guilhermeagostinelli sorry this fell through the cracks...

I see that particular user is already getting the right PurchaserInfo in our logs, so this is going to be hard to investigate. We haven't got reports like this. Do you have any other information regarding this issue that could help us figure out what's going on? Did the user do something in particular to start getting the right PurchaserInfo? I know it's been a while 🤦‍♂️
