### ISSUE TITLE
PurchaserInfo Stream instead of callback

### ISSUE THREAD

**Issue by smkhalsa** [RevenueCat/purchases-flutter#136]
Considering that Dart has built-in Streams, I'd like to request that the PurchaserInfo callback be changed to a stream to play nice with the Dart ecosystem.

**Comment by vegaro** [comment]
That would be ideal, are you particularly talking about the callback passed to `addPurchaserInfoUpdateListener`?

**Comment by smkhalsa** [comment]
Yes. Sorry for not being more clear

**Comment by vegaro** [comment]
Thanks for the suggestion! I think that makes total sense. Since this is more of a suggestion than an issue I am going to close it, but I have added it to our improvements list and the product team has been notified.
