### ISSUE TITLE
[Android Specifically] Transactions not showing in dashboard

### ISSUE THREAD

**Issue by RajeshBudhiraja** [RevenueCat/purchases-flutter#140]
**Describe the bug**
I have built flutter app and followed steps mentioned on site. When i purchase something in iOS, it's working fine. When i purchase something in android, user gets payment confirmed mail which means money is deducted but that info is not reflecting in transactions as well as PurchaserInfo. Not sure what's wrong here. Please help.

1. Environment
    [✓] Flutter (Channel stable, 1.22.1, on macOS 11.0.1 20B50, locale en-IN)
    [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [✓] Xcode - develop for iOS and macOS (Xcode 12.2)

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by rkotzy** [comment]
Are you able to provide the debug logs that reproduce the issue? https://docs.revenuecat.com/docs/debugging

**Comment by akshatjagga** [comment]
Facing a similar issue @RajeshBudhiraja — what was the fix? Thanks
