### ISSUE TITLE
** ARCHIVE FAILED ** due to problems with PurchasesHybridCommon

### ISSUE THREAD

**Issue by daniellampl** [RevenueCat/purchases-flutter#142]
Since I added `purchases_flutter` to my project, my cloud pipelines are failing when trying to sign my flutter release with `fastlane gym`. Following errors are getting logged: 

❌  /Users/vagrant/git/app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchases+HybridAdditions.h:12:12: declaration of 'RCPurchases' must be imported from module 'Purchases' before it is required
@interface RCPurchases (HybridAdditions)
        ^
⚠️  /Users/vagrant/git/app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCCommonFunctionality.h:6:2: missing submodule 'Purchases.Purchases'
#import <Purchases/Purchases.h>
        ^
⚠️  /Users/vagrant/git/app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCEntitlementInfo+HybridAdditions.h:6:2: missing submodule 'Purchases.Purchases'
#import <Purchases/Purchases.h>
        ^
⚠️  /Users/vagrant/git/app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCEntitlementInfos+HybridAdditions.h:6:2: missing submodule 'Purchases.Purchases'
#import <Purchases/Purchases.h>
        ^
⚠️  /Users/vagrant/git/app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCErrorContainer.h:6:2: missing submodule 'Purchases.Purchases'
#import <Purchases/Purchases.h>
        ^
⚠️  /Users/vagrant/git/app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCOffering+HybridAdditions.h:6:2: missing submodule 'Purchases.Purchases'
#import <Purchases/Purchases.h>
        ^
** ARCHIVE FAILED **
The following build commands failed:
	CompileSwift normal arm64 /Users/vagrant/git/app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/PurchasesHybridCommon.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

It is running perfectly on my local machine, but only when i trigger `Build` (⌘ + B) manually before.

I have no clue where these errors are coming from and I'm wondering if this problem is forced by `purchases_flutter` or due to a configuration issue made by me.

I'm using the latest version of `purchases_flutter` (2.0.0) and XCode 12.3 with Cocoapods 1.10.1.

**Comment by aboedo** [comment]
hi! 👋 sorry you're having issues. 
There are a few things that might cause this behavior. Could you try:
- Making sure that the `Podfile` specifies the [deployment target to at least iOS 10](https://github.com/RevenueCat/purchases-flutter/issues/134#issuecomment-739948702)
- Making sure that both `use_frameworks!` and `use_modular_headers!` are set [in the Podfile](https://github.com/RevenueCat/purchases-flutter/issues/133#issuecomment-745573546)
- [cleaning derived data and pod cache](https://github.com/RevenueCat/purchases-flutter/issues/129#issuecomment-722395693)


and try again? Let me know if you're still having issues after that

**Comment by daniellampl** [comment]
Thank you for your response! 

I have not idea why my Podfilen did not contain "use_frameworks!" anymore but adding it again fixed it for me.

**Comment by aboedo** [comment]
awesome! Glad to know you got it working! Closing this issue now. Have a great day!
