### ISSUE TITLE
Still got credential issue after waiting 1 week after setup.

### ISSUE THREAD

**Issue by afandiyusuf** [RevenueCat/purchases-flutter#144]
First thing first, I know that this article exists: https://support.revenuecat.com/hc/en-us/articles/360046398913
This is my flutter doctor:
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)
```
I'm using 
purchases_flutter: ^2.0.0

All feature works well,
Get all offerings, get all products, etc.

But until now I still got this error when finish purchasing some in-app purchase.
So the payment from google is work, but when the process from google completed the process back to my apps I got this error:
```
D/[Purchases] - DEBUG( 3930): POST /receipts
D/[Purchases] - DEBUG( 3930): POST /receipts 503
E/[Purchases] - ERROR( 3930): PurchasesError(code=InvalidCredentialsError, underlyingErrorMessage=Invalid Play Store credentials., message='There was a credentials issue. Check the underlying error for more details.')
I/flutter ( 3930): PlatformException(11, There was a credentials issue. Check the underlying error for more details., {code: 11, message: There was a credentials issue. Check the underlying error for more details., readableErrorCode: InvalidCredentialsError, readable_error_code: InvalidCredentialsError, underlyingErrorMessage: Invalid Play Store credentials., userCancelled: false}, null)
```

What should I do?

**Comment by aboedo** [comment]
hi @afandiyusuf! 👋 

This looks like a configuration issue. Could you open up a support ticket at https://support.revenuecat.com? Our support team will be better equipped to help you figure this out. 

We reserve GitHub Issues for bug reports, so I'm closing this ticket out, but please reach out to our support team so they can help you figure this out!

**Comment by esconts** [comment]
@afandiyusuf Hi, did you solve this issue?
