### ISSUE TITLE
Add null safety support for upcoming Flutter version

### ISSUE THREAD

**Issue by jamesblasco** [RevenueCat/purchases-flutter#149]
Flutter team is encouraging developers to migrate their packages to null safety before they release the new Flutter version that will have null safety activated by default.

https://dart.dev/null-safety/migration-guide

Right now null safety is activated by default in beta/dev/master channels and it will probably will be released in the Flutter event for 3/3/21.

I think it would be a good idea to start planning the migration before is too late

**Comment by vegaro** [comment]
Hi! We were just talking about this yesterday. We have an open ticket about this and we'll take care of it. We will keep this issue open.

**Comment by muhlba91** [comment]
@vegaro any updates on the timeline for this? nnbd is in beta since a week.

**Comment by vegaro** [comment]
I just opened a PR https://github.com/RevenueCat/purchases-flutter/pull/155

**Comment by vegaro** [comment]
The day has come. Just released https://pub.dev/packages/purchases_flutter 3.0.0 with minimum Dart 2.12.0 and the null safety changes 🦺

**Comment by jamesblasco** [comment]
Oh wow that was fast! Thank you! 💙

**Comment by IchordeDionysos** [comment]
@jamesblasco we can now close this issue right? ☺️

**Comment by vegaro** [comment]
The new release has a 50 as https://pub.dev/packages/purchases_flutter/score, because the analyzer ran on Dart 2.12.0 (build 2.12.0-259.16.beta) 🤔

**Comment by vegaro** [comment]
I just opened them an issue https://github.com/dart-lang/pub-dev/issues/4582 Hopefully it's fixable
