### ISSUE TITLE
Error when adding purchases-flutter as dependency

### ISSUE THREAD

**Issue by MSVCode** [RevenueCat/purchases-flutter#15]
Hi Revenuecat team, first of all thankyou for creating this package. I'm able to run this packages in Flutter, but not without problem initially.

When i'm creating a new Flutter project, add `purchases-flutter` as dependencies and try to run it, i got this error:
```
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\purchases_flutter-1.0.0\android\src\main\java\com\revenuecat\purchases\common\common.kt: (101, 37): Type mismatch: inferred type is String? but String was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\purchases_flutter-1.0.0\android\src\main\java\com\revenuecat\purchases\common\common.kt: (168, 41): Type mismatch: inferred type is String? but String was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\purchases_flutter-1.0.0\android\src\main\java\com\revenuecat\purchases\common\mappers.kt: (134, 31): Type mismatch: inferred type is String? but CharSequence was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':purchases_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
```

Steps:
1. `flutter create project_name`
2. Add `purchased_flutter: 1.0.0` to `pubspec.yaml`
3. Run the project

After checking the example project and some trial and error, i found out that i need to change these files:
- `<project folder>/android/build.gradle`: Change `ext.kotlin_version` to `1.3.60`. Change `gradle` version to `3.5.2`
- `<project folder/android/gradle/wrapper/gradle-wrapper.properties`: Change distribution url to `https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`

My environments are as follow:
- Flutter 1.9.1+hotfix.6
- Dart 2.5.0
- Windows 10

So i just want to ask what's the minimum requirement to use purchases-flutter? As the documentation doesn't mention it yet.

**Comment by vegaro** [comment]
Thanks for reporting @MSVCode 

Can you please share what is the `ext.kotlin_version` value and gradle distribution versions you had before changing them to 1.3.60 and 5.4.1?

Thanks!

**Comment by MSVCode** [comment]
Thanks for the response @vegaro. Here are the values before my changes:
- In `<project folder>/android/build.gradle`: `ext.kotlin_version = '1.2.71'` and `classpath 'com.android.tools.build:gradle:3.2.1'`
- In `<project folder/android/gradle/wrapper/gradle-wrapper.properties`: `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`

**Comment by vegaro** [comment]
Thanks for reporting this @MSVCode. I went ahead and made some small changes in the kotlin code to avoid this issue. The newest release https://github.com/RevenueCat/purchases-flutter/releases/tag/1.0.2 should work with older versions of Kotlin.

Thanks again!
