### ISSUE TITLE
Purchases.getOfferings returns empty list

### ISSUE THREAD

**Issue by Arcturus5404** [RevenueCat/purchases-flutter#152]
4 days ago, I could retrieve the offerings just fine. My last successful sale was 4 days ago. Suddenly they stopped working. 

Has there been a change API wise?

I also getting the following error messages:
Error in purchase: PurchasesErrorCode.unknownBackendError - There was an unknown backend error.
W/BillingClient( 8082): Error consuming purchase with token. Response code: 8

What can I do to resolve this issue?

**Comment by rkotzy** [comment]
Hey Arcturus5404 👋. No changes to the offerings API, if the list is empty, it means there was a failure fetching the products from Apple or Google. More info: https://support.revenuecat.com/hc/en-us/articles/360041793174-Why-are-products-empty-

I believe the "Error consuming purchase with token" message could be from a non-subscription purchase in the pending state, so it's not consumed.

If you need more assistance, feel free to submit a ticket though our Help Center and our support engineers will help ya out!

**Comment by wenxiangjiang** [comment]
@rkotzy Hello, I tested everything on my real device and everything is normal, but the reviewer cannot get the product information after submitting to apple for review.

**Comment by luix93** [comment]
@wenxiangjiang I'm facing the same issue, the reviewer can't fetch product informations and i'm stuck with violation of Guideline 2.1 App Completeness, but everything works fine in TestFlight.

Have you found a solution? I sent them a video of my devices proceeding to purchase successfully but my appeal failed.

I'm really at a loss here

**Comment by rkotzy** [comment]
This is an unfortunately frequent occurrence for the app review team, where their test devices are unable to fetch products for some reason. We've heard a handful of other reports of this in the past day, which is not uncommon, but could indicate some flakiness at Apple. 

Trying to explain the situation to the app review team, including a video of it working, or resubmitting the same binary are all strategies that we've heard have helped. The good news is, there's most likely nothing wrong with your app code or the Purchases SDK.

**Comment by luix93** [comment]
@rkotzy This sucks! And I wish the problem was with my code or the Purchases SDK, at least i knew WHAT was causing the issue :(

I tried to explain, sent multiple videos, done an appeal, they stand with their decision that is my app’s bug. I can’t replicate the issue on any of my devices, i really have nothing else to try. I’m now at 6 rejections for this same reason.

**Comment by rkotzy** [comment]
@luix93 are your products 'Approved', 'Waiting for Review', or 'Ready to Submit'?

If they're 'Ready to Submit', make sure you've attached them to the build you're submitting for review.

If they're 'Waiting for Review' maybe try letting the reviewer know that you submitted new products with the build and they need to approve those first (they should know this). 

If they're 'Approved' already then 🤷‍♂️

**Comment by luix93** [comment]
@rkotzy They are “Waiting for Review”. Is the first submission with IAP, and yes i attached them when i submitted the new build.

But wait, do they need to be in “Approved” status for them to work during review? Because if that’s the reason they just made me waste 5 days!

**Comment by rkotzy** [comment]
I'm almost positive the reviewers will approve any new products first, before they review the app. I remember reading a blog where someone else was facing the same issue and it took them 6 rounds to get the products reviewed properly: https://appbot.co/blog/switching-to-app-store-subscriptions/

Maybe submit a new binary and call out in the review notes that you're submitting new products with the app that need to be approved first.

**Comment by wenxiangjiang** [comment]
@luix93 I submitted a new binary yesterday, without modifying any code, and passed the review.

**Comment by luix93** [comment]
@wenxiangjiang Glad it worked out for you, I’m now preparing the 8th submission :(

**Comment by luix93** [comment]
@rkotzy Just for the sake of being sure, I’m setting up everything from scratch, new in-app, new subscription group, new app on RevenueCat with new SDK api and everything.

If after that it still won’t work, then i won’t know what else to try. Thanks for your help anyway, appreciated.

**Comment by wenxiangjiang** [comment]
@luix93 Don't click the submit button directly, recreate a new build version.

**Comment by luix93** [comment]
@wenxiangjiang I am creating a new build every time sadly, already doing that, not helping :( The only thing that is staying the same is the app version, but I’m at build 10 for this version right now, is nuts.

**Comment by Arcturus5404** [comment]
Finally found my issue! I added a new item to a different app in Google Play with the same sku. It gave an error, so I renamed it. But it also renamed the original! There was no way of changing it back for the original app. 

It's all fixed now!
