### ISSUE TITLE
Flutter iOS error: could not build Objective-C module 'PurchasesHybridCommon'

### ISSUE THREAD

**Issue by hemang249** [RevenueCat/purchases-flutter#168]
Trying to integrate Revenuecat into my app, and facing this issue. Here's what i have seen so far

- Works fine on Android
- Flutter Channel -> Stable ( Did flutter upgrade as well to be sure)
- Tried to remove the .pub-cache 
- Tried to remove the .Podfile.lock and pods/ 
- Tried running a clean build

The exact error I am seeing is - could not build Objective-C module 'PurchasesHybridCommon'

Is there any important configuration I am missing out on ? 

Edit : I have tried on both debug as well release modes, still facing the same issue

**Comment by hemang249** [comment]
here are the logs when I try flutter run

/Users/mac/keemut-app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchases+H
    ybridAdditions.h:7:2: note: in module 'Purchases' imported from
    /Users/mac/keemut-app/ios/Pods/PurchasesHybridCommon/ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchases+H
    ybridAdditions.h:7:
    #import <Purchases/Purchases.h>
     ^
    /Users/mac/keemut-app/ios/Pods/Purchases/Purchases/Public/RCTransaction.h:24:1: error: 'RCTransaction' with
    definition in module 'Purchases.RCTransaction' has different definitions in different modules; first difference is this
    method
    + (instancetype)new NS_UNAVAILABLE;
    ^
    /Users/mac/keemut-app/build/ios/Debug-iphonesimulator/PurchasesCoreSwift/PurchasesCoreSwift.framework/Headers/Purc
    hasesCoreSwift-Swift.h:276:1: note: but in 'PurchasesCoreSwift.Swift' found method
    + (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
    ^
    <unknown>:0: error: could not build Objective-C module 'PurchasesHybridCommon'
    rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at
    /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/rsync.c(244) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by hemang249** [comment]
Upon hours of Trial and error I finally managed to fix the issue. My podfile had a line like : config.build_settings['SWIFT_VERSION'] = '4.2'

Upon commenting out this line I was able to get the app running fine. Not aware of the underlying cause thought. Should be something that would be helpful if mentioned as a potential pitfall in the documentation.

My podfile after commenting out the line looks like this :

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # config.build_settings['SWIFT_VERSION'] = '4.2'  Had to comment this line to get the app to run
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
        'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
        'PERMISSION_SENSORS=0'
      ] 
    end
  end
end

**Comment by aboedo** [comment]
Hi! 👋 thanks for opening, and for reporting back once you got it working. 
Jeez, that one must have been frustrating. 
Our SDK does require Swift 5.0, and we do specify it in the [Podspec](https://github.com/RevenueCat/purchases-flutter/blob/develop/ios/purchases_flutter.podspec#L20), but it's really unfortunate that this doesn't generate a more descriptive error. 

out of curiosity: did you add that line yourself or was it auto-added by flutter? 
the current version of flutter doesn't seem to add it, but I think older versions did

**Comment by aboedo** [comment]
I'm not sure what we can do to prevent this from happening to other devs in the future, but I'm going to do some research. In the meantime, I added a new section to our [Flutter installation guide](https://docs.revenuecat.com/docs/flutter#ios-swift-version)

**Comment by hemang249** [comment]
> Hi! wave thanks for opening, and for reporting back once you got it working.
> Jeez, that one must have been frustrating.
> Our SDK does require Swift 5.0, and we do specify it in the [Podspec](https://github.com/RevenueCat/purchases-flutter/blob/develop/ios/purchases_flutter.podspec#L20), but it's really unfortunate that this doesn't generate a more descriptive error.
> 
> out of curiosity: did you add that line yourself or was it auto-added by flutter?
> the current version of flutter doesn't seem to add it, but I think older versions did

It was added by me, The permissions_handler dependency required that line. But the dependency works fine without it as well, may have been a redundant line in their Setup docs.

**Comment by aboedo** [comment]
that makes sense, `permission_handler` probably works with any Swift >= 4.2 so it was needed as a min and not a max. 
I'll try to compile a list of common issues and fixes and set it up as a troubleshooting reference. 

I'm closing this issue, but thanks again for opening, I hope it helps others who might run into it.
