### ISSUE TITLE
Bugs on null-safety app

### ISSUE THREAD

**Issue by jonatadashi** [RevenueCat/purchases-flutter#176]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)

**Describe the bug**
I'm running the example, which works as expected. But as soon as I migrate to null-safety following the [official guide](https://dart.dev/null-safety/migration-guide) errors arise.

```dart
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String' in type cast
#0      new PurchaserInfo.fromJson.<anonymous closure> (package:purchases_flutter/purchaser_info_wrapper.dart:66:68)
#1      MapMixin.map (dart:collection/maps.dart:170:28)
#2      new PurchaserInfo.fromJson (package:purchases_flutter/purchaser_info_wrapper.dart:66:18)
#3      Purchases.getPurchaserInfo (package:purchases_flutter/purchases_flutter.dart:313:26)
<asynchronous suspension>
#4      _MyAppState.initPlatformState (package:purchases_flutter_example/main.dart:33:35)
<asynchronous suspension>
```
See debug log for more info.

1. [Flutter doctor](https://gist.github.com/jonatadashi/28c1bd4ac0e98bdf42ed5d94fd4ed40a)
2. [Debug log](https://gist.github.com/jonatadashi/5918f4e1f5c45759fecbe32374ce2317)
3. [Main.dart](https://gist.github.com/jonatadashi/0de7f7712b3a19c5cc7d9f813599c273)

References:
https://github.com/dart-lang/build/issues/3046

**Comment by aboedo** [comment]
Hi! 👋 thanks for opening. 

I actually noticed this yesterday as well, and when trying to upgrade the app's dependencies for null safety I ran into the fact that a couple of them (ironically maintained by the Flutter team) aren't yet compatible with null-safety. 

<img width="438" alt="image" src="https://user-images.githubusercontent.com/3922667/112367415-a381dc80-8cb8-11eb-8622-64de79ea751a.png">

But I guess we can probably get moving and at least introduce the changes on our side, and then upgrade the min SDK for the example app once its dependencies get updated. 

Leaving the issue open until then.

**Comment by NarHakobyan** [comment]
Same here

**Comment by vegaro** [comment]
@jonatadashi is this happening in Android or iOS? Can you reproduce it consistently? It looks like when building `allExpirationDates` we are trying to parse `Null` to `String`. I can't really reproduce in a real case scenario but if I force `allExpirationDates` to contain a `null` date I get your exception:

```
  static Future<PurchaserInfo> getPurchaserInfo() async {
    Map<dynamic, dynamic> result =
        await _channel.invokeMethod('getPurchaserInfo');
    result["allExpirationDates"] = {"com.lifetime": null};
    return PurchaserInfo.fromJson(result);
  }
  ```
  
So for some reason, you are getting a null expiration date, which doesn't make sense since `allExpirationDates` only contains the expirations of subscriptions, which are inherently not null. The only way to get a null date would be if there's some error parsing the JSON in the native Android side. Do you know how you got to that state or have some clue or what could be going on?

I am going to open a PR that makes sure we parse to `String?` instead of `String`. We should also update the example to use null safety. We don't have to wait for those dependencies @aboedo since those are test only dependencies:

> Why do all dependencies need to support null safety? When all of an app’s direct dependencies support null safety, you can run the app with sound null safety. When all the dev dependencies support null safety, you can run tests with sound null safety. You might also need null-safe dev dependencies for other reasons, such as code generation.
https://dart.dev/null-safety/migration-guide#check-dependency-status

**Comment by vegaro** [comment]
Just opened https://github.com/RevenueCat/purchases-flutter/pull/177 

If you can give a try to that branch it would be great. Thanks!

**Comment by NarHakobyan** [comment]
> Just opened #177
> 
> If you can give a try to that branch it would be great. Thanks!

I tried it, and the error was gone, will try it on android also

**Comment by jonatadashi** [comment]
> Just opened #177
> 
> If you can give a try to that branch it would be great. Thanks!

Awesome, this fixed it. My best guess is that lifetime returns a null value because it's infinite or rather indefinite.

Just in case, here my [Debug Log](https://gist.github.com/jonatadashi/280a0527ca03968e653cd43eabfa52e7) on successful purchase.

**Comment by vegaro** [comment]
I thought about the lifetime purchases, but that property should only contain expirations of subscriptions. I'll check again just in case I'm missing something particularly in iOS. Did that purchaser info that was giving you issues have a lifetime purchase only?
