### ISSUE TITLE
add send email or message before subscription expires

### ISSUE THREAD

**Issue by robertoltrocha** [RevenueCat/purchases-flutter#186]
Hi,

it is common for users to forget to check the subscription expiration date and after that date they want a refund or are upset, is it possible to insert an option to send email or message a few days before the subscription expires?

thanks

**Comment by aboedo** [comment]
Hi! 👋 

This is achievable with RevenueCat by combining our [webhooks](https://docs.revenuecat.com/docs/webhooks) with a tool that sends emails or push notifications, or by using our [integrations](https://www.revenuecat.com/integrations), which might look somewhat similar to [this example](https://www.revenuecat.com/blog/app-cancellation-surveys-zapier). There isn't a way to do this solely on RevenueCat, though. 

We reserve GitHub issues for bug reports only, so I'm closing this ticket as a feature request. Feel free to check out our [Help Center](https://support.revenuecat.com/hc/en-us) if you need help getting set up.
