### ISSUE TITLE
Promoted In-App Purchases

### ISSUE THREAD

**Issue by ibrahimdevs** [RevenueCat/purchases-flutter#187]
My apps are written with Flutter and I have to handle Promoted In-App Purchases with RevenueCat.
Is flutter sdk supports this? If it is not, is there any workaround with platform specific code etc?

**Comment by aboedo** [comment]
Hi! 👋 

Support for this is in our backlog, and it has been implemented in some of our sdks, it just hasn't made its way into `purchases-flutter` just yet. 

We reserve GitHub issues for bug reports only. If you need more help with this or to get set up, visit our [Help Center](https://support.revenuecat.com) or open up a support ticket there.
