### ISSUE TITLE
Flutter multi-platform support

### ISSUE THREAD

**Issue by jamesblasco** [RevenueCat/purchases-flutter#188]
Hello, the feature request website is not working.

<img width="828" alt="Screenshot 2021-04-19 at 10 47 09" src="https://user-images.githubusercontent.com/19904063/115208195-995ace80-a0fc-11eb-8165-26d16908fe23.png">

I hope that you consider implementing the API rest with plain dart so Flutter Devs can use revenue cat in Flutter web, linux, and windows. I will be working on this for my project and will make it available for any other dev

https://github.com/jamesblasco/purchases

But hope you consider integrating it officially.

Also, it would be very helpful if you could point me out to a open API file with the revenue cat

**Comment by aboedo** [comment]
Hi! Thanks for posting this! 🎉  I'm sure it'll be helpful to a lot of folks. 

We reserve GitHub issues for bug reports only, so I'm going to close out this ticket, however I'll leave it unlocked for discussion.
