### ISSUE TITLE
restoreTransactions never completes on Android sandbox

### ISSUE THREAD

**Issue by armandojimenez** [RevenueCat/purchases-flutter#198]
Hi, When I have an active subscription, and I uninstall and re-install the app and try to restore,  Purchases.restoreTransactions(); never complete, it just stay there forever, no error or completion. In iOS it works.

But if I close and open the app, the premium entitlement is there and the user see the promised pro content. I don't know what is the problem.

Logs just show this:
```
D/[Purchases] - DEBUG(30975): ℹ️ Restoring purchases
D/[Purchases] - DEBUG(30975): ℹ️ Querying purchase history for type subs
```

**Comment by armandojimenez** [comment]
Any help with this?

**Comment by armandojimenez** [comment]
I open the android app, and restore and and purchase never completes, it just keep waiting... then I close and open the app, and everything works... this is in a closed track

**Comment by beylmk** [comment]
@armandojimenez looking into this today for you!

**Comment by beylmk** [comment]
@armandojimenez it's possible for restoreTransactions() to throw a PlatformException. do you have a try/catch around your call? that might help us figure out what's going on!

**Comment by armandojimenez** [comment]
Just to let you know the flow ->

- Install app for first time on Android
- I call `await Purchases.setDebugLogsEnabled(Flavor.isDevelopment);
    await Purchases.setup(ApiKey.revenueCatApiKey);` on my main, works great on iOS.

- Click on paywall to make a purchase, final PurchaserInfo purchaserInfo =
            await Purchases.purchasePackage(package); never completes, it just stay there and never completes. Same thing happens if instead you click on restore subscription, final PurchaserInfo restoredInfo = await Purchases.restoreTransactions(); never complete or return, no logs.
- Close and open the app, everything works, can make a purchase or restore. On iOS no problem.

It's on a try/catch, no errors, simply the method never returns, so it keeps awaiting

Purchase code, stays forever awaiting : await Purchases.purchasePackage(package);
`/// Fetch available packages
  Future<void> _getProductsAndCompletePurchase(Offerings offerings,
      {required BuildContext context}) async {
    if (offerings.current != null &&
        offerings.current!.availablePackages.isNotEmpty) {
      try {
        final Package package =
            offerings.current!.availablePackages[selectedOffer];
        Logger.log('Purchasing Product: ${package.identifier}',
            className: '$PremiumModalProvider');

        final PurchaserInfo purchaserInfo =
            await Purchases.purchasePackage(package);

        final bool isPro = purchaserInfo.entitlements.all
                .containsKey(CommonConstants.proEntitlement) &&
            purchaserInfo
                .entitlements.all[CommonConstants.proEntitlement]!.isActive;

        if (isPro) {
          // User became pro!!! 🎉🙏🏼 Celebration!!!
          Loading.dismiss();
          getIt<AnalyticsService>().logBecamePremium(package.identifier);
          getIt<AppProvider>().updateProStatus(isPro: true, context: context);
          return;
        }
      } on PlatformException catch (e) {
        Loading.dismiss();
        Logger.log('Error purchasing: $e');
        final errorCode = PurchasesErrorHelper.getErrorCode(e);
        // Show error only if user did not cancel
        if (errorCode != PurchasesErrorCode.purchaseCancelledError) {
          _showError();
        }
      }
    } else {
      Loading.dismiss();
      _showError();
    }
  }`

Restore Code:
`/// Restore premium for user, Thanks user 😍
  static Future<void> restoreSubscription(BuildContext context) async {
    Loading.show(indicator: const CircularLoading());
    try {
      final PurchaserInfo restoredInfo = await Purchases.restoreTransactions();
      // Check restored purchaserInfo to see if entitlement is now active
      final bool isPro = restoredInfo.entitlements.all
              .containsKey(CommonConstants.proEntitlement) &&
          restoredInfo
              .entitlements.all[CommonConstants.proEntitlement]!.isActive;

      if (isPro) {
        // User became or restored pro!!! 🎉🙏🏼 Celebration!!!
        Loading.dismiss();
        await showOkAlertDialog(
          context: context,
          okLabel: 'ok'.tr(),
          title: 'sub_restore.title'.tr(),
          message: 'sub_restore.message'.tr(),
        );
        getIt<AnalyticsService>().logRestoredPremium();
        getIt<AppProvider>().updateProStatus(isPro: true, context: context);
        return;
      } else {
        Loading.dismiss();
        await showOkAlertDialog(
            context: context,
            okLabel: 'ok'.tr(),
            title: 'sub_restore.not_found_title'.tr(),
            message: 'sub_restore.not_found_desc'.tr());
      }
    } on PlatformException catch (e) {
      // Error restoring purchases
      Logger.log('Error restoring sub: $e');
      Loading.dismiss();
      _showError();
    }
  }`

**Comment by beylmk** [comment]
@armandojimenez i'm digging into this. in the meantime, can you please provide what version of the flutter SDK you are using?

**Comment by beylmk** [comment]
also, is Purchases.setup() completing for you on Android?

**Comment by armandojimenez** [comment]
Yes, Purchases.setup is completing, and after I call getPurchasesInfo to get the entitlements

Flutter version :Channel stable, 2.2.1, on macOS 12.0 21A5248p darwin-arm, locale en-US

Logs:
`/flutter (32143): [🌎 Easy Localization] [DEBUG] Localization initialized


[AppConfig] Init GetIt


[AppConfig] Init Hive


D/[Purchases] - DEBUG(32143): ℹ️ Debug logging enabled


D/[Purchases] - DEBUG(32143): ℹ️ SDK Version - 4.0.5


D/[Purchases] - DEBUG(32143): 👤 Initial App User ID - null


D/[Purchases] - DEBUG(32143): 👤 Setting new anonymous App User ID - %s


D/[Purchases] - DEBUG(32143): 👤 Identifying App User ID: $RCAnonymousID:95389d759b4745298a07bd00e4715121


D/[Purchases] - DEBUG(32143): ℹ️ Deleting old synced subscriber attributes that don't belong to $RCAnonymousID:95389d759b4745298a07bd00e4715121


D/[Purchases] - DEBUG(32143): ℹ️ App foregrounded


D/[Purchases] - DEBUG(32143): ℹ️ PurchaserInfo cache is stale, updating from network in foreground.


D/[Purchases] - DEBUG(32143): ℹ️ Offerings cache is stale, updating from network in foreground


D/[Purchases] - DEBUG(32143): 😻 Offerings updated from network.


D/[Purchases] - DEBUG(32143): ℹ️ Skipping updating pending purchase queue since BillingClient is not connected yet.


D/[Purchases] - DEBUG(32143): ℹ️ No subscriber attributes to synchronize.


D/[Purchases] - DEBUG(32143): ℹ️ Listener set


2
I/System.out(32143): (HTTPLog)-Static: isSBSettingEnabled false


D/[Purchases] - DEBUG(32143): ℹ️ Starting connection for com.android.billingclient.api.BillingClientImpl@5f527d0


D/[Purchases] - DEBUG(32143): ℹ️ No cached PurchaserInfo, fetching from network.


D/[Purchases] - DEBUG(32143): 😻 PurchaserInfo updated from network.


D/[Purchases] - DEBUG(32143): ℹ️ Billing Service Setup finished for com.android.billingclient.api.BillingClientImpl@5f527d0


D/[Purchases] - DEBUG(32143): ℹ️ Updating pending purchase queue


D/[Purchases] - DEBUG(32143): ℹ️ API request started: GET /subscribers/%24RCAnonymousID%3A95389d759b4745298a07bd00e4715121


D/[Purchases] - DEBUG(32143): ℹ️ API request completed with status: GET /subscribers/%24RCAnonymousID%3A95389d759b4745298a07bd00e4715121 201


D/[Purchases] - DEBUG(32143): ℹ️ Sending latest PurchaserInfo to listener.


D/[Purchases] - DEBUG(32143): ℹ️ PurchaserInfo updated, sending to listener.


2
I/System.out(32143): (HTTPLog)-Static: isSBSettingEnabled false


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Start


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Init state


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Build


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Init Localization Delegate


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Init provider


D/[Purchases] - DEBUG(32143): ℹ️ API request started: GET /subscribers/%24RCAnonymousID%3A95389d759b4745298a07bd00e4715121/offerings


D/[Purchases] - DEBUG(32143): ℹ️ API request completed with status: GET /subscribers/%24RCAnonymousID%3A95389d759b4745298a07bd00e4715121/offerings 200


D/[Purchases] - DEBUG(32143): ℹ️ Requesting products from the store with identifiers: believe_4999_lifetime, believe_1499_1y_3d0, believe_199_1m_3d0


D/[Purchases] - DEBUG(32143): ℹ️ Querying subs


D/[Purchases] - DEBUG(32143): ℹ️ Querying inapp


D/[Purchases] - DEBUG(32143): ℹ️ Cleaning previously sent tokens


D/[Purchases] - DEBUG(32143): ℹ️ Tokens already posted: []


D/[Purchases] - DEBUG(32143): ℹ️ Saving tokens []


D/[Purchases] - DEBUG(32143): ℹ️ Tokens already posted: []


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Load Localization Delegate


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Load asset from assets/translations


D/[Purchases] - DEBUG(32143): ℹ️ Products request finished for believe_4999_lifetime, believe_1499_1y_3d0, believe_199_1m_3d0


D/[Purchases] - DEBUG(32143): 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"believe_1499_1y_3d0","type":"subs","price":"$14.99","price_amount_micros":14990000,"price_currency_code":"USD","title":"Creer Premium+ (Creer - Afirmaciones y Recordatorios Diarios)","description":"Desbloquea todas las funciones y contenido","subscriptionPeriod":"P1Y","freeTrialPeriod":"P3D","skuDetailsToken":"AEuhp4JRipuIpC0WAdSvcY6RrIIM6_u__excmBELdME5cRddUX8SjkCCBVI_Ey79wmQ="}, SkuDetails: {"productId":"believe_199_1m_3d0","type":"subs","price":"$2.49","price_amount_micros":2490000,"price_currency_code":"USD","title":"Creer Premium+ (Creer - Afirmaciones y Recordatorios Diarios)","description":"Desbloquea todas las funciones y contenido","subscriptionPeriod":"P1M","freeTrialPeriod":"P3D","skuDetailsToken":"AEuhp4JPgF2wDOlRsDxmjnrU8plJ_ltNDij0WGqBqj50hCZCIRoXa8wuxNJEWWq7RUQ="}

D/[Purchases] - DEBUG(32143): 💰 believe_1499_1y_3d0 - SkuDetails: {"productId":"believe_1499_1y_3d0","type":"subs","price":"$14.99","price_amount_micros":14990000,"price_currency_code":"USD","title":"Creer Premium+ (Creer - Afirmaciones y Recordatorios Diarios)","description":"Desbloquea todas las funciones y contenido","subscriptionPeriod":"P1Y","freeTrialPeriod":"P3D","skuDetailsToken":"AEuhp4JRipuIpC0WAdSvcY6RrIIM6_u__excmBELdME5cRddUX8SjkCCBVI_Ey79wmQ="}


D/[Purchases] - DEBUG(32143): 💰 believe_199_1m_3d0 - SkuDetails: {"productId":"believe_199_1m_3d0","type":"subs","price":"$2.49","price_amount_micros":2490000,"price_currency_code":"USD","title":"Creer Premium+ (Creer - Afirmaciones y Recordatorios Diarios)","description":"Desbloquea todas las funciones y contenido","subscriptionPeriod":"P1M","freeTrialPeriod":"P3D","skuDetailsToken":"AEuhp4JPgF2wDOlRsDxmjnrU8plJ_ltNDij0WGqBqj50hCZCIRoXa8wuxNJEWWq7RUQ="}


D/[Purchases] - DEBUG(32143): ℹ️ Requesting products from the store with identifiers: believe_4999_lifetime


D/[Purchases] - DEBUG(32143): ℹ️ Products request finished for believe_4999_lifetime


D/[Purchases] - DEBUG(32143): 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"believe_4999_lifetime","type":"inapp","price":"$49.99","price_amount_micros":49990000,"price_currency_code":"USD","title":"Creer Premium+ (De por vida) (Creer - Afirmaciones y Recordatorios Diarios)","description":"Desbloquea todas las funciones y contenido","skuDetailsToken":"AEuhp4LLQ-V8WHS1FsBEPXHVzAR3fpIUE_IOEF3h9GEU6GTvOY8Cpw0wkPUhyWbNqgg="}


D/[Purchases] - DEBUG(32143): 💰 believe_4999_lifetime - SkuDetails: {"productId":"believe_4999_lifetime","type":"inapp","price":"$49.99","price_amount_micros":49990000,"price_currency_code":"USD","title":"Creer Premium+ (De por vida) (Creer - Afirmaciones y Recordatorios Diarios)","description":"Desbloquea todas las funciones y contenido","skuDetailsToken":"AEuhp4LLQ-V8WHS1FsBEPXHVzAR3fpIUE_IOEF3h9GEU6GTvOY8Cpw0wkPUhyWbNqgg="}


[AppConfig] Timezone: America/Puerto_Rico


[NotificationService] Init notification service


[BelieveApp] _initApp() executed in 0:00:00.251329


[SplashPage] Showing initial config


2
I/jimenez.believ(32143): The ClassLoaderContext is a special shared library.


I/DynamiteModule(32143): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:211512000


I/DynamiteModule(32143): Selected remote version of com.google.android.gms.ads.dynamite, version >= 211512000


D/DynamitePackage(32143): Instantiated singleton DynamitePackage.


D/DynamitePackage(32143): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl


I/Ads     (32143): Updating ad debug logging enablement.


W/ConnectionStatusConfig(32143): Dynamic lookup for intent failed for action: com.google.android.gms.leibniz.events.service.START


E/GmsClient(32143): unable to connect to service: com.google.android.gms.leibniz.events.service.START on com.google.android.gms


I/jimenez.believ(32143): Thread[6,tid=800,WaitingInMainSignalCatcherLoop,Thread*=0xb400007a47d7c630,peer=0x14440290,"Signal Catcher"]: reacting to signal 28


I/jimenez.believ(32143):


I/jimenez.believ(32143): SIGSAVEPRF profile save


I/WebViewFactory(32143): Loading com.google.android.webview version 90.0.4430.210 (code 443021034)


W/jimenez.believ(32143): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)


W/jimenez.believ(32143): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)


W/jimenez.believ(32143): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)


W/jimenez.believ(32143): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)


W/jimenez.believ(32143): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)


I/cr_LibraryLoader(32143): Loaded native library version number "90.0.4430.210"


I/cr_CachingUmaRecorder(32143): Flushed 4 samples from 4 histograms.


W/jimenez.believ(32143): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)


W/cr_media(32143): Requires BLUETOOTH permission


W/Ads     (32143): Update ad debug logging enablement as false


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Start


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Build


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Init Localization Delegate


I/flutter (32143): [🌎 Easy Localization] [DEBUG] Init provider


Reloaded 1 of 2028 libraries in 925ms.

I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


D/Vibrator(32143): binder call to service pkg=dev.armandojimenez.believe, effect=OneShot{mDuration=10, mAmplitude=-1, mMagnitude=-1, mMagnitudeType=TYPE_EXTRA}


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


D/Vibrator(32143): binder call to service pkg=dev.armandojimenez.believe, effect=OneShot{mDuration=10, mAmplitude=-1, mMagnitude=-1, mMagnitudeType=TYPE_EXTRA}


[BelieveApp] Saving Reminders


I/TextToSpeech(32143): Sucessfully bound to com.google.android.tts


I/TextToSpeech(32143): Connected to ComponentInfo{com.google.android.tts/com.google.android.apps.speech.tts.googletts.service.GoogleTTSService}


I/TextToSpeech(32143): Set up connection to ComponentInfo{com.google.android.tts/com.google.android.apps.speech.tts.googletts.service.GoogleTTSService}


D/[Purchases] - DEBUG(32143): ℹ️ Ending connection for com.android.billingclient.api.BillingClientImpl@5f527d0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


D/Vibrator(32143): binder call to service pkg=dev.armandojimenez.believe, effect=OneShot{mDuration=10, mAmplitude=-1, mMagnitude=-1, mMagnitudeType=TYPE_EXTRA}


[AppConfig] Timezone: America/Puerto_Rico


[NotificationService] Init notification service


[BelieveApp] _initApp() executed in 0:00:00.061945


[AppProvider] init app


[AppConfig] App open count: 1


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


I/SurfaceControl(32143): release : mNativeObject = -5476376625717704704 - Surface(name=dev.armandojimenez.believe/dev.armandojimenez.believe.MainActivity$_32143)/@0xa0bee03 / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1810 android.view.ViewRootImpl.relayoutWindow:9005


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625717704704]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717704704]


I/SurfaceControl(32143): assignNativeObject: nativeObject = 0 Surface(name=null)/@0xbf4bc7d / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9965 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995


I/SurfaceControl(32143): release : mNativeObject = -5476376625717210320 - Surface(name=Surface(name=2408e7e InputMethod)/@0xad36ef5 - animation-leash)/@0x13abccc / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625717210320]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717210320]


I/SurfaceControl(32143): release : mNativeObject = -5476376625717211024 - Surface(name=Surface(name=e9239cf NavigationBar0)/@0x384b62d - animation-leash)/@0x2eb7180 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625717211024]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717211024]

I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717211024]


I/SurfaceControl(32143): release : mNativeObject = -5476376625717203808 - Surface(name=Surface(name=538f8f9 StatusBar)/@0xedcd798 - animation-leash)/@0x3d483b9 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625717203808]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717203808]


I/ViewRootImpl@e12a4b[MainActivity](32143): Relayout returned: old=(0,0,1440,3040) new=(0,0,1440,3040) req=(1440,3040)0 dur=8 res=0x1 s={true -5476376621422669952} ch=false fn=21


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


D/Vibrator(32143): binder call to service pkg=dev.armandojimenez.believe, effect=OneShot{mDuration=40, mAmplitude=-1, mMagnitude=-1, mMagnitudeType=TYPE_EXTRA}


D/PhoneWindow(32143): forceLight changed to false [dev.armandojimenez.believe/dev.armandojimenez.believe.MainActivity] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4229 com.android.internal.policy.PhoneWindow.setNavigationBarColor:4029 io.flutter.plugin.platform.PlatformPlugin.setSystemChromeSystemUIOverlayStyle:283 io.flutter.plugin.platform.PlatformPlugin.access$500:28 io.flutter.plugin.platform.PlatformPlugin$1.setSystemUiOverlayStyle:96


I/SurfaceControl(32143): release : mNativeObject = -5476376625716943504 - Surface(name=dev.armandojimenez.believe/dev.armandojimenez.believe.MainActivity$_32143)/@0xa0bee03 / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1810 android.view.ViewRootImpl.relayoutWindow:9005


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625716943504]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625716943504]


I/SurfaceControl(32143): assignNativeObject: nativeObject = 0 Surface(name=null)/@0xbf4bc7d / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9965 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995


I/SurfaceControl(32143): release : mNativeObject = -5476376625716917456 - Surface(name=Surface(name=2408e7e InputMethod)/@0xad36ef5 - animation-leash)/@0xe8734d6 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625716917456]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625716917456]


I/SurfaceControl(32143): release : mNativeObject = -5476376625717145200 - Surface(name=Surface(name=e9239cf NavigationBar0)/@0x384b62d - animation-leash)/@0x52ee357 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625717145200]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717145200]


I/SurfaceControl(32143): release : mNativeObject = -5476376625717704704 - Surface(name=Surface(name=538f8f9 StatusBar)/@0xedcd798 - animation-leash)/@0xa857e44 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625717704704]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717704704]


I/ViewRootImpl@e12a4b[MainActivity](32143): Relayout returned: old=(0,0,1440,3040) new=(0,0,1440,3040) req=(1440,3040)0 dur=14 res=0x1 s={true -5476376621422669952} ch=false fn=21


I/ViewRootImpl@e12a4b[MainActivity](32143): updateBoundsLayer: shouldReparent = false t = android.view.SurfaceControl$Transaction@3e7ab2d sc = Surface(name=Bounds for - dev.armandojimenez.believe/dev.armandojimenez.believe.MainActivity@0)/@0x199c862 frame = 21


I/SurfaceControl(32143): release : mNativeObject = -5476376625716611744 - Surface(name=dev.armandojimenez.believe/dev.armandojimenez.believe.MainActivity$_32143)/@0xa0bee03 / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1810 android.view.ViewRootImpl.relayoutWindow:9005


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625716611744]

I/SurfaceControl(32143): release : mNativeObject = -5476376625716611744 - Surface(name=dev.armandojimenez.believe/dev.armandojimenez.believe.MainActivity$_32143)/@0xa0bee03 / android.view.SurfaceControl.assignNativeObject:567 android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1810 android.view.ViewRootImpl.relayoutWindow:9005


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625716611744]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625716611744]


I/SurfaceControl(32143): assignNativeObject: nativeObject = 0 Surface(name=null)/@0xbf4bc7d / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9965 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995


I/SurfaceControl(32143): release : mNativeObject = -5476376625717060544 - Surface(name=Surface(name=2408e7e InputMethod)/@0xad36ef5 - animation-leash)/@0x7545df3 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.ImeInsetsSourceConsumer.setControl:154


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625717060544]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625717060544]


I/SurfaceControl(32143): release : mNativeObject = -5476376625716917632 - Surface(name=Surface(name=e9239cf NavigationBar0)/@0x384b62d - animation-leash)/@0x7e3ab0 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625716917632]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625716917632]


I/SurfaceControl(32143): release : mNativeObject = -5476376625716943504 - Surface(name=Surface(name=538f8f9 StatusBar)/@0xedcd798 - animation-leash)/@0xfc0cd29 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833


I/SurfaceControl(32143): nativeRelease nativeObject s[-5476376625716943504]


I/SurfaceControl(32143): nativeRelease nativeObject e[-5476376625716943504]


I/ViewRootImpl@e12a4b[MainActivity](32143): Relayout returned: old=(0,0,1440,3040) new=(0,0,1440,3040) req=(1440,3040)0 dur=7 res=0x1 s={true -5476376621422669952} ch=false fn=22


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


D/Vibrator(32143): binder call to service pkg=dev.armandojimenez.believe, effect=OneShot{mDuration=10, mAmplitude=-1, mMagnitude=-1, mMagnitudeType=TYPE_EXTRA}


[BecomePremium] Monthly selected


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 0


I/ViewRootImpl@e12a4b[MainActivity](32143): ViewPostIme pointer 1


D/[Purchases] - DEBUG(32143): ℹ️ Vending Offerings from cache


D/[Purchases] - DEBUG(32143): ℹ️ Checking if cache is stale AppInBackground false


[PremiumModalProvider] Purchasing Product: $rc_monthly


D/[Purchases] - DEBUG(32143): ℹ️ Vending Offerings from cache


D/[Purchases] - DEBUG(32143): 💰 Purchase started - product:  SkuDetails: {"productId":"believe_199_1m_3d0","type":"subs","price":"$2.49","price_amount_micros":2490000,"price_currency_code":"USD","title":"Creer Premium+ (Creer - Afirmaciones y Recordatorios Diarios)","description":"Desbloquea todas las funciones y contenido","subscriptionPeriod":"P1M","freeTrialPeriod":"P3D","skuDetailsToken":"AEuhp4JPgF2wDOlRsDxmjnrU8plJ_ltNDij0WGqBqj50hCZCIRoXa8wuxNJEWWq7RUQ="}  - offering: default


D/[Purchases] - DEBUG(32143): 💰 Purchasing product: believe_199_1m_3d0


D/[Purchases] - DEBUG(32143): ℹ️ Checking if cache is stale AppInBackground false`

**Comment by beylmk** [comment]
@armandojimenez Can you try creating a new test user? Sometimes old test accounts have unfinished transactions, and then attempting a restore can hang. You can follow the steps here for fully setting up testing in Play: https://docs.revenuecat.com/docs/google-play-store

I'll work on reproducing this on my side in the meantime...

**Comment by armandojimenez** [comment]
I did and still the same issue. I move the init Purchases.setup() from my main (before runApp) to the first screen in the init function and now it works, I don't know why. In iOS it works on either side.

**Comment by beylmk** [comment]
I’m glad you got things working 🥳  Sorry I wasn’t able to pinpoint the issue for you.

I do see that your BillingClient connection is closed prior to making the purchase call:

```D/[Purchases] - DEBUG(32143): ℹ️ Ending connection for com.android.billingclient.api.BillingClientImpl@5f527d0```

It's possible that another plugin/some other code might be affecting the threading and/or network calls, and that for some reason moving the initialization to after runApp keeps the instance alive. Let me know if you have any further questions.
