### ISSUE TITLE
Upgrading subscription on iOS in sandbox mode simply not working

### ISSUE THREAD

**Issue by nzackoya** [RevenueCat/purchases-flutter#202]
- [ v] I have updated Purchases SDK to the latest version
- [v ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [ v] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ v] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ v] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
Upgrading subscription on iOS in sandbox simply purchases another subscription, so the entitlements has 2 active items, then it just cancels the latter. After, when you try to purchase the second subscription again, it just ignores and doesn't open the upgrade or even purchase dialog.

**Comment by vegaro** [comment]
Can you share some logs around the second purchase that is not showing the purchase dialog? Are both subscriptions in the same subscription group? You might want to check out our blog post on subscription groups 
medium.com/revenuecat-blog/ios-subscription-groups-explained-8c5b8325d4ab

**Comment by Niko-by** [comment]
I am seeing the same problem. At the same time, this was not the case in older versions of the plugin, in my other projects it works well because there is an old version of the plugin. Did you find a way to fix this?

**Comment by Niko-by** [comment]
It will be fair to say that after 3-4 attempts to pay, the subscription window will appear. I do not understand what this is connected with.

**Comment by BradenBagby** [comment]
Same problem. User upgrades a subscription and the REST API shows they now have both. The SDK shows only one. Calling `restoreTransactions` or `syncPurchases` does nothing.
