### ISSUE TITLE
Unable to set Attributes

### ISSUE THREAD

**Issue by keenhon** [RevenueCat/purchases-flutter#206]
- [Yes] I have updated Purchases SDK to the latest version
- [Yes] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [Yes] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [Yes] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [Yes] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

1. Environment
   1. Output of `flutter doctor`
      No Error
   2. How widespread is the issue. Percentage of devices affected.
       Unknown
   
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
D/[Purchases] - DEBUG(25665): ℹ️ setDisplayName called
D/[Purchases] - DEBUG(25665): ℹ️ setAttributes called

3. Steps to reproduce, with a description of expected vs. actual behavior
I created a button for user to update his particulars, however, it doesn't get updated. This happens with standard attributes like displayname and also custom attributes. Just keep changing the inputs and it doesn't get updated in the portal. debug show it's called. Also sometimes, it updates when I reload the app, which is weird.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
No error thrown.

**Additional context**

**Comment by rkotzy** [comment]
Subscriber attributes are only synced with RevenueCat servers on app launch, app backgrounded, and when purchases are made or restored - sounds like that could be what's going?

**Comment by keenhon** [comment]
Ok. Noted. Then I probably have to implement using the rest api.

**Comment by rkotzy** [comment]
REST API will work and write the attributes in real-time. 

However, it's worth noting that this logic was built into the SDK to sync attributes without overwhelming any rate limits. In addition to that POST'ing logic, the SDK will also never re-send the same attribute after it's been synced, so you can do things like call `.setEmail()` on every app launch and the SDK will only make a network request for new data. The exact rate limits are variable based on the number of subscribers your app has, but if you foresee the API usage significantly exceeding what the SDK logic was designed for (1-2 requests per install and infrequent usage after) then it may be worth exploring your own database for real-time persistence of data.
