### ISSUE TITLE
CompletePurchase

### ISSUE THREAD

**Issue by Jayvd** [RevenueCat/purchases-flutter#208]
- [V ] I have updated Purchases SDK to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [V ] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [V ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ V] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

Using other plugins or even on the native SDK, a call to `CompletePurchase` is needed in iOS (to prevent it being refunded in 3 days), but I couldn't find any similar call in RevenueCat SDK. Is the call to CompletePurchase isnt needed?

**Comment by beylmk** [comment]
Hey @Jayvd, thanks for your question. We don't have a method called `CompletePurchase`, but it looks like you're referring to the StoreKit `finishTransaction` call. The RevenueCat SDK will handle listening to your payment queue and calling `finishTransaction` for you 😸 

Let me know if you were referring to something else, or if you have further questions!
