### ISSUE TITLE
Message Codecs Crash error occurs test purchase that are canceled by the user or automatically by non test account.

### ISSUE THREAD

**Issue by jrmarkham** [RevenueCat/purchases-flutter#215]
- [ x] I have updated Purchases SDK to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/develop/CONTRIBUTING.md)
- [x ] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
I have revenue cat set up for sand box testing and I am testing on a couple of pieces of hardware. So for all iOS and all Android devices if a test purchase is canceled. I get a codex error. The purchase is wrapped in try as instructed. I get the error on line 581 of message_codec.dart. Product listing and full product purchases are working fine.

==========================================
Here is my code for calling a purchase:

```
try {
  final PurchaserInfo purchaserInfo = await Purchases.purchasePackage(package);

  if (_checkNonConsumedOwned(purchaserInfo: purchaserInfo, packageType: package.packageType)) {
    _sharedPreferencesServices.setRemoveAdsPurchased(true);
    return true;
  } else if (package.packageType == PackageType.custom && _isConsumable(package.product.identifier)) {
    debugPrint ('_runPurchase first seen ${ purchaserInfo.firstSeen}');
    debugPrint ('_runPurchase ${ purchaserInfo.toString()}');
    debugPrint ('_runPurchase non sub: last ${ purchaserInfo.nonSubscriptionTransactions.last.toString()}');
    final String _token = '${purchaserInfo.nonSubscriptionTransactions
        .last.revenueCatId}${purchaserInfo.nonSubscriptionTransactions.last.purchaseDate}';

    final Set<UserPowerUp> _powerUpSet = await _getPurchasedProducts(
        prodId: package.product.identifier,
        token: _token);

    debugPrint ('_runPurchase  power up set ${_powerUpSet.toString()}');
    for (UserPowerUp upu in _powerUpSet) {
      debugPrint ('UserPowerUp upu in _powerUpSet ${upu.toString()}');
      userPowerUpPurchased(upu);
    }

    return true;
  }
  return false;
} on PlatformException catch (e) {
  var errorCode = PurchasesErrorHelper.getErrorCode(e);
  debugPrint ('purchase errorCode ${errorCode.toString()}');
  return false;
}
```

 
=============================================
Here is the debug info: 

D/[Purchases] - DEBUG(26529): ℹ️ Vending Offerings from cache
D/[Purchases] - DEBUG(26529): 💰 Purchase started - product:  com.revenuecat.purchases.models.ProductDetails@5356bd50  - offering: default
D/[Purchases] - DEBUG(26529): 💰 Purchasing product: reserves
D/[Purchases] - DEBUG(26529): ℹ️ Checking if cache is stale AppInBackground false
W/ProxyBillingActivity(26529): Activity finished with resultCode 0 and billing's responseCode: 1
W/BillingHelper(26529): Couldn't find purchase lists, trying to find single data.
W/BillingHelper(26529): Received a bad purchase data.
W/BillingHelper(26529): Couldn't find single purchase data as well.
E/[Purchases] - ERROR(26529): 🤖‼️ BillingWrapper purchases failed to update: DebugMessage: . ErrorCode: USER_CANCELED.null
E/[Purchases] - ERROR(26529): 🤖‼️ Purchase was cancelled.
W/prises.swipewa(26529): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)

=======================================
and here is the error in frames

![frame](https://user-images.githubusercontent.com/3997866/125177001-6594bf80-e1a6-11eb-924a-99c5a872f7b5.png)

and the message codecs

![message_codecs](https://user-images.githubusercontent.com/3997866/125177006-77766280-e1a6-11eb-98bb-40bb5a2faa26.png)

=======================================
Here is my flutter doctor output: 

[✓] Flutter (Channel stable, 2.0.6, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /usr/local/lib/flutter
    • Framework revision 1d9032c7e1 (2 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at /Users/johnmarkham/Library/Android/sdk/
    • Platform android-30, build-tools 31.0.0-rc5
    • ANDROID_HOME = /Users/johnmarkham/Library/Android/sdk/
    • Java binary at: /Applications/JetBrains/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/JetBrains/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/JetBrains/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
    • IntelliJ at /Users/johnmarkham/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 58.0.3
    • Dart plugin version 211.7665

[✓] Connected device (2 available)
    • Pixel 3 (mobile) • 8A8X0MVUT • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome    • web-javascript • Google Chrome 91.0.4472.114
    ! Error: John’s iPad is not connected. Xcode will continue when John’s iPad is connected. (code -13)
    ! Error: John’s iPhone is not connected. Xcode will continue when John’s iPhone is connected. (code -13)

=========================
plugins: 

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  auto_size_text: ^2.1.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  firebase_auth: ^2.0.0
  google_mobile_ads: ^0.13.2
  firebase_dynamic_links: ^2.0.6
  firebase_messaging: ^10.0.3
  google_sign_in: ^5.0.4
  apple_sign_in: ^0.1.0
  random_string: ^2.1.0
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  soundpool: ^2.1.0
  assets_audio_player: ^3.0.3+3
  jiffy: ^4.1.0
  rate_my_app: ^1.1.0+1
  purchases_flutter: ^3.3.1
  connectivity: ^3.0.6
  dio: ^4.0.0
  device_info: ^2.0.2
  share: ^2.0.4
  confetti: ^0.5.5
  flutter_circular_text: ^0.3.1
  ntp: ^2.0.0
  strings: ^0.2.2
  convex_bottom_bar: ^3.0.0
  game_service_connect: ^0.0.10

**Comment by jrmarkham** [comment]
MY error is extremely detailed please let me know what is missing.

**Comment by vegaro** [comment]
Just to make sure I understand what's going on... your code doesn't enter in the catch section right? What happens if you just catch all exceptions? Without catching only PlatformException.

Thanks for the detailed issue by the way. I'm not sure why the bot asked for more information 😬

**Comment by vegaro** [comment]
Maybe this helps https://stackoverflow.com/a/54824475?

**Comment by jrmarkham** [comment]
Yes that is correct not getting to the catch exception. I'll checkout my IDE setting. thanks.

**Comment by jrmarkham** [comment]
I think ups are right; this seems to be an Intellij issue. Still poking around I found a similar crash that works if you emulate thru command line but crashes thru Intellij. Curious. I'll investigate more and close the issue if all is well. Thanks.

**Comment by vegaro** [comment]
Let us know if that's the case when you close the issue. We are also curious about this one!

**Comment by jrmarkham** [comment]
Certainly.

**Comment by jrmarkham** [comment]
Ok I am certain the problem was either an IDE setting or bug or related to null-safety. I updated my project to null safety and it runs perfectly fine w/ the platform catch error now from the IDE launching the app; also fine via command line. I have had other older projects have the same issue on Platform Exception catches that would fail w/ IDE launch and work fine via command line. 

But the problem is definitely not on the plugin side. Thanks for you attention on this matter.

**Comment by vegaro** [comment]
Thanks for letting us know. I will close the issue then.
