### ISSUE TITLE
GP Subscriptions issue ("Acknowledge purchases or they will be automatically refunded")

### ISSUE THREAD

**Issue by urbanMar** [RevenueCat/purchases-flutter#219]
```

 Acknowledge purchases or they will be automatically refunded
We've detected that your app is not acknowledging all in-app purchases or subscriptions. Starting with Billing Library 2.0, all purchases must be acknowledged within three days or they will be automatically refunded.

```

[Learn more](https://developer.android.com/google/play/billing/integrate#acknowledge)

In google play console I get such an issue. 
-in rc we have 3 products
-in GP we have 3 products
-in app we are using only 1 (and showing 1)

**Comment by beylmk** [comment]
Hey @urbanMar, this issue could be related to the other you recently opened. RevenueCat will acknowledge purchases for you, unless some other kind of error is found...I'm hoping that fixing the other "invalid package name" issue will solve this one for you too 🤞
