### ISSUE TITLE
iOS app crash on latest Flutter channel

### ISSUE THREAD

**Issue by tapeo** [RevenueCat/purchases-flutter#22]
On flutter `beta` and `dev` channel, using `1.0.4` version of `purchases-flutter`, when call method `Purchases.getPurchaserInfo()` iOS app crashes.

On Android it works.

This is the logs with `flutter run`:

```
 └─Compiling, linking and signing...                        12,6s
Xcode build done.                                           42,0s
Installing and launching...                                        26,3s
Lost connection to device.                                              
Syncing files to device iPhone di Matteo Ricupero...                    
                                                   
matteo@teobook fitet_unofficial_flutter % 
```

Actually no logs so I thought it was an issue with the Swift native code. If I run it from Xcode, it works.

**Comment by vegaro** [comment]
What version of XCode are you using @tapeo ?

**Comment by tapeo** [comment]
I found that was an issue with my code. I haven't call `setup()` method so it crashed. Maybe an exception if you don't call that method should be useful.
