### ISSUE TITLE
PlatformException(22, There is an issue with your configuration....

### ISSUE THREAD

**Issue by urbanMar** [RevenueCat/purchases-flutter#220]
Affter success transaction with GP I get:
`[   +6 ms] I/flutter (10430): PlatformException(22, There is an issue with your configuration. Check the underlying error for more details., {code: 22, message: There is an issue with your configuration. Check the underlying error for more details., readableErrorCode: ConfigurationError, readable_error_code: ConfigurationError, underlyingErrorMessage: Invalid package name., userCancelled: false}, null)
`

LOGS:
`[+53934 ms] D/[Purchases] - DEBUG(10430): ℹ️ Vending PurchaserInfo from cache.
[   +7 ms] D/[Purchases] - DEBUG(10430): ℹ️ Checking if cache is stale AppInBackground false
[        ] D/[Purchases] - DEBUG(10430): ℹ️ Vending Offerings from cache
[   +4 ms] D/[Purchases] - DEBUG(10430): ℹ️ Checking if cache is stale AppInBackground false
[  +35 ms] I/flutter (10430): 2021-07-22T13:25:27.188315	I	purchas product:	 Product{identifier: ci1yintroa, description: Intro offer for the start of our new app. One year all functionality. , title: camping.info 1 year - Intro Offer (Camping Info Test), price: 25.99, priceString: 25,99 zł, currencyCode: PLN, introductoryPrice: IntroductoryPrice{introPrice: 0.0, introPriceString: 0,00 zł, introPricePeriod: P1W, introPricePeriodUnit: DAY, introPricePeriodNumberOfUnits: 7, introPriceCycles: 1}}
[        ] I/flutter (10430): 2021-07-22T13:25:27.189017	I	purchaserInfo2:	 {}
[+19454 ms] D/[Purchases] - DEBUG(10430): ℹ️ Requesting products from the store with identifiers: ci1yintroa
[  +45 ms] D/[Purchases] - DEBUG(10430): ℹ️ Products request finished for ci1yintroa
[        ] D/[Purchases] - DEBUG(10430): 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"ci1yintroa","type":"subs","price":"25,99 zł","price_amount_micros":25990000,"price_currency_code":"PLN","title":"camping.info 1 year - Intro Offer (Camping Info Test)","description":"Intro offer for the start of our new app. One year all functionality. ","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4Lrm89Xc6dQOY3J4fqEuA0GTzGD0Ia52nyUbNMYO_tXjQ8y18IuZdKWI4J58dDn"}
[        ] D/[Purchases] - DEBUG(10430): 💰 ci1yintroa - SkuDetails: {"productId":"ci1yintroa","type":"subs","price":"25,99 zł","price_amount_micros":25990000,"price_currency_code":"PLN","title":"camping.info 1 year - Intro Offer (Camping Info Test)","description":"Intro offer for the start of our new app. One year all functionality. ","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4Lrm89Xc6dQOY3J4fqEuA0GTzGD0Ia52nyUbNMYO_tXjQ8y18IuZdKWI4J58dDn"}
[   +7 ms] D/[Purchases] - DEBUG(10430): 💰 Purchase started - product:  com.revenuecat.purchases.models.ProductDetails@15cbb8c5 null
[        ] D/[Purchases] - DEBUG(10430): 💰 Purchasing product: ci1yintroa
[  +90 ms] D/HwCust  (10430): Create obj success use class android.app.HwCustActivityImpl
[        ] D/HwCust  (10430): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
[  +16 ms] V/ActivityThread(10430): ActivityThread,callActivityOnCreate
[  +36 ms] D/ActivityThread(10430): add activity client record, r= ActivityRecord{32c4185 token=android.os.BinderProxy@ac325cd {campingtest.info.app/com.android.billingclient.api.ProxyBillingActivity}} token= android.os.BinderProxy@ac325cd
[   +7 ms] D/OpenGLRenderer(10430):   HWUI Binary is  enabled
[  +38 ms] I/PressGestureDetector(10430): onAttached begin
[   +3 ms] I/PressGestureDetector(10430): onAttached end
[  +12 ms] I/PressGestureDetector(10430): HiTouch restricted: AboardArea.
[  +33 ms] D/mali_winsys(10430): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
[        ] D/OpenGLRenderer(10430):   HWUI Binary is  enabled
[+10592 ms] W/InputMethodManager(10430): startInputReason = 1
[  +95 ms] W/BillingHelper(10430): Couldn't find purchase lists, trying to find single data.
[   +6 ms] D/[Purchases] - DEBUG(10430): ℹ️ BillingWrapper purchases updated: skus: [ci1yintroa], orderId: GPA.3327-4332-8428-59676, purchaseToken: befaealoialknogddeppdaca.AO-J1OxeALUsqbmExEcDwTQi4i7LnMk7U1pBexaLQD9jiu4ZN5GMimXQLf6QLqV9s9ao10_Rn5KQs6bYEFtCJm_t9iWK_SbqsA
[   +1 ms] W/[Purchases] - WARN(10430): 🤖‼️ There's more than one sku in the PurchaseHistoryRecord, but only one will be used.
[   +1 ms] W/[Purchases] - WARN(10430): 🤖‼️ There's more than one sku in the PurchaseHistoryRecord, but only one will be used.
[   +5 ms] D/[Purchases] - DEBUG(10430): ℹ️ Requesting products from the store with identifiers: ci1yintroa
[  +72 ms] W/InputMethodManager(10430): startInputReason = 1
[  +20 ms] W/libEGL  (10430): EGLNativeWindowType 0x7150ba0010 disconnect failed
[  +15 ms] D/[Purchases] - DEBUG(10430): ℹ️ Products request finished for ci1yintroa
[        ] D/[Purchases] - DEBUG(10430): 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"ci1yintroa","type":"subs","price":"25,99 zł","price_amount_micros":25990000,"price_currency_code":"PLN","title":"camping.info 1 year - Intro Offer (Camping Info Test)","description":"Intro offer for the start of our new app. One year all functionality. ","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4Lrm89Xc6dQOY3J4fqEuA0GTzGD0Ia52nyUbNMYO_tXjQ8y18IuZdKWI4J58dDn"}
[        ] D/[Purchases] - DEBUG(10430): 💰 ci1yintroa - SkuDetails: {"productId":"ci1yintroa","type":"subs","price":"25,99 zł","price_amount_micros":25990000,"price_currency_code":"PLN","title":"camping.info 1 year - Intro Offer (Camping Info Test)","description":"Intro offer for the start of our new app. One year all functionality. ","subscriptionPeriod":"P1Y","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4Lrm89Xc6dQOY3J4fqEuA0GTzGD0Ia52nyUbNMYO_tXjQ8y18IuZdKWI4J58dDn"}
[        ] D/[Purchases] - DEBUG(10430): ℹ️ Found 0 unsynced attributes for App User ID: os:android:a2b95883982c4935
[  +21 ms] D/ActivityThread(10430): Remove activity client record, r= ActivityRecord{32c4185 token=android.os.BinderProxy@ac325cd {campingtest.info.app/com.android.billingclient.api.ProxyBillingActivity}} token= android.os.BinderProxy@ac325cd
[ +859 ms] D/[Purchases] - DEBUG(10430): ℹ️ API request started: POST /receipts
[   +2 ms] D/[Purchases] - DEBUG(10430): ℹ️ API request completed with status: POST /receipts 503`

version: purchases_flutter: ^3.4.0

**Comment by beylmk** [comment]
Hi @urbanMar, sorry you're seeing this error...The error message indicates that your Google Play package name in the Play Store configuration of your RevenueCat account might be incorrect. Can you please confirm whether the package is exactly the same as the package name published on the Play Store?

**Comment by urbanMar** [comment]
to close, there was misstype
