### ISSUE TITLE
Android Error on Purchase but no problem with fetching

### ISSUE THREAD

**Issue by burakcbdn** [RevenueCat/purchases-flutter#228]
**Describe the bug**
I cannot purchase item in Android. I can fetch products both in Android and IOS, but I can only purchase them in IOS, when I try to purchase something in Android I got following logs.

```
D/[Purchases] - DEBUG( 8762): ℹ️ Requesting products from the store with identifiers: one_time_export
D/[Purchases] - DEBUG( 8762): ℹ️ Products request finished for one_time_export
D/[Purchases] - DEBUG( 8762): 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"one_time_export","type":"inapp","price":"₺1,99","price_amount_micros":1990000,"price_currency_code":"TRY","title":"1 Rapor (GekApp)","description":"1 adet rapor dışa aktarma hakkı","name":"1 Rapor","skuDetailsToken":"AEuhp4KeEjsTy-FDWk6tUcOBQMdCXtyZ_OxkLt6R81fC46fQW76S5iDZy0lH6_K0hfBM"}
D/[Purchases] - DEBUG( 8762): 💰 one_time_export - SkuDetails: {"productId":"one_time_export","type":"inapp","price":"₺1,99","price_amount_micros":1990000,"price_currency_code":"TRY","title":"1 Rapor (GekApp)","description":"1 adet rapor dışa aktarma hakkı","name":"1 Rapor","skuDetailsToken":"AEuhp4KeEjsTy-FDWk6tUcOBQMdCXtyZ_OxkLt6R81fC46fQW76S5iDZy0lH6_K0hfBM"}
D/[Purchases] - DEBUG( 8762): 💰 Purchase started - product:  com.revenuecat.purchases.models.ProductDetails@574bd3ed null
D/[Purchases] - DEBUG( 8762): 💰 Purchasing product: one_time_export
W/BillingClient( 8762): Exception while launching billing flow: ; for sku: SkuDetails: {"productId":"one_time_export","type":"inapp","price":"₺1,99","price_amount_micros":1990000,"price_currency_code":"TRY","title":"1 Rapor (GekApp)","description":"1 adet rapor dışa aktarma hakkı","name":"1 Rapor","skuDetailsToken":"AEuhp4KeEjsTy-FDWk6tUcOBQMdCXtyZ_OxkLt6R81fC46fQW76S5iDZy0lH6_K0hfBM"}; try to reconnect
E/[Purchases] - ERROR( 8762): 🤖‼️ Failed to launch billing intent. DebugMessage: Service connection is disconnected.. ErrorCode: SERVICE_DISCONNECTED.
E/[Purchases] - ERROR( 8762): 🤖‼️ BillingWrapper purchases failed to update: DebugMessage: Service connection is disconnected.. ErrorCode: SERVICE_DISCONNECTED.null
E/[Purchases] - ERROR( 8762): 🤖‼️ There was a problem with the Play Store.
I/flutter ( 8762): PurchasesErrorCode.storeProblemError

```

Things I checked:
 - I configured google play connection to revenuecat (I clicked the button connect and it connected)
 - enabled pub/sub api
 - gave permissions to service accounts
 - waited for days maybe it needs to configure something

My debug logs are enabled:

```Dart
Future<void> initRevenueCat() async {
  await Purchases.setDebugLogsEnabled(true);
  await Purchases.setup("api-key");
}
```

@beylmk

**Comment by burakcbdn** [comment]
Any solution?

**Comment by beylmk** [comment]
HI @burakcbdn, thanks for opening the issue!

Can you please confirm:
* where you are calling `initRevenueCat()` from? 
* whether you are using the new `io.flutter.embedding.android.FlutterActivity`?
* whether the purchase dialog pops up?

**Comment by burakcbdn** [comment]
- I was calling ìnitRevenuCat()` from main function main function, I changed it to initState but nothing changed.
 - I am using new embedding and latest version of flutter, so yes I am using `io.flutter.embedding.android.FlutterActivity`
 - Purchase dialog is not pops up, as soon as I press purchase button from the app ui, it throws the error.
 - I am reffering to the button that on the revenuecat app settings page, below the json key. I clicked that and it connected. I tested notifications, too. I send test notification from google play console and revenuecat received it.
 
 I tried to reinstall whole google play configuration but nothing changed, I tried with different devices and users and still same.

**Comment by beylmk** [comment]
Thanks for the info...I'm going to confirm things are working with our sample app. Just to clarify, are your Play users also added to the internal test group in the Play console?

**Comment by burakcbdn** [comment]
Yes I added users to both License testing and internal testing.by the way I am using Android 11  if that makes difference.

**Comment by beylmk** [comment]
Thanks for confirming...I've confirmed our sample app is working as expected...

Could you try adding a try/catch to the purchaseProduct call? That might help us pinpoint the source of the problem.

Another thing which might help is if you try running our sample app on your phone. Then we can determine whether the issue has to do with your code vs your Play/RC setup.

The app is here: https://github.com/RevenueCat/purchases-flutter/tree/main/revenuecat_examples/MagicWeather. The plugin version would need to be updated to match your dependency.

**Comment by burakcbdn** [comment]
I already added try catch block this output is from print statement inside catch block.

I will try example app and return

**Comment by burakcbdn** [comment]
Hi, I tried the sample app but I could not get it to running. I am entering my api key, it sees products but cannot fetch them.
Another thing I did was, I tried original in_app_purchase package, and it even cannot fetch products. can problem might be about google play? But if it is about google play, How RC fetches product details

**Comment by beylmk** [comment]
@burakcbdn this sounds like a configuration issue. We reserve Github issues for bug reports, so I'm going to close this one out... but we've let the support team know about the discussion above, and they can help you through the Community ticket
