### ISSUE TITLE
Depracted Api error

### ISSUE THREAD

**Issue by jaybabani** [RevenueCat/purchases-flutter#231]
Hello,

Get this error while trying to run "flutter build appbundle"

C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\purchases_flutter-3.4.1\android\src\main\java\com\revenuecat\purchases_flutter\PurchasesFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Please check.

**Comment by aboedo** [comment]
hi @jaybabani!! Thanks for reporting! This is actually a duplicate of https://github.com/RevenueCat/purchases-flutter/issues/213, I'm closing this ticket out to keep the conversation in that one.

**Comment by bryantgtx** [comment]
The link to issue #213 is dead - is that conversation captured somewhere?
