### ISSUE TITLE
Android Error on Purchase but no problem with fetching

### ISSUE THREAD

**Issue by victoriousStudio** [RevenueCat/purchases-flutter#234]
This issue was reported 3 days ago also and I am getting the same issue ... my closed testing app is approved and so I was testing purchases in my debug build fine 4 days ago but now when I make purchase I get the item you are looking for is not found error but if I download my play store closed testing build I can successfully make the purchase.. Can you please help me its a urgent issue at my end .

**Comment by taquitos** [comment]
Hey @victoriousStudio, I know it's not super clear, but we're using our GitHub issues for reporting SDK-code specific problems/bugs/feature requests for the SDKs. To get the kind of help you're requesting is best if you head over to https://community.revenuecat.com/ where we have a dedicated team of folks to help! You can file support tickets there too, that will be the fastest way to get support.

Start here: https://community.revenuecat.com/about-the-community-60/should-i-post-here-or-contact-revenuecat-support-78
