### ISSUE TITLE
introductoryPrice is not accurate and any support for introductory length?

### ISSUE THREAD

**Issue by tamoyal** [RevenueCat/purchases-flutter#243]
It seems that `introductoryPrice` is always `null`, even when it should actually be `0`. I can see `null` making sense if there is no introductory price but if there is a price but it is `0`, I don't see how `null` makes sense. Also is there a way to get introductory offer details? ...like the length of the introductory price for a subscription?

**Comment by tamoyal** [comment]
The Flutter example on [this page](https://docs.revenuecat.com/docs/displaying-products) says we should be able to get the introductory period:
```
// Accessing the monthly product// Displaying the monthly product

try {
  Offerings offerings = await Purchases.getOfferings();
  if (offerings.current != null && offerings.current.monthly != null) {
    Product product = offerings.current.monthly.product;
    // Get the price and introductory period from the Product
  }
} on PlatformException catch (e) {
    // optional error handling
}
```

**Comment by vegaro** [comment]
Can you please provide which platform you are referring to? Android or iOS? 

`introductoryPrice` shouldn't always be null. If you are always getting null it means that user is not eligible for that introductory price or trial, or that there's no introductory price or trial at all. Maybe try creating a new tester user to make sure they would be eligible for the intro price. 

If there's a a trial with value of 0, `product.introductoryPrice` would not be `null`, and `product.introductoryPrice.price` would be `0`. 

You can access the subscription introductory price period via the `introPricePeriod` in the `IntroductoryPrice` [class](https://github.com/RevenueCat/purchases-flutter/blob/main/lib/product_wrapper.dart#L53).  So in that snippet of code you shared it would be something like:

```
 Product product = offerings.current.monthly.product;
 var introPricePeriod = product.introductoryPrice.introPricePeriod
```

I hope that helps

**Comment by tamoyal** [comment]
@vegaro Thanks for the response. This is for iOS. Since it's supposed to work, I deleted and re added the intro price in appstoreconnect and it worked ¯\_(ツ)_/¯

**Comment by vegaro** [comment]
Glad you got it to work. Not the first time I've heard something like that. The iOS sandbox environment is delicate...
