### ISSUE TITLE
Any plans to support ios subscription offers in the flutter sdk?

### ISSUE THREAD

**Issue by ericmartineau** [RevenueCat/purchases-flutter#25]
I read through the docs here: https://www.revenuecat.com/blog/signing-ios-subscription-offers but couldn't find the necessary calls in the flutter sdk. 

Do you guys have plans to implement this?

**Comment by aboedo** [comment]
Hi Eric! Thanks for writing in. We do have plans to include subscription offers in flutter, we will likely roll it out within the next month!

**Comment by nemoryoliver** [comment]
> Hi Eric! Thanks for writing in. We do have plans to include subscription offers in flutter, we will likely roll it out within the next month!

Any update on this?

**Comment by gabrielfgularte** [comment]
Waiting for an update too.

**Comment by leonardocustodio** [comment]
No updates on this yet? I have to use another package just to make this feature work. I would love to do everything through revenuecat package instead.

**Comment by vegaro** [comment]
I am working on this atm and also adding MacOS support @leonardocustodio Sorry for taking so long to make these changes

**Comment by leonardocustodio** [comment]
Nice, thank you very much for the great work.

**Comment by vegaro** [comment]
This will go out in 1.4.0 along with the MacOS support
