### ISSUE TITLE
Returning invalidCredentialsError error after trying to purchase

### ISSUE THREAD

**Issue by EdesonABizerril** [RevenueCat/purchases-flutter#252]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
I am unable to complete a purchase. I've already reviewed all the settings several times and I couldn't finish. The purchase is being registered in the Play Console, but RevenueCat returns the error: invalidCredentialsError, with the following message:

`PlatformException (PlatformException(11, There was a credentials issue. Check the underlying error for more details., {code: 11, message: There was a credentials issue. Check the underlying error for more details., readableErrorCode: InvalidCredentialsError, readable_error_code: InvalidCredentialsError, underlyingErrorMessage: Invalid Play Store credentials., userCancelled: false}, null))
`

I tried to make a subscription. Which setting is not correct? What should I do?

1. Environment
   1. Output of `flutter doctor`
```
 [✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)
```

   2. How widespread is the issue. Percentage of devices affected.
 1 device - debug mode

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

```
`D/[Purchases] - DEBUG(25118): ℹ️ BillingWrapper purchases updated: skus: [com.ivoltaic.inv_mod.monthly.test1], orderId: GPA.3301-8186-2910-14819, purchaseToken: kjdpbhcfhgigkhgjgbhgflic.AO-J1OxPYhMcTkZ5t55rjJ7YrWSsaEw_Gjq9.........ifoBnM4F3pO-jzBSw6QZhHeX556dC4nkFT7VCQ
W/[Purchases] - WARN(25118): 🤖‼️ There's more than one sku in the PurchaseHistoryRecord, but only one will be used.
W/[Purchases] - WARN(25118): 🤖‼️ There's more than one sku in the PurchaseHistoryRecord, but only one will be used.
D/[Purchases] - DEBUG(25118): ℹ️ Requesting products from the store with identifiers: com.ivoltaic.inv_mod.monthly.test1
I/Timeline(25118): Timeline: Activity_idle id: android.os.BinderProxy@9316037 time:92552449
D/[Purchases] - DEBUG(25118): ℹ️ Products request finished for com.ivoltaic.inv_mod.monthly.test1
D/[Purchases] - DEBUG(25118): 💰 Retrieved skuDetailsList: SkuDetails: {"productId":"com.ivoltaic.inv_mod.monthly.test1","type":"subs","title":"Módulos por Inversor - Mensal (iVoltaic - Energia Solar)","name":"Módulos por Inversor - Mensal","price":"R$ 13,00","price_amount_micros":13000000,"price_currency_code":"BRL","description":"Desbloquei todos os recursos com a assinatura mensal","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4IzXv5mOn..........KCx-G3uQ5YPo1croN5LLUVBDIgPp4QNZ92K_RImGbxy"}
D/[Purchases] - DEBUG(25118): 💰 com.ivoltaic.inv_mod.monthly.test1 - SkuDetails: {"productId":"com.ivoltaic.inv_mod.monthly.test1","type":"subs","title":"Módulos por Inversor - Mensal (iVoltaic - Energia Solar)","name":"Módulos por Inversor - Mensal","price":"R$ 13,00","price_amount_micros":13000000,"price_currency_code":"BRL","description":"Desbloquei todos os recursos com a assinatura mensal","subscriptionPeriod":"P1M","freeTrialPeriod":"P1W","skuDetailsToken":"AEuhp4IzXv5mOn........QYKCx-G3uQ5YPo1croN5LLUVBDIgPp4QNZ92K_RImGbxy"}
D/[Purchases] - DEBUG(25118): ℹ️ Found 0 unsynced attributes for App User ID: U9AX2f3cAsPPtzVWio7NonB5wQF2
D/[Purchases] - DEBUG(25118): ℹ️ API request started: POST /receipts
D/[Purchases] - DEBUG(25118): ℹ️ API request completed with status: POST /receipts 503
E/[Purchases] - ERROR(25118): 🤖‼️ There was a credentials issue. Check the underlying error for more details.`
```

3. Steps to reproduce, with a description of expected vs. actual behavior
- Trying to make a purchase
- Purchase to be made
- Return a failure

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
Please, check my settings.

**Additional context**
none

**Comment by aboedo** [comment]
hi @EdesonABizerril! 👋 
`invalidCredentialsError` happens when the API key is wrong, please make sure that you're passing in the correct value when calling `setup`

**Comment by EdesonABizerril** [comment]
Hi, it's not wrong. I took the API Keys -> Public SDK Key value and added it to Setup, as you said. I even installed RevenueCat in another app a while ago and it was pretty smooth. I don't understand why I can't now. What can I do?

In Get Start on the website home, option '5. Make a test purchase' is still unchecked.
The app icon is also not yet showing on the dashboard.

Unfortunately I'm about to give up on using RevenueCat in my app, because I've been trying for days and not having success. It's getting more costly than doing everything by hand. Help me!

**Comment by aboedo** [comment]
I had missed this bit in the logs: `Invalid Play Store credentials`, this means that there's something wrong with the Google Play configuration in the RevenueCat dashboard. 

Have you tried re-doing the steps outlined in our [Play Store Credentials setup guide](https://docs.revenuecat.com/docs/creating-play-service-credentials)?

If that's done correctly, and [products are set up correctly](https://docs.revenuecat.com/docs/android-products), then I think the next step would be to get you in touch with our [support team](mailto:support@revenuecat.com) directly, since they'll be better-equipped to figure out what's missing in the configuration.

Hope this helps!!

**Comment by EdesonABizerril** [comment]
Yes I saw this link. I will contact support. Thanks!

**Comment by esconts** [comment]
@EdesonABizerril Did you solve this issue?
