### ISSUE TITLE
iOS 15 - GetPurchaserInfo returns null

### ISSUE THREAD

**Issue by twigapp** [RevenueCat/purchases-flutter#253]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

Hi, Like many others, since upgrading one of my device to iOS 15, GetPurchaserInfo returns null. Rebooting the phone and running the app again will work but on renewal it will once again return null. All is well on iOS 14. Still using code from demo app https://github.com/RevenueCat/purchases-flutter/blob/master/example/lib/main.dart. Any idea of a fix.. ? Thanks !

 

✓] Flutter (Channel stable, 2.5.1, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)
 

Pubspec: purchases_flutter: ^3.4.5

Phone: iPhoneX (iOS 15.0)

**Comment by twigapp** [comment]
Aboedo, sorry for the late reply. iOS version is 15.0 (19A346). App still works ok on iOS 14.7 (18G69). I havent tried setting up new sandbox account as yet. I actually just saw another user mentioned it too. Will try and report back. Thanks.

**Comment by aboedo** [comment]
Sounds good! I hope the new sandbox user works. This is an odd one, for sure. I'm still trying to reproduce this on my side
