### ISSUE TITLE
MissingPluginException(No implementation found for method setupPurchases on channel purchases_flutter)

### ISSUE THREAD

**Issue by sondresorbye** [RevenueCat/purchases-flutter#256]
I have the latest version of purchases (purchases_flutter: ^3.4.5). I just updated to flutter 2.5.1 and got this runtime error: 

`MissingPluginException(No implementation found for method setupPurchases on channel purchases_flutter)`

This plugin used to work on previous versions of flutter.

**Comment by aboedo** [comment]
Hi! 👋 Thanks for reporting. 

I think this might be a caching issue. Have you tried the steps [outlined in this ticket from the flutter repo?](https://github.com/flutter/flutter/issues/10912)

**Comment by sondresorbye** [comment]
Yes, I have tried all tricks like flutter clean, pod install etc. The issue is only happening on iOS by the way. Runs fine on android

**Comment by aboedo** [comment]
🤔 not sure what might be going on there. I tried this on a sample app and had no issues. I also tried it on a brand new flutter app, and it still worked. 
Have you tried removing the plugin and adding it back? Other than that, it looks like `flutter run` is the specific command that would re-generate the relevant code. 
Does this also happen to you in a brand new app? I.e.: if you create a new flutter project, install the SDK and run on iOS, do you also get this error? If so, you could try re-installing flutter altogether.

**Comment by aboedo** [comment]
cool, let me know if you're still running into issues afterwards! Thanks for the quick followup!
