### ISSUE TITLE
getPurchaserInfo => managementURL IOS open with android

### ISSUE THREAD

**Issue by NicolasCELLA** [RevenueCat/purchases-flutter#258]
Hello, I have a problem when on an android, ```getPurchaserInfo => managementURL``` gives me an appStore link.

I can't open this link on navigator

Any ideas thank 😇

**Comment by vegaro** [comment]
Hi @NicolasCELLA thanks for opening! We would return the App store management URL if the active entitlement for that customer is coming from an Apple subscription. Is this maybe your case? Did you purchase a subscription for that app user ID from Apple before?

**Comment by NicolasCELLA** [comment]
Android: ```itms-apps://apps.apple.com/account/subscriptions```

**Comment by NicolasCELLA** [comment]
to get link:
```
   PurchaserInfo purchaserInfo = await Purchases.getPurchaserInfo();
    _purchaseUrl = purchaserInfo.managementURL;
    print(_purchaseUrl)
    ```

**Comment by vegaro** [comment]
I think we can do something to prevent "itms-apps:" links to be sent to Android devices since they don't do anything and improve the documentation on this function so its clearer what possible values the management URL can have. I have created an internal ticket for it.

**Comment by NicolasCELLA** [comment]
Great, thank you very much 👍
