### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by rodydavis** [RevenueCat/purchases-flutter#26]
I thought MacOS was supported? Can you show me documentation to get started? Works great on iOS and Android. Also is web support for Flutter web added?

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method setDebugLogsEnabled on channel purchases_flutter)
#0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:154
<asynchronous suspension>
#1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
#2      Purchases.setDebugLogsEnabled 
package:purchases_flutter/purchases_flutter.dart:243
#3      CartBloc.mapEventToState 
package:hymns_for_worship/…/cart/cart_bloc.dart:45
<asynchronous suspension>
#4      Bloc._bindStateSubject.<anonymous closure> 
package:bloc/src/bloc.dart:155
#5      Stream.asyncExpand.onListen.<anonymous closure>  (dart:async/stream.dart:576:30)
#6      _rootRunUnary  (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
#8      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
#9      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
#10     _DelayedData.perform  (dart:async/stream_impl.dart:594:14)
#11     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:710:11)
#12     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:670:7)
#13     _rootRun  (dart:async/zone.dart:1122:38)
#14     _CustomZone.run  (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
#17     _rootRun  (dart:async/zone.dart:1126:13)
#18     _CustomZone.run  (dart:async/zone.dart:1023:19)
#19     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
#21     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
#22     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
```

**Comment by vegaro** [comment]
Flutter web is not yet supported since our cross-platform SDKs don't support Stripe yet. I've realized there is a badge in pub.dev indicating support for `web`. I will remove it.

Regarding macOS support, we haven't tested yet, but as far as I am aware, it's not in the stable channel of Flutter yet, right? I just spend some time digging around macOS support and we need to make some changes on the plugin. 

I am going to leave this Issue open to track the macOS support

**Comment by rodydavis** [comment]
Macos is in alpha on the dev channel but not in stable I believe. If you need a tester for it please let me know.

And for web is there a way I can use this server to store purchases? For example not completing new ones just checking if a user purchased on iOS or Android. I know they would have to use the mobile app once before the web. Is there a database of users to access? Or is it all just api wrappers.

I haven’t found a good solution for web yet before building my own.

**Comment by vegaro** [comment]
Regarding for your web case, you could use our REST API https://docs.revenuecat.com/reference#basic. You would have to call this API from your own backend though, a Firebase Function for example, and send/get the data from RevenueCat from there to be consumed. Calling our REST API directly from Flutter won't work and will give you Cross-Origin requests blocked

**Comment by rodydavis** [comment]
When you have MacOS please let me know. I have a Flutter app ready to be released with it.

**Comment by JSANL** [comment]
Then please remove it from your Features list?!  "*macOS support*"
![image](https://user-images.githubusercontent.com/29028262/82453712-28a4cf80-9ab1-11ea-9d58-192a82d99ff5.png)

We now wasted our time trying to fix a problem that was not even caused by us... 🙄

**Comment by vegaro** [comment]
Sorry to waste your time @JSANL I will remove that now. We removed it from https://pub.dev/packages/purchases_flutter but not from the readme

**Comment by muhleder** [comment]
@vegaro You could also remove the stated web support from the Readme `know whether a user is subscribed whether they're on iOS, Android or web`

**Comment by vegaro** [comment]
Removing it here https://github.com/RevenueCat/purchases-flutter/pull/78.  Thanks for bringing that up @muhleder

**Comment by AndroidNils** [comment]
Are there any plans to support Flutter RevenueCat for macOS? RevenueCat for macOS should be working: https://docs.revenuecat.com/docs/macos

**Comment by vegaro** [comment]
It's in our backlog @AndroidNils

I will update here when we start working on it

**Comment by AndroidNils** [comment]
Great, @vegaro! So can we reopen this issue?
