### ISSUE TITLE
Getting: "Purchases instance already set" but not sure how?

### ISSUE THREAD

**Issue by tamoyal** [RevenueCat/purchases-flutter#261]
I'm currently getting this warning:

```
Getting: "Purchases instance already set" but not sure how?
```

There is no indication of how this issue can come about and I can't if it's actually going to cause problems or not.

I am on the latest version of the Flutter SDK

**Comment by aboedo** [comment]
hi! 👋 Thanks for reporting! 

This would happen as a result of calling `setup` more than once. This could lead to issues, yes. 
I'm going to make a note to improve the message to provide more details. 

In the meantime, though, try to make sure to call `setup` only once in your app's lifecycle, and within that, try to make it as early as possible (i.e.: right after launch). 

If you don't have the `appUserID` available at `setup` time, you can set it later by calling `logIn`. 

Hope this helps!

**Comment by friebetill** [comment]
I call the method `Purchases.setup` only once. But on each hot restart the information is printed that the Purchase Object is already configured. I guess it is because during the hot restart, the Purchase object is not reset. Is it possible to reset the Purchase object, like automatically all other variables, on a hot restart?

I use the latest version 3.5.0.

**Comment by aboedo** [comment]
Ohhhh, I see, that makes sense, I hadn't considered the hot reload. Perhaps that's what @tamoyal was running into as well? 

For hot reloads, you need to make sure that the setup method doesn't get called again when the widgets get reloaded. 
So you'd need to either move the setup line to somewhere where it doesn't get called on hot reload (I'm not familiar enough with Flutter to know whether that's possible), or you could try something like what's suggested here, [using a flag to determine whether the setup method has already been called](https://stackoverflow.com/a/67956127/5074358). 
Hope this helps!

**Comment by taquitos** [comment]
Heyo @friebetill, does that help? We're just going through our issues and making sure folks have their issues solved 😄

**Comment by friebetill** [comment]
Unfortunately not, the warning occurs (in my case) not with hot reloads, but with hot restarts. I did [some research](https://github.com/flutter/flutter/issues/29647), but did not find a solution to detect the hot restart. Therefore, I cannot prevent this with a flag. I think a hot restart does not correctly reset the setup process, although it should. But on the other hand, it's just a warning and doesn't occur in Production, so it's not so bad.
