### ISSUE TITLE
Why introductory price not applied while making purchase?

### ISSUE THREAD

**Issue by tijnar** [RevenueCat/purchases-flutter#265]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
When I do a test subscription to a package that has an introductory offer, the original price is shown to the google play subscription sheet, and no introductory offer is mentioned. And after the subscription is successful, the original price is shown in the billing email rather than the introductory offer.

Any suggestions to apply introductory offer while purchasing a product?

- Device used: Redmi Note 5 pro
- Flutter version: 2.2.3
-
Offering Output:
`Offering{identifier: annual, serverDescription: Annual Packages, availablePackages: [Package{identifier: standard, packageType: PackageType.custom, product: Product{identifier: subscription_annual_standard, description: Billed annually after 7-day free trial. Cancel anytime. , title: Standard (Zenmind), price: 66.12, priceString: $66.12, currencyCode: USD, introductoryPrice: IntroductoryPrice{introPrice: 0.0, introPriceString: US$0.00, introPricePeriod: P1W, introPricePeriodUnit: DAY, introPricePeriodNumberOfUnits: 7, introPriceCycles: 1}}, offeringIdentifier: annual}, Package{identifier: premium, packageType: PackageType.custom, product: Product{identifier: subscription_annual_premium, description: Billed annually after 7-day free trial.You can cancel anytime., title: Premium (Zenmind), price: 132.7, priceString: $132.70, currencyCode: USD, introductoryPrice: IntroductoryPrice{introPrice: 66.35, introPriceString: $66.35, introPricePeriod: P1Y, introPricePeriodUnit: YEAR, introPricePeriodNumberOfUnits: 1, introPriceCycles: 1}}, offeringIdentifier: annual}, Package{identifier: discounted, packageType: PackageType.custom, product: Product{identifier: discount_subscription_annual_premium, description: discounted annual premium, title: premium (Zenmind), price: 132.75, priceString: $132.75, currencyCode: USD, introductoryPrice: IntroductoryPrice{introPrice: 66.38, introPriceString: $66.38, introPricePeriod: P1Y, introPricePeriodUnit: YEAR, introPricePeriodNumberOfUnits: 1, introPriceCycles: 1}}, offeringIdentifier: annual}], lifetime: null, annual: null, sixMonth: null, threeMonth: null, twoMonth: null, monthly: null, weekly: null}`
```

1. Environment
   1. Output of `flutter doctor`
   2. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
Add any other context about the problem here.

**Comment by khacnha** [comment]
i think revenuecat should solve this problem.
before, when we integrate android/google directly, if the introduction price is not applied they will return null.

**Comment by beylmk** [comment]
Hey @khacnha, our team is considering how we can make this experience better for Android. We've created a ticket to work on this as soon as we can, and will report back here after.

**Comment by vitorhm** [comment]
Any update on this? We have 1 week trial on android and I need to check if the user is eligible for the offer.

**Comment by beylmk** [comment]
Hey @vitorhm 👋  we are working through our plan to upgrade to Google's new subscription model announced at Google I/O, and checking offer eligibility should be a part of that refactor. In the meantime, see the best response in this [Community answer](https://community.revenuecat.com/sdks-51/how-do-i-check-the-user-s-eligibility-for-intro-pricing-and-free-trials-on-android-163) for how to check yourself.
