### ISSUE TITLE
Error code: 23, message: There's a problem with your configuration.

### ISSUE THREAD

**Issue by kestasb** [RevenueCat/purchases-flutter#266]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**

We're using `purchases_flutter: ^3.4.6` in our app and receive the following crash reports from iOS users:

```
PlatformException(23, There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is being used). 
More information: https://rev.cat/why-are-offerings-empty, {code: 23, message: There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is being used). 
More information: https://rev.cat/why-are-offerings-empty, underlyingErrorMessage: , readable_error_code: CONFIGURATION_ERROR, readableErrorCode: CONFIGURATION_ERROR}, null)
```

**Additional context**

We haven't changed anything in RevenueCat configuration and it worked without this issue with `purchases_flutter: ^3.4.5`. Few days ago, we accepted the Paid apps agreement in App Store Connect, but the issue still persists to this day.
Unfortunately, we're not able to reproduce it on our test devices.

**Comment by friebetill** [comment]
I have the same problem and it has only appeared since I updated the package from 3.4.5 to 3.5.0. Also, I don't use Offerings and don't want to use them at the moment, so it makes sense that the Offerings are empty. But the error should not be displayed then.

**Comment by JazmineMT** [comment]
Hey @kestasb and @friebetill,

As of iOS SDK 3.12.6, we consider empty offerings to be an error so it’s expected (even if you aren’t using offerings, we automatically fetch them). Here is the GitHub release( https://github.com/RevenueCat/purchases-ios/releases/tag/3.12.6)

**Comment by friebetill** [comment]
Then probably this text should be adjusted accordingly in the webapp:
![image](https://user-images.githubusercontent.com/10923085/142619383-329ec7fc-c8f4-4c4a-9837-8bc6ebfba834.png)
Now that they are no longer optional.
