### ISSUE TITLE
I have some error message and I always get blank offering

### ISSUE THREAD

**Issue by dnaextrim** [RevenueCat/purchases-flutter#267]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
![image](https://user-images.githubusercontent.com/390712/139051174-e3e5909b-37a9-4f85-acda-9dc58204a16c.png)

**Additional context**

i always get blank offering

**Comment by codykerns** [comment]
@dnaextrim I'm going to go ahead and close this issue for now. If you're able to provide more information about the error you're encountering, and the community article above didn't help, please re-open and we can take another look.
