### ISSUE TITLE
Purchaser info cache does not invalidate after Google Play logout

### ISSUE THREAD

**Issue by kofan** [RevenueCat/purchases-flutter#277]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**

1. A user logs into Google Play Store, using the account on which an app subscription was purchased. 
2. The app retrieves information about the subscribed user and enables the premium feature.
3. The user goes to the device settings and logs out the Google account, so now the user is not logged in Play Store.
4. The method `Purchases.getOfferings()` starts throwing an error:
    ```
    PlatformException(3, The device or user is not allowed to make the purchase., {code: 3, message: The device or user is not allowed to make the purchase., readableErrorCode: PurchaseNotAllowedError, readable_error_code: PurchaseNotAllowedError, underlyingErrorMessage: Billing is not available in this device. DebugMessage: Google Play In-app Billing API version is less than 3. ErrorCode: BILLING_UNAVAILABLE.}, null)
    ```
5. However, the method `Purchases.getPurchaserInfo()` still returns the info about the user with a valid subscription.
6. On step 5, when we see the described error for the `Purchases.getOfferings()` method, I tried to call the method `Purchases.invalidatePurchaserInfoCache()`, but it didn't help the method `Purchases.getPurchaserInfo()` continues returning a user with a valid subscription.
7. The method `Purchases.logOut()` didn't work as well because we use fully anonymous users (no ID is bound) and the `Purchases.logOut()` method fails in this situation.

---

1. Environment
    1. Output of `flutter doctor`:
        ```
        [✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
        [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
        [✓] Xcode - develop for iOS and macOS
        [✓] Chrome - develop for the web
        [✓] Android Studio (version 2020.3)
        [✓] VS Code (version 1.62.3)
        [✓] Connected device (2 available)

        • No issues found!
        ```
    2. How widespread is the issue: all Android devices.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue: -
3. Steps to reproduce: see the description
4. **Other information**: -

**Additional context**

We use fully anonymous users in our app - no ID / e-mail / name is bound to a user.

**Comment by JazmineMT** [comment]
Hi @kofan, 

Sorry for the delay in the response here. The behavior you are seeing is expected when a user logs out of Google Play store our SDK will throw this error. This is because the user can't make a purchase unless logged into the Google Play store.

Additionally, although they are logged out of Google Play Store they are still a user in RevenuCat so we will retrieve their information when calling Purchases.getPurchaserInfo(). 

Is there a specific use case you are trying to account for?

**Comment by nickolay-kofanov** [comment]
I expected that after a user logs out of the Google Play Store, the method `getPurchaserInfo()` should NOT return an active subscription. Instead, it should return purchaser information that does NOT contain an active subscription...

**Comment by kofan** [comment]
I expected that after a user logs out of the Google Play Store, the method `getPurchaserInfo()` should NOT return an active subscription. Instead, it should return purchaser information that does NOT contain an active subscription...

**Comment by JazmineMT** [comment]
Hi @kofan, 

A Google Play Store account user is not the same as a RevenueCat user. We use the App User ID (the ID we use to identify users in our backend) that is on the device and pull information for that user. This information is coming from the receipt we have in our backend. Unless the receipt is updated to show an inactive/canceled subscription `getPurchaserInfo()` will still show an active subscription. 

The only time you would show a not active subscription is if you called `logOut() `or `logIn()` with an App User ID that doesn't have an active subscription. 

Does that make sense?
