### ISSUE TITLE
Failed to compile on android

### ISSUE THREAD

**Issue by davidgalarza** [RevenueCat/purchases-flutter#28]
Hi Revenuecat team, first of all thank you  this package. I'm able to run this packages in Flutter.

I was using the package revenuecat, and now I decided to start using the official library, but I'm having troubles to execute my app when I add to my dependencies 

`purchases_flutter: ^1.0.4`

I'm giving the following error:

`
e: /Users/macbook/development/flutter/.pub-cache/hosted/pub.dartlang.org/purchases_flutter-1.0.4/android/src/main/java/com/revenuecat/purchases/common/mappers.kt: (109, 60): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
@InlineOnly public inline operator fun BigDecimal.div(other: BigDecimal): BigDecimal defined in kotlin
@InlineOnly public inline operator fun BigInteger.div(other: BigInteger): BigInteger defined in kotlin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':purchases_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
`
Info:

My Kotlin version ext.kotlin_version = '1.3.60'

Flutter Doctor: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale
    es-EC)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category

**Comment by vegaro** [comment]
I've never seen this, but did you totally remove the unofficial `revenuecat` package? Could be due to an incorrect version of the BilingClient library being added to the project. If you open the Android project with Android Studio and go to the project view, can you check the versions that are being downloaded?

![Screen Shot 2020-03-25 at 4 45 46 PM](https://user-images.githubusercontent.com/664544/77596027-14c95c80-6eb8-11ea-8338-764872fadccc.png)

Thanks!

**Comment by davidgalarza** [comment]
Thanks for your answer.
Here is my version 
com.android.billingclient:billing:1.1

**Comment by vegaro** [comment]
It looks like for some reason an older incompatible version of the billingclient is being downloaded. What Flutter plugins do you have installed? There is a plugin downloading an older version of the billingclient 😄 

Thanks!

**Comment by davidgalarza** [comment]
Sorry was my bad.
For some reason I've implemented a resolution strategy   in my build.gradle         
resolutionStrategy.force "com.android.billingclient:billing:1.1"

removing it solved my issue.

**Comment by vegaro** [comment]
Glad you found the problem!

Let us know if you come across anything else

Have a good day 👏
