### ISSUE TITLE
purchasePackage does nothing and throw no exception

### ISSUE THREAD

**Issue by soham-mazumdar** [RevenueCat/purchases-flutter#283]
- [✓] I have updated Purchases SDK to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [✓] I have searched the [Community](https://community.revenuecat.com)
- [✓] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [✓] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. **Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

1. Environment
   1. Output of `flutter doctor`
   2. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

==================

pf.Purchases.purchasePackage(package) is not opening and neither showing any error or exception. it happens in testflight but not always... seems to a bit random. 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.3.1 20E241 darwin-x64, locale en-IN)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.0)
[✓] Connected device (1 available)

**Comment by beylmk** [comment]
Hi @soham-mazumdar, thanks for opening the issue. Could you try to reproduce with debug logs enabled, and send the logs? It'd be helpful to see where things get stuck. You can see how here: https://docs.revenuecat.com/docs/debugging
