### ISSUE TITLE
Adding the plugin breaks a working build from a vanilla flutter create app

### ISSUE THREAD

**Issue by arisAlexis** [RevenueCat/purchases-flutter#284]
I have updated Purchases SDK to the latest version
 I have read the Contribution Guidelines
 I have searched the Community
 I have read docs.revenuecat.com
 I have searched for existing Github issues

Describe the bug
Adding purchases-flutter into the pubspec.yam breaks a working build.

Environment
Platform: Android
SDK version: 30
OS version: Windows
Android Studio version: 2020.3.1
How widespread is the issue. Percentage of devices affected.
Debug logs that reproduce the issue
1: Task failed with an exception.
Where:
Build file 'C:\src\flutter.pub-cache\hosted\pub.dartlang.org\purchases_flutter-3.8.0\android\build.gradle' line: 25

What went wrong:
A problem occurred evaluating project ':purchases_flutter'.

java.lang.ExceptionInInitializerError (no error message)

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
2: Task failed with an exception.
Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 387

What went wrong:
A problem occurred configuring project ':purchases_flutter'.

Failed to notify project evaluation listener.
Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt
compileSdkVersion is not specified. Please add it to build.gradle

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1

Steps to reproduce, with a description of expected vs. actual behavior
add flutter plugin according to the docs in project that builds correctly and created by flutter create
Other information (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
Additional context

**Comment by vegaro** [comment]
Can you share the results of `flutter doctor`?

**Comment by arisAlexis** [comment]
@vegaro 

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (2 available)

**Comment by vegaro** [comment]
I just created a new Flutter project using Flutter 2.8.1. Then added the plugin via `flutter pub add purchases_flutter`. I opened the project with Android Studio and ran a `flutter pub get` and was able to successfully run the newly created app.

Maybe this is related. We are setting `compileSdkVersion 28`, do you have that version installed? You can see your installed Android SDKs in the SDK Manager in Android Studio:

<img width="753" alt="Screen Shot 2021-12-27 at 1 22 22 PM" src="https://user-images.githubusercontent.com/664544/147471439-6fa664de-21ff-4035-a5a3-fc5342157c8a.png">

**Comment by arisAlexis** [comment]
compiling for sdk 28 breaks other packages (file_picker, permission_handler) which need 29 or 30 to build. In any case 28 is very old to be a requirement for this package. Can you confirm it builds on 30 or produces an error for you too?

**Comment by vegaro** [comment]
@arisAlexis Sorry if I wasn't clear, I was suggesting if you could try installing the Android SDK 28, not if you could compile the app against SDK 28. I am not sure that could be the problem, but I am not sure what could be causing this. I haven't been able to reproduce it. I also tried setting `compileSdkVersion 30` in the `android/app/build.gradle` and also got it to compile.

If you want to sure a vanilla project that reproduces it in your machine, I am happy to try to build it in my machine.

**Comment by arisAlexis** [comment]
Confirmed my problem, something with build.gradle that was working ok but adding this package broke it. Fixed by getting a vanilla build.gradle.

**Comment by vegaro** [comment]
Do you have the diff between the vanilla and the older build.gradle? Just in case we need to add something to the docs

**Comment by arisAlexis** [comment]
buildscript {
    ext.kotlin_version = '1.2.71'
    >> ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        >> classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

 I think that was the problem. This was an older project I upgraded to the latest flutter.
Because of the above (root build.gradle)

this line failed in the app/build.gradle

apply plugin: 'kotlin-android'

my project used to compile without this line but since I changed those two and added this package it worked. Maybe only machine specific.
