### ISSUE TITLE
After Refunding non-consumable product getting error during Purchases.restoreTransactions()

### ISSUE THREAD

**Issue by premingiet** [RevenueCat/purchases-flutter#286]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**

On android, i tested with a test purchase of non-consumable product, then when i did refund that product from inside revenuecat dashboard, it said refund was success. Now when i press restoreTransactions button in my app, i get this error 
underlyingErrorMessage: Backend Code: 7651 - The payment for this non-subscription product is not complete.

For restoring transactions i am using this dart code
```dart
Future<void> restorePastPurchases() async{
    try {
      PurchaserInfo restoredInfo = await Purchases.restoreTransactions();
      print("***************  SUCCESS -> ${restoredInfo.entitlements.active["full_access"]}  ***************");
    } on PlatformException catch (e) {
      print("***************   ERROR -> $e ***************");
    }
  }
```

1. Environment

   1. Output of `flutter doctor`
   ```dart
    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 12.1 21C52 darwin-arm, locale en-IN)
    [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2020.3)
    [✓] VS Code (version 1.63.2)
    [✓] Connected device (2 available)
    
    • No issues found!
   ```

   2. How widespread is the issue. Percentage of devices affected.
   this happens in all android devices

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```flutter
D/[Purchases] - DEBUG( 9203): ℹ️ API request started: POST /receipts
D/[Purchases] - DEBUG( 9203): ℹ️ API request completed with status: POST /receipts 400
E/[Purchases] - ERROR( 9203): 😿‼️ There was an unknown backend error.
D/[Purchases] - DEBUG( 9203): 💰 Consuming purchase with token ghbkejonkocapllcncfnplhc.AO-J1OylaXxuEhGV0p3bDRovzJMjcW4VP5n0Lf9pKLGL3c80ByU-bwNEu2j7puSFM01VcfiNvRkyvjB8cblKiZguwRsUU1KzmLoPOSjSAO-cs6oKLyQVmD8
E/[Purchases] - ERROR( 9203): 😿‼️ Error restoring purchase: PurchaseDetails(orderId=null, skus=[lifetime_managed], type=INAPP, purchaseTime=1641221771691, purchaseToken=ghbkejonkocapllcncfnplhc.AO-J1OylaXxuEhGV0p3bDRovzJMjcW4VP5n0Lf9pKLGL3c80ByU-bwNEu2j7puSFM01VcfiNvRkyvjB8cblKiZguwRsUU1KzmLoPOSjSAO-cs6oKLyQVmD8, purchaseState=UNSPECIFIED_STATE, isAutoRenewing=null, signature=VJS9bmwf7aBVLtHKhbXFpH5yfu/dMUpuz0YwBQQOxJDdLbDHB7pY/cac/rz/7/HFJDguxBh9ZPWnLBrtkHSswDL7s6eRvKeUr78B866oBMrGpjnJrAOBZ0q/ugGHI+ieP+cKWhrgOBdh3idiQ2jWJIXOKz9c+tUfOCUoG3evcuOLSJSGgae9HlQfbKrHv1u2czcx3URKp/aenYTy7IWLpawcnC8C2vOFhZN54wXDAWy7jp6kA50aaRzVP+T1YHLREY4gy+L1CO6dRZkEuYO9dTkBUZJCx8z5bYONlZiRWtwzvkVvJtaJEGy20jCSJmWdwu3ZVt/FAGpAMTiLxuHrug==, originalJson={"productId":"lifetime_managed","purchaseToken":"ghbkejonkocapllcncfnplhc.AO-J1OylaXxuEhGV0p3bDRovzJMjcW4VP5n0Lf9pKLGL3c80ByU-bwNEu2j7puSFM01VcfiNvRkyvjB8cblKiZguwRsUU1KzmLoPOSjSAO-cs6oKLyQVmD8","purchaseTime":1641221771691,"quantity":1,"developerPayload":null}, presentedOfferingIdentifier=null, storeUserID=null, purchaseType=GOOGLE_RESTORED_PURCHASE). Error: PurchasesError(code=UnknownBackendError, underlyingErrorMessage=Backend Code: 7651 - The payment for this non-subscription product is not complete., message='There was an unknown backend error.')

```

3. Steps to reproduce, with a description of expected vs. actual behavior
- just buy a non-consumable product set up for android
- you will see purchase success message
- Now go to dashboard of revenuecat and enable ```viewing sandbox data```
- select the user and then in purchase history, choose the purchase for ```non-consumable``` product that just happened
- Now in Event details press ```Refund``` button
- Go back to android app and press the ```restore transactions``` button
- you will now see the error mentioned above and won't be able to fetch ```PurchaserInfo``` anymore
- Only way to fix it currently is to purchase any product again and no more error shows.
- Please tell me how to fix this issue

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
- https://community.revenuecat.com/sdks-51/error-when-purchasing-non-subscription-and-refunding-800

**Additional context**
```please check the above revenuecat community link where someone else mentioned the same issue and wasn't responded by anyone yet.```

**Comment by beylmk** [comment]
Hey @premingiet, thanks for opening this issue and providing all the logs. I'm reaching out to our team to get more info. In the meantime, could you please clarify this point?

>  won't be able to fetch PurchaserInfo anymore

What happens when you try to fetch PurchaserInfo?

**Comment by premingiet** [comment]
When i try to fetch PurchaserInfo after the refund/restore, it gives me that error log. Because its never successful. It goes to catch block and shows the platform error.

```dart
Future<void> restorePastPurchases() async{
    try {
      PurchaserInfo restoredInfo = await Purchases.restoreTransactions();
      print("***************  SUCCESS -> ${restoredInfo.entitlements.active["full_access"]}  ***************");
    } on PlatformException catch (e) {
      print("***************   ERROR -> $e ***************");
    }
  }
```

you see in the above method, after refunding a non-consumable product on android, when i try to restore past purchase, instead of finishing inside try block, it actually goes into error and finishes in catch block, that is to say, it ends up in showing platform exception.

**Comment by beylmk** [comment]
Ahhh, I see what you mean @premingiet, thanks.

The code is actually working as expected in this case, though I think there are some improvements we could make. Here's what's going on:
Unfortunately, Google will continue reporting the purchase in queryPurchaseHistoryAsync, so we don't have a way to know to NOT try to restore the purchase (There's an [open issue](https://issuetracker.google.com/issues/73982566) with Google about this.). Then, when trying to restore, it fails, because... it's been refunded. Google doesn't provide a very descriptive error, so we can't tell why the restore failed.

However, since functionality isn't technically broken, we probably shouldn't error here (and then you can still get a PurchaserInfo object returned).  I've created a ticket for us to improve this experience. In the meantime, you could call for a new PurchaserInfo object in the case that restore fails, and you should be able to get one. Let me know if that makes sense.

**Comment by premingiet** [comment]
ya i got your point. I will give that a go for now. Thanks for help

**Comment by beylmk** [comment]
@premingiet closing for now, but will post back here when we are able to prioritize updating our error logic. Thanks again for your feedback!
