### ISSUE TITLE
making android consumable products purchase not possible with revenue cat package?

### ISSUE THREAD

**Issue by abeyshiferaw0** [RevenueCat/purchases-flutter#287]
- [ ] I have updated Purchases SDK to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [ ] I have searched the [Community](https://community.revenuecat.com)
- [ ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
hi, i was trying to set up a consumable products based on Non-Subscription Purchases doc recommendations from revenue cat https://docs.revenuecat.com/docs/non-subscriptions.

but after calling purchaseProduct for a consumable product  i can't seem to purchase this product again because it was bought as a non-consumable and a an already bought error comes up

1. Environment
   1. Output of `flutter doctor`
   [✓] Flutter (Channel stable, 2.8.0, on macOS 11.5.2 20G95 darwin-x64, locale
    en-ET)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
E/[Purchases] - ERROR(13710): 🤖‼️ BillingWrapper purchases failed to update: DebugMessage: . ErrorCode: ITEM_ALREADY_OWNED.null
E/[Purchases] - ERROR(13710): 🤖‼️ This product is already active for the user.

3. **Other information** it would be great if the purchaseProduct() method could accept another parameter to specify if the product is consumable or non-consumable for android to make sure that the product is  consumed and can be bought again

**Comment by aboedo** [comment]
hi! 👋 

Are you setting `observerMode` to `true` or `finishTransactions` to `false`? Otherwise, the SDK should always consume the purchases and allow for another purchase to go through straight away. 

> it would be great if the purchaseProduct() method could accept another parameter to specify if the product is consumable or non-consumable for android to make sure that the product is consumed and can be bought again

This is very valid feedback, and we're thinking about ways to make that easier to work with.

**Comment by taquitos** [comment]
We're working on a way to make this better, no ETA, but let us know if you need anything else!
