### ISSUE TITLE
Need to find a new host for your binaries

### ISSUE THREAD

**Issue by kaseyrossanderson** [RevenueCat/purchases-flutter#288]
Hello,

The website that you use to host your binaries is shutting down. They are still allowing users to download up to version 3.6.0 from their website until Feb 1st, 2022.

Please see their wording below for this notice:

> Bintray services will no longer be available. JCenter will no longer be available for non-Artifactory clients. This means by the end of March 2021, publishing new packages to Bintray will no longer be allowed. Existing packages can still be downloaded until February 1st, 2022.

When you try to update your version in the pubspec to 3.8.0 for example it will cause the following errors in the app and will not be able to be built:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not resolve com.revenuecat.purchases:purchases-hybrid-common:1.11.1.
     Required by:
         project :app > project :purchases_flutter
      > Could not resolve com.revenuecat.purchases:purchases-hybrid-common:1.11.1.
         > Could not get resource 'https://jcenter.bintray.com/com/revenuecat/purchases/purchases-hybrid-common/1.11.1/purchases-hybrid-common-1.11.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/revenuecat/purchases/purchases-hybrid-common/1.11.1/purchases-hybrid-common-1.11.1.pom'. Received status code 502 from server: Bad Gateway
```

**Comment by kaseyrossanderson** [comment]
Just trying to provide some helpful info you dumb bot.

**Comment by joshdholtz** [comment]
@kaseyrossanderson Heyyy 👋 Thanks for reporting this! It looks like `jcenter` was removed 16 days ago in https://github.com/RevenueCat/purchases-flutter/pull/285 but is just not in the latest release yet

I'm going to close this issue but pin it so that anybody else that comes across this will know that its coming but we will get a release out soon 😊
