### ISSUE TITLE
Upgrade to new Android plugins APIs

### ISSUE THREAD

**Issue by vegaro** [RevenueCat/purchases-flutter#29]
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by atrope** [comment]
I Second that.
This is the only plugin that we use that is still with old APIs

**Comment by atrope** [comment]
@vegaro

**Comment by vegaro** [comment]
@atrope Thanks for the bump. We are going to be migrating the plugin to the new APIs in the following weeks. Just to make sure we are prioritizing this right, is this limiting you in any way?

**Comment by atrope** [comment]
Hi @vegaro ,
it is not limiting per se, but it is  limiting our upgrade to the recommended flutter way to set up android app.

and it is a fairly easy upgrade

Thanks for the prompt response!

**Comment by vegaro** [comment]
Thanks for clarifying. This is in our backlog, but we have a few other items in our plate, so there might be a bit of a wait. I will post here when get to work on this. We are accepting pull requests, if you need it to be released sooner.

**Comment by vegaro** [comment]
Release 1.2.0 will have this changes
