### ISSUE TITLE
purchases_flutter >=3.9.0 depends on freezed_annotation ^0.15.0

### ISSUE THREAD

**Issue by bwhiteTP** [RevenueCat/purchases-flutter#296]
- [ x] I have updated Purchases SDK to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x ] I have searched the [Community](https://community.revenuecat.com)
- [x ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
Upgrading purchases_flutter to 3.9.0 reports that it is dependent on outdated freezed_annotation package v0.15.0. The latest freezed_annotation package is 1.1.0.
`flutter pub get` output:
`Because purchases_flutter >=3.9.0 depends on freezed_annotation ^0.15.0 and my_project depends on freezed_annotation 1.1.0, purchases_flutter >=3.9.0 is forbidden.`

**Comment by NatsuOnFire** [comment]
Duplicated #292

**Comment by aboedo** [comment]
Update here: release 3.9.1 has been released with the dependency update! 🎉  Thanks so much for reporting! And special thanks to @NatsuOnFire for making a PR with the update!
