### ISSUE TITLE
Empty Offers Query

### ISSUE THREAD

**Issue by ericmartineau** [RevenueCat/purchases-flutter#30]
I'm having an issue with blank `Offers` coming back from the SDK.  I'm on the flutter `dev` channel working in iOS: 
```
Flutter 1.16.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision e6b0f5f238 (9 days ago) • 2020-03-18 21:56:02 -0400
Engine • revision 216c420a2c
Tools • Dart 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)
```

I noticed that the Pod for Purchases is at `3.2.1` and the flutter app is using the `3.0.x` releases.

**Comment by ericmartineau** [comment]
I ran the project in XCode and got this from didFailWithError during SKRequest: 

[1]	(null)	@"NSLocalizedFailureReason" : @"Attempted to decode store response"	
<img width="1681" alt="Screenshot 2020-03-27 15 45 43" src="https://user-images.githubusercontent.com/244358/77806475-0c049200-7042-11ea-9a89-d65f669167ef.png">

**Comment by aboedo** [comment]
Hi! This error can happen in a few scenarios, so to try to narrow it down:
- Make sure you're using a physical device
- Make sure that you have accepted the terms and have filled in all of the tax and legal requirements in App Store Connect, and that free and paid app agreements show as Active in the Agreements section
