### ISSUE TITLE
Purchases.purchasePackage(selectedPackage) throws an error

### ISSUE THREAD

**Issue by dmitry-kotorov** [RevenueCat/purchases-flutter#304]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
#0 Purchases.purchasePackage (package:purchases_flutter/purchases_flutter.dart:223)
throws an error:
type '_InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>'
 

<br class="Apple-interchange-newline">

1. Environment
   1. Output of `flutter doctor`
   [✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (4 available)

   2. How widespread is the issue. Percentage of devices affected.
   Issue appeared in production. It is hard to say yet how widespread as this version was rollout to 20% of our users and issue appeared few hours after release started.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
 - Make purchase of a subscription on Android device
 - Confirm payment
 - Issue appears when app calls   Purchases.purchasePackage(selectedPackage!);

3. Steps to reproduce, with a description of expected vs. actual behavior
 - Make purchase of a subscription on Android device
 - Confirm payment
 - Issue appears when app calls   Purchases.purchasePackage(selectedPackage!);
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by yarmel** [comment]
Seems that this bug was detected in new versions 3.9+
As a temporary solution just use version 3.8.0

**Comment by vegaro** [comment]
Hi! Sorry about that. We just pushed 3.9.2 that fixes the problem. The original bug report https://github.com/RevenueCat/purchases-flutter/issues/300 has more information.

**Comment by dmitry-kotorov** [comment]
Thanks! I did not notice that there was already a bug report about that(
