### ISSUE TITLE
[3.9.2] purchases_flutter ^3.9.2 is forbidden

### ISSUE THREAD

**Issue by devibrahimkarahan** [RevenueCat/purchases-flutter#307]
- [ + ] I have updated Purchases SDK to the latest version
- [ + ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [ + ] I have searched the [Community](https://community.revenuecat.com)
- [ + ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ + ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
When i use 3.9.1, its working. But when i use 3.9.2, pub get giving me error
"Because no versions of purchases_flutter match 3.9.2 and no versions of purchases_flutter match >3.9.2 <4.0.0, purchases_flutter ^3.9.2 is forbidden.
So, because my_package depends on purchases_flutter ^3.9.2, version solving failed.
pub get failed (1; So, because my_package depends on purchases_flutter ^3.9.2, version solving failed.)"

1. Environment
   1. Output of `flutter doctor`
   - ✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale tr)
     [✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.

   2. How widespread is the issue. Percentage of devices affected.
   - Build error
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
- "Because no versions of purchases_flutter match 3.9.2 and no versions of purchases_flutter match >3.9.2 <4.0.0, purchases_flutter ^3.9.2 is forbidden.
So, because my_package depends on purchases_flutter ^3.9.2, version solving failed.
pub get failed (1; So, because my_package depends on purchases_flutter ^3.9.2, version solving failed.)"
3. Steps to reproduce, with a description of expected vs. actual behavior
purchases_flutter: ^3.9.2
flutter pub get
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
Im trying to run project on real iphone device.
Its not an application, its a package. Because of that i cant do pod install

**Comment by beylmk** [comment]
Hey @devibrahimkarahan, sorry you're experiencing this...

Unfortunately, I'm not able to reproduce in our sample app... could you try deleting your pubspec.lock and pub caches folder by running `flutter pub cache clean` and retrying?

**Comment by devibrahimkarahan** [comment]
Yeah it worked, thanks
