### ISSUE TITLE
IntroductoryPrice is no longer exposed by default

### ISSUE THREAD

**Issue by mrgnhnt96** [RevenueCat/purchases-flutter#309]
**Describe the bug**

In a previous version of [purcahses_flutter](https://github.com/RevenueCat/purchases-flutter/releases/tag/3.8.0) the `IntroductoryPrice` class was located with the product_wrapper file. Since then, it as been moved into its own file. The object_wrapper barrel file hasn't been updated to include the new introductory_price file. 

The only way to use the IntroductoryPrice object is by importing the implementation file.

**Comment by beylmk** [comment]
@mrgnhnt96 i'm going to do a quick release with this fix, but the team is thinking through ways to automate/test this to prevent it from happening again.

**Comment by beylmk** [comment]
@mrgnhnt96 this should be fixed via [3.9.3](https://github.com/RevenueCat/purchases-flutter/releases/tag/3.9.3), closing for now! feel free to re-open if there are any more problems
