### ISSUE TITLE
Create APITester

### ISSUE THREAD

**Issue by beylmk** [RevenueCat/purchases-flutter#313]
Create a dart APITester similar to those in [purchases-ios](https://github.com/RevenueCat/purchases-ios/tree/main/APITesters) and [purchases-android](https://github.com/RevenueCat/purchases-android/tree/main/api-tester).

This is a minimal command-line app depending on purchases-flutter which calls each public API found in the Purchases library.  The app is not meant to run, only compile. Compiling the APITester (which, in a follow-up ticket, will be automated via CircleCI) will serve as a check for any unintentional changes to the public API.

[sc-12902]

**Comment by vegaro** [comment]
We have an api tester now https://github.com/RevenueCat/purchases-flutter/tree/main/api_tester
