### ISSUE TITLE
The whole app crashes after adding purchases-flutter

### ISSUE THREAD

**Issue by rocboronat** [RevenueCat/purchases-flutter#314]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
When trying the plugin for the first time, this happens:

```
java.lang.NoSuchMethodError: No virtual method getSku()Ljava/lang/String; in class Lcom/android/billingclient/api/Purchase; or its super classes (declaration of 'com.android.billingclient.api.Purchase' appears in /data/app/com.EAGINsoftware.dejaloYa-Pz68xtNm1m5q6uf_vZicBQ==/base.apk!classes2.dex)
```

We have native inapp purchases in our app. Now we want to add subscriptions with RevenueCat, but we want to maintain giving our PRO features to the people who bought the inapp purchases. Maybe having both RevenueCat and the regular `in_app_purchase` plugin could be a reason?

1. Environment
   1. Output of `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] Connected device (3 available)

• No issues found!
```

   2. How widespread is the issue. Percentage of devices affected.
We're still implementing the SDK

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

3. Steps to reproduce, with a description of expected vs. actual behavior
Just run the app and initialize the SDK

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
```
D/[Purchases] - DEBUG(31039): ℹ️ Starting connection for com.android.billingclient.api.BillingClientImpl@b9d320d
D/[Purchases] - DEBUG(31039): ℹ️ Billing Service Setup finished for com.android.billingclient.api.BillingClientImpl@b9d320d
D/[Purchases] - DEBUG(31039): ℹ️ Updating pending purchase queue
D/[Purchases] - DEBUG(31039): ℹ️ No cached Offerings, fetching from network
D/[Purchases] - DEBUG(31039): Same call already in progress, adding to callbacks map with key: /subscribers/%24RCAnonymousID%3A11ab146415894262b881ce25fa5fd21f/offerings
D/TransportRuntime.SQLiteEventStore(31039): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(31039): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-462670947 in 27089ms(Backend next call timestamp 1643896134435). Attempt 1
E/AndroidRuntime(31039): FATAL EXCEPTION: main
E/AndroidRuntime(31039): Process: com.EAGINsoftware.dejaloYa, PID: 31039
E/AndroidRuntime(31039): java.lang.NoSuchMethodError: No virtual method getSku()Ljava/lang/String; in class Lcom/android/billingclient/api/Purchase; or its super classes (declaration of 'com.android.billingclient.api.Purchase' appears in /data/app/com.EAGINsoftware.dejaloYa-Pz68xtNm1m5q6uf_vZicBQ==/base.apk!classes2.dex)
E/AndroidRuntime(31039): 	at io.flutter.plugins.inapppurchase.Translator.fromPurchase(Translator.java:64)
E/AndroidRuntime(31039): 	at io.flutter.plugins.inapppurchase.Translator.fromPurchasesList(Translator.java:97)
E/AndroidRuntime(31039): 	at io.flutter.plugins.inapppurchase.Translator.fromPurchasesResult(Translator.java:119)
E/AndroidRuntime(31039): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.queryPurchases(MethodCallHandlerImpl.java:296)
E/AndroidRuntime(31039): 	at io.flutter.plugins.inapppurchase.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:135)
E/AndroidRuntime(31039): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(31039): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/AndroidRuntime(31039): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/AndroidRuntime(31039): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/AndroidRuntime(31039): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(31039): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(31039): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(31039): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(31039): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31039): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(31039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by rocboronat** [comment]
![image](https://user-images.githubusercontent.com/456499/152356299-5540109b-e814-49e3-a502-4e92e76517cc.png)

It smells like this is the reason for everything. You and the official in-app purchase plugin are using different Android billing versions. Shame on `in_app_purchase` for not using the latest version, but what can we do now?

**Comment by vegaro** [comment]
You are right @rocboronat , `in_app_purchase` hasn't updated to Billing Client 3 yet 😮‍💨 

You're going to have to stick to version 3.3.1 of purchases_flutter since it's the last version that uses BillingClient 3

We should do the same we did in our Unity plugin in the VERSIONS file https://github.com/RevenueCat/purchases-unity/blob/main/VERSIONS.md . We added the BillingClient versions there and the compatibility with Unity IAP

**Comment by rocboronat** [comment]
Thanks for your answer, @vegaro!

Right now we have the Flutter's IAP plugin to keep giving the pro features to the users who bought them. Can I replace the Flutter's IAP plugin with yours, and continue giving those pro features to those old users? I mean, RevenueCat handles subcriptions, but what about the regular in-app purchases? If someone downloads the app, the RevenueCat SDK can say "this old user who never used RevenueCat since today bought the pro features two years ago"?

If the answer is yes, I could just get rid of the Flutter's IAP and that's it.

**Comment by aboedo** [comment]
@rocboronat you can import your existing data into RevenueCat, as long as you have access to it. Here's our [guide on the migration path](https://docs.revenuecat.com/docs/migrating-existing-subscriptions). Hope this helps!

**Comment by rocboronat** [comment]
We don't store anything about the purchases right now. What we do is just ask Google or Apple if that user has an IAP, send to our servers to validate it, and if it's ok, give the pro features to them.

I thought I could do the same with RevenueCat in case you support non-consumable in-app purchases, but I'm not sure you do. In the documentation you always talk about subscriptions, but I don't know if you consider the regular non-consumable IAPs just a lifetime subscription. May you clarify it?

Thanks a lot, @aboedo!

**Comment by vegaro** [comment]
We do support non-consumable iaps and non-consumable purchases appear in the PurchaserInfo. We use the PurchaserInfo class to hold all the purchase information of the customer. We abstract Apple's and Google's implementation so you just have to check the PurchaserInfo for the lifetime purchase. You can use Packages https://docs.revenuecat.com/docs/displaying-products#displaying-packages and configure this lifetime product as your lifetime package. We have a lot of apps that use non-consumable as a lifetime access to their premium features.

The only thing to clarify is that, with our current implementation, non-consumables in Android are actually being consumed. There's no really a type of product called "non-consumable" in Android. We keep track of the purchase in the PurchaserInfo class, so it doesn't matter it's consumed because it will always appear there and you can check for it in the PurchaserInfo. But one thing to be careful with is to not offer the lifetime product for purchase again.

I hope that clarifies a bit. I am going to close this issue to tidy up things a bit. Feel free to reach out to our support or to checkout our community in case you need more help setting up the non-consumable products with RevenueCat. You can find our help center [here](https://community.revenuecat.com).

**Comment by rocboronat** [comment]
Oh my god @vegaro, that's very, very bad news. Did you automatically consume all the lifetime purchases of our users? That means I'm bound to RevenueCat forever.

**Comment by codykerns** [comment]
Hey @rocboronat,

We're really sorry about the bad experience here. We know that this is a current limitation, and we're investigating ways that we could improve this experience (like configuring Google transactions as non-consumable) to avoid automatically consuming purchases like this. If you ever need to move off of RevenueCat, we'll be happy to help get you a list of users and purchases to help facilitate the process- you can reach out to RevenueCat Support at any time to help out.

We're also looking into ways of improving our documentation to try and make it more clear that this behavior occurs on Android. If you want to avoid purchases being consumed, you can also use Observer Mode which won't acknowledge or consume: https://docs.revenuecat.com/docs/observer-mode

**Comment by rocboronat** [comment]
Oooh honestly, it's the surprise what broke me. We gave your service account access to everything but we thought you were going not to write anything, just to see what happened behind the courtain.

If you can make a list of the purchasers, it's ok. But the most important thing is to explicitly warn of it to newcomers. Honestly, I would have agreed to it because you made easy to have reliable suscriptions, but knowing how it worked in this random issue made me feel like you hid something, and that's not fair.

But don't worry, you give a good service. Thanks for the support and the explanation 😊
