### ISSUE TITLE
TestFlight users resubscribe every restart

### ISSUE THREAD

**Issue by EliasDeuss** [RevenueCat/purchases-flutter#32]
For some reason if you use the subscription action in an app installed through TestFlight it resets the test subscription every time you force close the app. Subscriptions work though the App Store though.

**Comment by aboedo** [comment]
Hi! Could you elaborate on what it means for them to be reset every time the app is force-closed, and how much time passes between the subscription being purchased and expiring? 
Note that on TestFlight, subscription durations are dramatically reduced to make testing purchases easier (this is native iOS behavior). 

You can find more info on exact durations in our [subscriptions testing guide.](https://www.revenuecat.com/blog/the-ultimate-guide-to-subscription-testing-on-ios#sandbox)

**Comment by aboedo** [comment]
closing this ticket due to inactivity. @EliasDeuss feel free to reopen if you're still facing issues.
