### ISSUE TITLE
latestExpirationDate wrong in sandbox

### ISSUE THREAD

**Issue by ThangNguyen91** [RevenueCat/purchases-flutter#322]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**I tried payment on the sandbox account and result was returned `latestExpirationDate` was wrong.**

1. Environment
   1. Output of `Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 2.10.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (12 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2`
   2. All Device iOS
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior:

- Download App from Testflight
- Make purchase with method `purchaseProduct`
- Get Purchase Info with method `getPurchaserInfo`
- `latestExpirationDate` return is wrong as image :
![image](https://user-images.githubusercontent.com/28625589/153819790-0bc2b48c-2a55-46c1-86db-5f1615ca8b23.png)

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by ThangNguyen91** [comment]
If the user purchase both `do not register` and` register on the same product code, it will return the expiration date of `non-subscription`, right?

**Comment by aboedo** [comment]
@ThangNguyen91 Could you clarify a bit more? I'm not sure I understand the question

**Comment by ThangNguyen91** [comment]
For example, I have the alacarte product `product_one`.
After paying for the `product_one`, I keep paying for the `subscriptions`. Will `LatestExpirationDate` be expiration date of `subscriptions` or of the last bought a la carte (`product_one`), cause I'm seeing it returning the expiration date of `product_one`?

**Comment by aboedo** [comment]
I see. 
`LatestExpirationDate` represents the absolute max of expiration dates for all products. 
This in your case would mean that if you have a lifetime expiration date, but there's also a subscription, you'll get that `2221` date you saw before, which won't be very useful.


`LatestExpirationDate` is meant as a shorthand for apps where you can only have one thing active at a time, but if that's not your case, you can [use the `expirationDate` from `EntitlementInfo`](https://pub.dartlang.org/documentation/purchases_flutter/3.9.3/models_entitlement_info_wrapper/EntitlementInfo/expirationDate.html) to get the expiration date per specific entitlement. 

Hope this helps!

**Comment by ThangNguyen91** [comment]
Yes, thanks for support, I did as you and it worked.
