### ISSUE TITLE
Android: don't add an Activity on top of the Flutter's MainActivity

### ISSUE THREAD

**Issue by rocboronat** [RevenueCat/purchases-flutter#324]
Without checking the code, I see you are doing something strange before showing the native purchase dialog. The same when you close the dialog.

If you really need to show it, make it totally unperceivable. If I can see something strange happen, users will too.

**Comment by rocboronat** [comment]
This is how it looks on a Pixel 4a 👇 
https://user-images.githubusercontent.com/456499/154050477-84e626da-1886-4ebb-9dc8-f7e24dbcb138.mp4

See the app resizes when opening the purchase dialog, and a black bar crosses the screen from top to bottom when closing it 😿

**Comment by beylmk** [comment]
Hey @rocboronat, agreed that this experience is a little weird...RevenueCat doesn't have any control over this, unfortunately. Google's BillingClient (which we rely on to make purchases) creates a transparent activity when launching the billing flow (see related cordova [issue](https://github.com/RevenueCat/cordova-plugin-purchases/issues/11): ...you're not alone!)

As mentioned in that ticket, there is a [workaround](https://github.com/android/play-billing-samples/issues/135).

**Comment by beylmk** [comment]
Going to close for now, let me know how this goes!

**Comment by rocboronat** [comment]
Thanks for the link, @beylmk ! Do you have any open issue with the billing team of Google? Just to add a star there and maybe add a bit of weight on it.

**Comment by rocboronat** [comment]
I found a link: https://issuetracker.google.com/issues/153476408

Please, star it if you think it's important :·)

**Comment by beylmk** [comment]
Thanks for finding that @rocboronat ... starred!

**Comment by armandojimenez** [comment]
> Hey @rocboronat, agreed that this experience is a little weird...RevenueCat doesn't have any control over this, unfortunately. Google's BillingClient (which we rely on to make purchases) creates a transparent activity when launching the billing flow (see related cordova [issue](https://github.com/RevenueCat/cordova-plugin-purchases/issues/11): ...you're not alone!)
> 
> As mentioned in that ticket, there is a [workaround](https://github.com/android/play-billing-samples/issues/135).

I tried this workaround in flutter but in my manifest this class is not found: android:name="com.android.billingclient.api.ProxyBillingActivity"

any help how to implement this workaround in Flutter?
