### ISSUE TITLE
introductoryPrice returns null on Android even in production

### ISSUE THREAD

**Issue by jezsung** [RevenueCat/purchases-flutter#329]
`introductoryPrice` suddenly started to return null on Android. I have my subscription product set to 3-days free trial with no introductory price. But the free trial information was available in the `introductoryPrice` field but it seems it got broken. I have no ideas when this started to happen but my production app isn't working now. I didn't make any changes for quite a while.

**Comment by jezsung** [comment]
It seems it returns null for the only users who subscribed before and are not eligible for the free trial. But it doesn't on iOS. Why does it show different behaviors depending on the platform?

**Comment by aboedo** [comment]
@jezsung I'm sorry about the confusion, and thanks for opening! 

The reason that these are different is because we're bridging them over from their native counterparts, and Google and Apple manage this behavior differently. 

I.e.: Apple does provide an `introductoryPrice` even if the user isn't eligible for it. 

However, I do think that standardizing this falls within the scope of the things that RevenueCat should do, so I'm going to bring this up with the team.

**Comment by aboedo** [comment]
Looking at this again, I believe `introductoryPrice` does in fact still return a non-null value for Google even if the user isn't eligible. You can use the [approach described here to check for eligibility.](https://community.revenuecat.com/sdks-51/how-do-i-check-the-user-s-eligibility-for-intro-pricing-and-free-trials-on-android-163?postid=316#post316) 

@jezsung while testing this out I ran into some issues myself, due to some apparently very heavy caching on Google's side. On my main test device, after adding a free trial, the `introductoryPrice` wouldn't show up. I created a new emulator with Android Studio and the products loaded correctly on it. 

I wonder if this might be similar to what you're facing? Could you try setting up a new emulator with Play Store services, logging into a google account on it and checking the `introductoryPrice` again?

**Comment by jezsung** [comment]
This is how I fetch the `introductoryPrice`.

``` dart 
final Offerings offerings = await Purchases.getOfferings();
final Offering? current = offerings.current;

if (current == null) {
  return;
} else if (current.availablePackages.isEmpty) {
  return;
}

final Package? package = current.monthly;
if (package == null) {
  return;
}

// Prints null
print(package.product.introductoryPrice);
```

I haven't tested on emulators, I always tested on a real device and I'm not sure how it goes on emulators. `Product` is loaded correctly, but only the `introductoryPrice` field is null. Have you tested on real devices?  I'll try on emulators later.

**Comment by aboedo** [comment]
I was getting the null value on a real device, but then again, everything else was outdated for the same product - I tried updating the description in Google Play Console and it would still render the old value. 

On the brand new emulator it picked up the correct new values and non-null intro price

**Comment by jezsung** [comment]
@aboedo you mean you got a non-null `introductoryPrice` on a new emulator even after the free trial ends and becomes not eligible?

**Comment by jezsung** [comment]
@aboedo that's weird... I have no ideas what causes this but I looked up my production app crash reports and found out not many users are affected by this. So not eligible for the free trial was my initial guess but I really can't tell the exact problem.

**Comment by aboedo** [comment]
🤔 I wouldn't be entirely surprised if the sandbox environment was the only one with the issue, since sandbox is typically less reliable than production. 

But... you _are_ seeing users running into this in production? I.e.: getting `null` `introductoryPrice` for products that have a free trial?

**Comment by jezsung** [comment]
@aboedo  yeah, it happens in production as well. I think it has been around for a while. Unfortunately, my crash reports only give me the latest 3 months, and not sure when it started to happen.

**Comment by aboedo** [comment]
is this happening for one specific product? Or all of them? 
I'm asking because it's expected that non-subscription products will always have a null value for the field, and subscription products that don't have a free trial or introductory pricing will get nulls too

**Comment by jezsung** [comment]
@adoede It's happening to a subscription product which has a 3-day free trial. My app only has one subscription product and I don't know how's going for the other types of products.

**Comment by aboedo** [comment]
@jezsung is there any pattern that you can see with regards to locale? I'm wondering [if this conversion](https://github.com/RevenueCat/purchases-hybrid-common/blob/main/android/src/main/java/com/revenuecat/purchases/common/mappers/SkuDetailsMapper.kt#L23) might be causing issues

**Comment by jezsung** [comment]
@aboedo It doesn't show by the user's locale. But I got a null on my device with the production app and the language is set to US English and the region might be set to Canada.

**Comment by aboedo** [comment]
🤔 Just in case it's a Google thing, perhaps one approach would be to create a new product and use that one instead?

**Comment by jezsung** [comment]
@aboedo I just chose to handle a null value and not show the UI if it's null. I think it's okay as long as few users are affected by this

**Comment by aboedo** [comment]
@jezsung we've had more reports of this happening in production. It's an issue in the Billing Library itself, and it's currently being tracked here https://issuetracker.google.com/issues/219799769?pli=1

**Comment by jezsung** [comment]
@aboedo Thanks for letting me know. If it's a bug from the billing library then we might not need to do something on our side.

**Comment by rafaellop** [comment]
@jezsung It's not on the Google side or the billing library. In the 4.9.0 version of the plugin I get a correct introductoryPrice as defined in the Google Play for the subscription product, but in 5.x I always get `null`. The case is when a user already has purchased the item in the past, but I would like still have an option to get the information even if purchased in the past.

**Comment by nechtas** [comment]
> @jezsung It's not on the Google side or the billing library. In the 4.9.0 version of the plugin I get a correct introductoryPrice as defined in the Google Play for the subscription product, but in 5.x I always get `null`. The case is when a user already has purchased the item in the past, but I would like still have an option to get the information even if purchased in the past.

+1 for such experience. Tried every 5.x package and every time I received null for introductoryPrice. Any package 4.x and bellow works correct

**Comment by lukepighetti** [comment]
anyone know if this is still an issue? i have a local development android device that has never purchased a subscription and we cannot see any introductory offers (they are all null)

**Comment by padit69** [comment]
for version: 9.1.0 introductoryPrice returns null on Android even in production and sanbox
