### ISSUE TITLE
Subscription automatically switches if the user reinstalls the app and re-login to another account

### ISSUE THREAD

**Issue by thanhnhan111093** [RevenueCat/purchases-flutter#332]
- [x] purchases_flutter: ^3.9.5
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community] (https://community.revenuecat.com) 
https://community.revenuecat.com/sdks-51/subscription-automatically-switches-if-the-user-reinstalls-the-app-and-re-login-to-another-account-1295
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/) 
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**

**Flutter config**: await Purchases.setup(Config.revenueCatKey, appUserId: profileId);

The scenario on android sandbox

I log in and link user A and buy package A, Then I uninstall the app and reinstall then login user B, but the entitlement list returns the package A I bought earlier on User A. then I checked on RC's Customer page, I found package A has been transferred to account B. I don't think this is Restore Behavior

await Purchases.setup(Config.revenueCatKey, appUserId: profileId);

**Comment by joshdholtz** [comment]
@thanhnhan111093 Hello and thanks for reaching out!

This is the expected default behavior when restore purchases. Restore purchases will look at the on-device receipt and see that the Apple ID or Google Account purchased that subscription and then it will be transferred to that new user.

There are some other behaviors that can be set (see https://docs.revenuecat.com/docs/restoring-purchases) but they are a bit more dangerous and might require a higher level of manual support if the user (for some reason) loses access to their identified account.

**Comment by thanhnhan111093** [comment]
In this case, the user can log in to the wrong account and they can log back into the old account, the case of re-installing the app is easy to appear and they are very confused if we provide multiple login methods.

if we switch to Block Restores. do we have a way for users to force transfer when they click the "Restore Purchases" button?

**Comment by joshdholtz** [comment]
Hey @thanhnhan111093! 

I'm going to close these issues because the community posts are being escalated through a Zendesk ticket so you should have received some communication about that! Let me know if you haven't receive that communication and we'll figure out why.

Thanks!

**Comment by thanhnhan111093** [comment]
sorry, i didn't get any notification from zendesk

**Comment by aboedo** [comment]
@thanhnhan111093 we sent an email through ZenDesk on Monday at 11:45 PST, could you check your inbox for it? Perhaps it went to the spam folder?

**Comment by aboedo** [comment]
I'll send a follow-up just in case
