### ISSUE TITLE
Restore purchase has different results on android and ios

### ISSUE THREAD

**Issue by thanhnhan111093** [RevenueCat/purchases-flutter#334]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com) https://community.revenuecat.com/general-questions-7/unwanted-purchase-transfer-after-buy-new-subscription-1283
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/) 
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**
RC on Android
When I login user A account and link it to Revenue Cat. And Then Buy Package A. On the same phone, I logout account A then login account B and the buy Package B.
List of entitlement:
User  A -> Entitlement A
User  B -> Entitlement B

RC on iOS
When I login user A account and link it to Revenue Cat. And Then Buy Package A. On the same phone, I logout account A then login account B and the buy Package B,
List of entitlement:
User  A -> Entitlement is empty
User  B -> Entitlement has A & B

**Comment by joshdholtz** [comment]
Hey @thanhnhan111093! 

I'm going to close these issues because the community posts are being escalated through a Zendesk ticket so you should have received some communication about that! Let me know if you haven't receive that communication and we'll figure out why.

Thanks!
