### ISSUE TITLE
Expose `originalPurchaseDate` from `purchases-ios`

### ISSUE THREAD

**Issue by om-ha** [RevenueCat/purchases-flutter#34]
In reference to [this purchases-ios PR](https://github.com/RevenueCat/purchases-ios/pull/191), could `originalPurchaseDate` be exposed for flutter users please?

The currently exposed property `originalApplicationVersion` actually corresponds to the build number and not the version name. This is bad for migrating users since not all build numbers are unique for all versions. See the discussion in the PR linked above. All new developers of the project have to know this important optional constraint that is having distinct incremental build number regardless of version name.

This is impactful and wouldn't take much time to implement so I hope this gets you attention please.

**Comment by aboedo** [comment]
Hi! yeah, we'll include it for flutter as well. I'll keep this ticket open so we can track it. Thanks for bringing it to our attention!

**Comment by om-ha** [comment]
@aboedo many many thanks! really looking forward to this.

**Comment by aboedo** [comment]
closing this out since this has been integrated as a part of release 1.2.0
