### ISSUE TITLE
getOfferings does not work using the new Amazon branch

### ISSUE THREAD

**Issue by ac941** [RevenueCat/purchases-flutter#340]
- [x] I have updated Purchases SDK to the latest version

Yes, I am using version 4.0.0-amazon.alpha.4

- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)

Yes and there is a similar question but no one answered it: https://community.revenuecat.com/sdks-51/cannot-fetch-offerings-when-using-amazon-sdk-1155

- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

Running 

`await Purchases.getOfferings(); `

does not end. It just runs forever. The last output in the console is

`D/c       ( 2662): In App Purchasing SDK - Sandbox Mode: sendGetUserDataRequest`

Before calling it I have correctly setup the library using

`await Purchases.setup("amzn_xxxxxx", appUserId: null, observerMode: false, useAmazon: true);`

I have tested it on a real device, a Kindle Fire. targetSdkVersion is set to 31. Flutter version is 2.10.2.

I have read your documentation about empty getOfferings, but I could not find anything about getOfferings being stuck. I think it might be a bug.

**Comment by beylmk** [comment]
Hey @ac941 thanks for opening this and for providing all those details. Could you provide more info on how you're testing? Are you in Live App Testing or using the App Tester?

That last log comes from the Amazon IAP library, so it seems something is hanging on their side. If you haven't already, could you submit a debug build to Live App Testing, and send any logs you see there? That will provide the most realistic scenario.

**Comment by ac941** [comment]
I didn't know that I had to install the "[App Tester](https://developer.amazon.com/docs/in-app-purchasing/iap-app-tester-user-guide.html)" app to test it in Sandbox mode. I have installed it now, downloaded the json file with the IAPs and copied it into /mnt/sdcard . It seems to work now, thank you very much! 😊

**Comment by beylmk** [comment]
@ac941 wahooo, happy to hear it! I'll go ahead and close this ticket :)
