### ISSUE TITLE
Continue the purchase started on the App Store when the app is launched

### ISSUE THREAD

**Issue by rocboronat** [RevenueCat/purchases-flutter#341]
The user can start a purchase on the App Store, and it's expected from the app to show the purchase dialog as soon as the app is opened. I've looked for it in [the documentation](https://docs.revenuecat.com/docs/ios-app-extensions) but I can't find how to do it. 

Is it possible to do it?

It's requested by Apple to do it in case you want to promote an in-app purchase on the App Store, a thing that of course our competitors do :·(

A link to add a bit of context to this issue: https://developer.apple.com/app-store/promoting-in-app-purchases

> When a user starts an in-app purchase on the App Store, they are taken into your app to continue the transaction. Consider presenting the payment sheet as soon as they are in the app to make the process of completing their purchase as easy as possible. Avoid unnecessary interstitials and messaging, as each extra step you require may decrease the likelihood that the user will complete the purchase. If you are offering an auto-renewable subscription, you’ll need to explain how auto-renewal works in the purchase flow within your app.

**Comment by rocboronat** [comment]
Thank you so much @beylmk 😊

**Comment by beylmk** [comment]
Hey @rocboronat , we are so glad you brought this to our attention. We spent some time today understanding the flow (it's one of the more complex IAP flows I've seen 😅 ), and feel that we should make a couple minor updates to the underlying iOS function before we feel good about adding this to Flutter. We've made tickets for that as well and are hoping to tackle those in the next couple weeks.

I'll continue posting updates here! Thanks for your patience :)

**Comment by rocboronat** [comment]
Thank you @beylmk! I'm a bit concerned about it because in some weeks it could happen that we were featured as App Of The Day on the App Store, and we won't want to make Apple angry if this purchase flow doesn't work 🤒 Well, thank you so much, for sure it won't be easy but it'll be worth the price for sure 😃

**Comment by beylmk** [comment]
Hey @rocboronat, I understand, hope we can get this out to you ASAP! The iOS work has been started, so the Flutter work should be doable in the next few days to a week. I'll keep you posted here!

**Comment by rocboronat** [comment]
Thanks a lot! Super appreciated, @beylmk 😊

**Comment by beylmk** [comment]
Hey @rocboronat good news! The implementation is complete on Flutter :) I've got a [PR](https://github.com/RevenueCat/purchases-flutter/pull/345) out for a release...should be today or Monday.

**Comment by rocboronat** [comment]
Coooool! That's great news. Thanks for keeping me posted! 😊

**Comment by beylmk** [comment]
Hey @rocboronat, this is now released in [3.10.0](https://github.com/RevenueCat/purchases-flutter/releases/tag/3.10.0). We are still working on updating the docs on our site, but for now here's an example flow:

```
Purchases.addReadyForPromotedProductPurchaseListener(
        (productID, startPurchase) async {
      print('Received readyForPromotedProductPurchase event for '
          'productID: $productID');
	 // you can choose to cache the startPurchase block here if you'd like

      try {
        final purchaseResult = await startPurchase.call(); // this initiates the actual purchase flow
        print('Promoted purchase for productID '
            '${purchaseResult.productIdentifier} completed, or product was'
            'already purchased. purchaserInfo returned is:'
            ' ${purchaseResult.purchaserInfo}');
      } on PlatformException catch (e) {
        print('Error purchasing promoted product: ${e.message}');
      }
});
```

It's a confusing flow, but allows for flexibility on your end in determining whether you want to make the promoted purchase or not. We also have a function to remove the listener for cleanup, depending on where you set it.

Here are the docs for the existing iOS method (`purchases:shouldPurchasePromoProduct`), with a little more detail: https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/testing_promoted_in-app_purchases

And some docs on how to test: https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/testing_promoted_in-app_purchases

Let me know if you have any feedback or questions!

**Comment by armandojimenez** [comment]
Thank you so much for adding this!

**Comment by armandojimenez** [comment]
Testing this, is only working for me when the app is already open when receiving the intent. Is this how it's supposed to work?

**Comment by rocboronat** [comment]
Hello! We didn't have the chance to test it (we're working on the Apple Watch this week) but nope, that's not how that's supposed to work. Well, that case should be handled too, but the idea is that having the app dead, tapping the buy button on the App Store should launch the app and then, inside the app, continue with the purchase flow, also if the app was just cold-started.

**Comment by armandojimenez** [comment]
Got it, well then it does not work with a cold started app, let me know when you have a change to test it

**Comment by stepanov-standy** [comment]
@rocboronat @armandojimenez were you able to finally check a scenario with the app that hasn't been opened before start of the purchase from App Store? If it doesn't work, we have to ask @beylmk to check this from their side, because it is the main scenario for such functionality.

**Comment by rocboronat** [comment]
Hello! Yap, we released your solution to the App Store and it works as you said, but that's not how it's supposed to work.

Here's a video that reproduces the issue: the first time the purchase dialog doesn't appear, while the second time does. You can check it by yourself by looking for QuitNow on the App Store.

https://user-images.githubusercontent.com/456499/172580678-6340ec81-86cb-420b-8cf8-e67475268139.MP4

**Comment by beylmk** [comment]
Hey @rocboronat @stepanov-standy @armandojimenez thanks for your comments and explaining the issue, and sorry it's not working as expected :( I'll investigate today.

**Comment by rocboronat** [comment]
Thank you @beylmk 😊 I think the Flutter SDK should persist the configuration in the platform side, so it doesn't depend on the Flutter side. Then, as soon as the iOS app starts it can do stuff with the deeplink from the App Store, also if the Flutter engine is not ready yet.

**Comment by beylmk** [comment]
Hey @rocboronat I tried testing with QuitNow, thanks for sharing... I actually do see the popup on a cold start, though it takes a really long time to appear. Can you confirm if this happens for you too? 

When I test locally, it's not quite as slow...let me confirm whether the behavior is the same for a native iOS app, in case this is an AppStore thing...

**Comment by rocboronat** [comment]
Hi again 👋 I've just tried it and nope, the dialog never appears if it was a cold start... 😐

May you try with other devices? Maybe it's a OS version thing?

**Comment by armandojimenez** [comment]
For me it does not appear with a cold start, it appears only if the app is already opened

**Comment by beylmk** [comment]
> Hi again 👋 I've just tried it and nope, the dialog never appears if it was a cold start... 😐
> 
> May you try with other devices? Maybe it's a OS version thing?

sure, what OS are you on?

**Comment by rocboronat** [comment]
It's iOS 15.5

**Comment by beylmk** [comment]
@armandojimenez @stepanov-standy can you confirm which OS version you're seeing this issue on?

**Comment by beylmk** [comment]
I've been working on reproducing this with a coworker. We are _sometimes_ able to see the payment sheet on 15.5, sometimes not. Comparing device logs between the scenarios, there seems to be a difference between the products loaded from the AppStore. Can you confirm that the AppStore IAPs match exactly with those in the RC dashboard?

The behavior is just as spotty on a native iOS app on 15.5, and when it does work, the sheet still pops up pretty slowly... I'm going to continue looking into this...

**Comment by rocboronat** [comment]
> Can you confirm that the AppStore IAPs match exactly with those in the RC dashboard?

Yes, the IAP on the App Store matches exactly the one in RevenueCat. If not, I guess it would never work, right? I mean, right now it works if the app has been previously open. If it wouldn't match, they would never work.

By the way, when you say that it pops up pretty slowly, do you mean seconds or minutes?

Thanks for the effort! If I can do anything from this side to help you debug the issue, don't hesitate to ask.

**Comment by beylmk** [comment]
Oh, I meant ALL of the IAPs. I see something strange in device logs when the sheet fails to pop up, where it queries the AppStore for an extra product. It might be unrelated, but that's the only difference I see in the logs (besides a single `[SKIAP:P:L/com.eaginsoftware.QuitNow/2FE3A5C8] Payment sheet has presented` log) between the success and failure scenario. I don't know why this would affect things, but thought it was worth ruling out.. 

By slowly, I mean ~10 seconds. Long enough that I'd be confused/annoyed as a user... 

Will keep digging and let you know, thanks for offering to help with debugging!

**Comment by rocboronat** [comment]
Yep, then yes, we had an IAP that didn't exist on the App Store. I just deleted it, and the related offering. It was an experiment we did on Android and left everything ready on iOS, but as it didn't perform better than the offering we had right now, we left it just unattended. Now all the IAPs exist on the App Store and the log should be clean :·)

**Comment by beylmk** [comment]
Hey @rocboronat I'm a little stuck on this one. I've tested promoted purchases for QuitNow and other apps in the store, and it seems the behavior is unexpected across the board...sometimes the payment sheet simply fails to present, and almost always, it's quite slow. I'm filing a bug report with Apple today describing my findings.

I _do_ see it working for QuitNow most of the time, though it is slow...it takes anywhere from ~3-10 whole seconds to launch the payment sheet. It's slow for other apps too. I can't seem to find a pattern for when it simply doesn't pop up at all-- since that's happening for you consistently, could you describe the exact scenario? i.e. how long since you've launched the app, whether it's installed before clicking the promoted purchase, etc? 

I've seen some apps that display a screen with a loading indicator while waiting for the payment sheet, which feels like a slightly smoother UX. This is something you could consider while we wait for a response from Apple... for our library, that'd mean displaying some kind of loading indicator between receiving the delegate event and calling the `startPurchase` block. Though I suppose we'd want to figure out how to detect a "payment sheet failing to pop up" scenario, so you're not loading forever...

Anyways, that's just my brain dump. I'm going to open that bug report with Apple and will also continue trying different scenarios/capturing logs to hopefully find a pattern we can work with. Let me know if you're able to see any patterns on your end.

**Comment by rocboronat** [comment]
Ok! Thank you so much. About that loading page as you said I'm afraid of an infinite loading...

One question. Does the RevenueCat SDK have to be initialized and have loaded anything before calling the method that shows the dialog? Maybe that's the issue and we're having a race condition here and that's it?

**Comment by beylmk** [comment]
@rocboronat i don't think so 🤔, because I see the `shouldAddStorePayment` delegate method getting called immediately, which means our library is all initialized. And also I'm seeing the delay on non-RevenueCat apps in the store.

At this point, I'm unfortunately not sure there's much we can do to speed it up. I'm just hoping that we can find patterns to let Apple know and so that you can at least have more information about what's going on.

But I'll also kick this to the rest of my team in case they have more ideas...

**Comment by rocboronat** [comment]
Oh, I understand you're looking to fix the delayed purchase dialog, but what about when the purchase doesn't appear at all? Is the RevenueCat SDK totally initialized too? Sorry for asking for this clarification, but I'm afraid the issue is in our implementation and I want to be 100% sure we can do nothing to fix the issue 😊😊 Thanks!

**Comment by beylmk** [comment]
@rocboronat I'm happy to look at your initialization code to ensure nothing seems off! 

I'm having a lot of trouble reproducing the scenario when the dialog doesn't show at all, so I haven't been able to check logs for that case. That's where I could use your help understanding what you might be doing differently for that to happen.

**Comment by aboedo** [comment]
@rocboronat for the case where it doesn't show up at all, I think you might be right in that we're getting there _late_. 
I.e.: maybe StoreKit's queue is sending the `shouldAddStorePayment` call before either the SDK initialized or the listener is fully set up. 
Maddie already took a look that the first case, so maybe we should check the second one?

I.e.: could there be a case where by the time that you're calling `Purchases.addReadyForPromotedProductPurchaseListener`, the listener already went through? 
Could you share a snippet that shows how/when you're initializing the SDK and also how/when you're setting up this listener? Maybe it'll shed some light into what's going on here

**Comment by rocboronat** [comment]
Hi team! Here's our initialization code. Hope it helps!

```dart
Future<void> initRevenueCat() async {
    if (await Purchases.isConfigured) return;

    if (kDebugMode) {
      await Purchases.setDebugLogsEnabled(true);
    }

    if (Platform.isAndroid) {
      await Purchases.setup("the Android key");
    } else if (Platform.isIOS) {
      await Purchases.setup("the iOS key");
    }

    updateUserAttributes(); // to have the RevenueCat users database updated

    fetchOfferingsAndProducts(); // to have the SKUs and prices cached in memory
    restorePurchases(); // to automatically move the users to PRO if they just installed the app

    Purchases.addPurchaserInfoUpdateListener((purchaserInfo) {
      SubscriptionsDatabase.instance.savePurchaserInfo(purchaserInfo); // To update if the user is PRO or not when the SDK notifies a change
    });

    //An almost copy paste of @beylmk example implementation
    Purchases.addReadyForPromotedProductPurchaseListener((productID, startPurchase) async {
      //More info about this implementation in https://github.com/RevenueCat/purchases-flutter/issues/341
      print('Received readyForPromotedProductPurchase event for productID: $productID');
      try {
        final purchaseResult = await startPurchase.call();
        SubscriptionsDatabase.instance.savePurchaserInfo(purchaseResult.purchaserInfo);

        print(
            'Promoted purchase for productID ${purchaseResult.productIdentifier} completed, or product was already purchased. purchaserInfo returned is: ${purchaseResult.purchaserInfo}');
      } on PlatformException catch (e) {
        print('Error purchasing promoted product: ${e.message}');
      }
    });
  }
```

In case you would like to see it live, say hi to roc@fewlaps.com and say when :·)

**Comment by aboedo** [comment]
@rocboronat thanks for getting back to me! 

The code snippet makes sense. The only thing I can think of is that since there are a few things happening before the listener gets set, maybe the first call to the listener is getting lost. 

I would recommend moving the `Purchases.addReadyForPromotedProductPurchaseListener` block all the way up right after the `setDebugLogsEnabled` line, so the listener is ready to go by the time the SDK is set up.

If that doesn't work, let me know and I'll send you an email to set up a debug session!

**Comment by rocboronat** [comment]
Cool, I'll do it and update the app on the App Store 😊

**Comment by vegaro** [comment]
Hi @rocboronat any updates on this?

**Comment by rocboronat** [comment]
Not yet, we didn't have the chance to update the iOS app yet 😥

**Comment by rocboronat** [comment]
But now I had! The version already available on the App Store has the suggestion you said. The listener is set before anything else.

**Comment by rocboronat** [comment]
Hi team! Good news. It seems the last version of the app works as expected. It takes some time to show the dialog, but it eventually shows it, always. Well, at least on my tests 😆 If you want to try it, just look for QuitNow on the App Store and install it via the promoted in-app purchase button directly instead of with the install one.

So I want to say... thank you so much for the support!!!! 💰🎉🌮🦖

**Comment by rocboronat** [comment]
Team, a year passed and I think this is working as expected. If it stops working or anything, I will try to reopen this issue or link it in a new issue and that will be it. Thanks for the support!
