### ISSUE TITLE
Documentation for the Amazon variant seems to be missing the Proguard rules

### ISSUE THREAD

**Issue by ac941** [RevenueCat/purchases-flutter#342]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)

A similar Proguard configuration seems to be necessary for the Android version of the RevenueCat library.

- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

Using the purchase functions for Amazon IAPs on a Kindle Fire seems to work fine now in debug mode. However when running the release version, an error occurs:

```
2022-03-31 14:55:04.975 13498-13529/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method setupPurchases on channel purchases_flutter)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175)
    <asynchronous suspension>
    #1      Purchases.setup (package:purchases_flutter/purchases_flutter.dart:48)
    <asynchronous suspension>
```

To fix it it seems to be necessary to add the line

`-keep class com.revenuecat.** { *; }`

to the proguard-rules.pro file. Writing `-keep class com.revenuecat.purchases_flutter.** { *; }` is not sufficient.

And then the file has to be used in the build.gradle file:

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

Afterward it seems to work fine even in release mode. Maybe you should add this to your documentation. :-)

**Comment by vegaro** [comment]
Thanks for opening @ac941 

We recently made a new release https://github.com/RevenueCat/purchases-flutter/releases/tag/4.0.0-amazon.alpha.3  that should have included these automatically for you. Are you using that version?

**Comment by ac941** [comment]
I am using version 4.0.0-amazon.alpha.4. However the proguard file in that version contains only these lines:

```
-dontwarn com.amazon.**
-keep class com.amazon.** {*;}
-keepattributes *Annotation*
```

It is missing the line

```
-keep class com.revenuecat.** { *; }
```

which seems to be necessary to make it work. If I run the app in release mode without this line, then it doesn't work, i.e. the error mentioned above appears. However with this line (to make it easier I added it in my main project to a proguard file that contains only this line) it works fine.

Can you reproduce the problem?

**Comment by vegaro** [comment]
You are right, sorry about that. We merged a PR in the android dependency that fixes that, but it's not part of the version you are using. This is the PR https://github.com/RevenueCat/purchases-android/pull/416

Do you mind adding that line to your project Proguard configuration? We are going to release a major of purchases-flutter very soon and this problem will be fixed automatically with the new version. We mention this Proguard configuration in our android docs https://docs.revenuecat.com/docs/android#configure-proguard . I will add it to the Flutter docs while we get those updates in.

**Comment by ac941** [comment]
Hi,

yes, I can certainly add it to my project Proguard configuration, no problem. I just wanted to tell you so that you can fix it for future users. RevenueCat is really great and makes integrating subscriptions easy and I just wanted to help making the library easier to use. 😊

**Comment by beylmk** [comment]
Hey @ac941 thanks for bringing to our attention, we always appreciate customers calling out issues :) I'm going to close this ticket since the fix has shipped, but feel free to re-open if needed!
