### ISSUE TITLE
No way to access Package description?

### ISSUE THREAD

**Issue by magnus-lpa** [RevenueCat/purchases-flutter#35]
A description can be set for a Package in the RevenueCat dashboard, but I can't find any way to access it using version 1.1.0 of the Flutter plugin?

**Comment by alfonsoperez** [comment]
Hi @magnus-lpa!,
Sorry for the confusion here, the [package description](https://docs.revenuecat.com/docs/entitlements#section-4-configure-offerings) was initially meant for organizational purposes within our dashboard, but I see we return it for our `offerings`, so it might have been an oversight at our end.

Will leave this issue open until we have more info about when we can get to this

**Comment by khamasaki** [comment]
I would also find this useful. Thanks!

**Comment by rkotzy** [comment]
Going to go ahead and close this out since we have it logged as a feature request internally and isn't a Flutter specific issue exactly.

**Comment by romrell4** [comment]
@rkotzy do you have a link to the internal feature request so that we can follow the status?
