### ISSUE TITLE
Documentation link in read me is broken

### ISSUE THREAD

**Issue by esDotDev** [RevenueCat/purchases-flutter#352]
The url https://docs.revenuecat.com/v3.4/docs/flutter#amazon-appstore is giving me a 404 error

**Comment by codykerns** [comment]
Hey @esDotDev! We're pushing a quick fix, thanks for the heads up. The correct URL is: https://docs.revenuecat.com/docs/flutter#amazon-appstore

**Comment by esDotDev** [comment]
ty!
