### ISSUE TITLE
IOS 13.4 Update After - Flutter

### ISSUE THREAD

**Issue by bilaloz** [RevenueCat/purchases-flutter#36]
Hello Dear.

Payment does not start after updating.
Sometimes it starts but not as a sandbox user. process is canceled when i enter my password
The mistake I usually get is this PurchasesErrorCode.storeProblemError.
All of this happened after upgrading to 13.4.

**Comment by vegaro** [comment]
Hi @bilaloz 

Something happened in 13.4 that some users have to create a new sandbox user in order to be able to purchase. On top of that, there is an ongoing partial outage of sandbox https://status.revenuecat.com/ that will also throw errors when gettting products or purchasing. 

If you want to read more about this same issue, https://github.com/RevenueCat/cordova-plugin-purchases/issues/33

I hope that helps

**Comment by bilaloz** [comment]
Hi @vegaro 
I examined https://github.com/RevenueCat/cordova-plugin-purchases/issues/33 but,
my problem continues.
I created a new sandbox account.
Payment does not start after updating.
Sometimes it starts but not as a sandbox user. process is canceled when i enter my password
The mistake I usually get is this PurchasesErrorCode.storeProblemError.
All of this happened after upgrading to 13.4.
There is no problem in android.

Thank you.

**Comment by aboedo** [comment]
we haven't seen the issue where payments start as production users for a while, but maybe it's back. 
Have you tried signing out of the regular app store account on the device, so that you're only signed in to the sandbox account?

**Comment by bilaloz** [comment]
Thank you answer @aboedo .  I tried to . I sign out app store account (testflight,apple store) after . I created new apple account , I added as a testflight developer then I tried to sign in new account (settings,appstore,testfligt) then I tried to be subscripe to the my app . Result: Successful. but you should improve your response times because I can't say exactly fast. some times 5 sn come response. Beautiful library.

**Comment by aboedo** [comment]
I'm curious about that response time - was that while following the purchase prompts from iOS, or when getting purchaser info? 

Part of the flow happens exclusively in native iOS libraries - namely, everything from you begin the purchase to "your purchase was successful". We can't control that part, as it happens on iOS, and it is known to be slow, specially in Sandbox. However, the flow from after the purchase was confirmed by the OS until you receive updated purchaserInfo does happen on our servers, and they're typically fast (well under 1 second).

**Comment by Tom3652** [comment]
Hello guys, i am having the exact same issue under iOS 15.4. 
My app got rejected today by Apple because of this (they didn't see the prompt). 
When i tried in debug mode i got these logs : 

```
[Purchases] - DEBUG: ℹ️ Requesting products from the store with identifiers: {(
    "premium_subscription"
)}
[Purchases] - DEBUG: ℹ️ Products request finished.
[Purchases] - DEBUG: 💰 Retrieved SKProducts:
[Purchases] - DEBUG: 💰 premium_subscription - <SKProduct: 0x2829962a0>
[Purchases] - DEBUG: ℹ️ 1 completion handlers waiting on products
[Purchases] - DEBUG: ℹ️ makePurchase
[Purchases] - DEBUG: 💰 Purchasing product - premium_subscription
[Purchases] - DEBUG: ℹ️ PaymentQueue updatedTransaction: premium_subscription 2000000046660027 ((null)) 2000000046618823 - 1
[Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/A0C65C0D-77A4-44A0-AFB5-D8FDC588283F/StoreKit/sandboxReceipt
[Purchases] - DEBUG: ℹ️ Found 0 unsynced attributes for App User ID: GyLmrH9mpDaKpRPP9V2rUSfO9oq1
[Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /receipts
[Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
8.15.0 - [Firebase/Analytics][I-ACS023141] Purchase is a duplicate and will not be reported. Product ID: premium_subscription.   
[Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/receipts 200
[Purchases] - DEBUG: ℹ️ Serial request done: POST /receipts, 0 requests left in the queue
[Purchases] - DEBUG: 💰 Finishing transaction premium_subscription 2000000046660027 (2000000046618823)
flutter: Info : {entitlements: {all: {premium: {identifier: premium, isActive: false, willRenew: false, latestPurchaseDate: 2022-05-04T11:41:15Z, originalPurchaseDate: 2022-05-04T10:40:34Z, productIdentifier: premium_subscription, isSandbox: true, ownershipType: PURCHASED, store: APP_STORE, periodType: NORMAL, expirationDate: 2022-05-04T11:46:15Z, unsubscribeDetectedAt: 2022-05-04T11:46:24Z, billingIssueDetectedAt: null}}, active: {}}, allPurchaseDates: {premium_subscription: 2022-05-04T11:41:15Z}, activeSubscriptions: [], allPurchasedProductIdentifiers: [premium_subscription], nonSubscriptionTransactions: [], firstSeen: 2022-05-02T17:54:08Z, originalAppUserId: $RCAnonymousID:2adaea43f45542f987e7f965ab7b1189, allExpirationDates: {premium_subscription: 2022-05-04T11:46:15Z}, requestDate: 2022-05-04T15:48:35Z, latestExpirationDate: 2022-05-04T11:46:15Z, originalPurchaseDate: 2013-08-01T07:00:00Z, originalApplicationVersion: 1.0, managementURL: null}
[Purchases] - DEBUG: ℹ️ PaymentQueue removedTransaction: premium_subscription 2000000046660027 (2000000046618823 (null)) (null) - 1
```

Even a newly RevenueCat created users. 
It was working fine yesterday in debug mode with my app store sandbox account. I have tried again after Apple rejection and also tried to sign out from the sandbox account to get a real case scenario but the prompt didn't appear either. 

I have also tried removing all users from RevenueCat dashboard (to remove all pending transactions etc..) but this didn't seem to change anything unfortunately. 

I am using `flutter: 2.10.5` stable and `purchases_flutter: ^3.10.0`.
