### ISSUE TITLE
Data that should be enums are plain Strings

### ISSUE THREAD

**Issue by rocboronat** [RevenueCat/purchases-flutter#362]
Hi team 👋 

A simple feature request. As it's 100% code-related and not a whole RevenueCat feature I opened this issue. Don't hesitate to close it and ask me to do it in the support form if you think I should 😄

We're implementing some SKUs with a demo period and this is what I found while debugging:

![image](https://user-images.githubusercontent.com/456499/167066929-5ac921f7-b4d8-4fde-ae4c-0560b8a9cafe.png)

Period and period unit are Strings. It's not bad because it's easy to guess, but I can't know what other values I could expect. For example, is that  `P1W` stable between Android and iOS? What happens if you start sending me `P7D`? As they are just Strings, I'm not going to get any clue you changed it.

What do you think about moving those values to enums? If you do so, I will feel more confident about the data I could expect and, in case you change the values you share via the SDK, my implementation will fail at compilation time instead of just crashing or doing something not expected on production.

Thank you so much for your understanding! 🙏

**Comment by joshdholtz** [comment]
@rocboronat This seems like a reasonable feature request 😊 There are some other major changes happening to the Flutter SDK right now to bring it up to use iOS v4 and Android v5 so this would probably not happen until after those major changes 🤷‍♂️

**Comment by rocboronat** [comment]
Zero rush of course, first things first :·) I opened this because using the SDK as a user is different than developing it, and well, sometimes these easy things come unnoticed when building the API. Thanks a lot for the support, by the way! :·)

**Comment by joshdholtz** [comment]
@rocboronat Oh yeah, I totally get that 😇  I'm an iOS user of our SDK so I get some of these kinds of thoughts myself too but sadly I don't have a personal Flutter app (yet 🤔) so this is great to hear!

**Comment by vegaro** [comment]
I am going to be closing this since in 4.0.0 period unit is an enum. 

Sadly we can't make period an enum because it can have any value. For example, someone can configure a trial for any value of days/months/weeks/years in Google Play Store. You can set 14 days, 10 days, 2 days, 10 years, basically anything.
