### ISSUE TITLE
AdvertisingIdentifier

### ISSUE THREAD

**Issue by geekydiamond** [RevenueCat/purchases-flutter#37]
We have created an app that is in the App store 'made for kids' special category.
The app was rejected due to IDFA being present. Having searched our app it appears this comes from the Revenue Cat plugin.
`fgrep -R advertisingIdentifier .`
There are entries in RCAttributionFetcher.h, RCPurchases.m, and RCAttributionFetcher.m

Is it possible to remove this from the plugin so that we can successfully submit our app? Love the plugin and the RevenueCat approach, so really wouldn't want to remove our revenuecat integration and use another approach for subscriptions.

If there is a hack to do so please advise, any solution accepted right now!

Thanks,
Tom

**Comment by rkotzy** [comment]
Hi Tom!

The advertising identifier will only be accessed by RevenueCat if you have an attribution integration set up and have the AdSupport framework imported.

Do you have the AdSupport framework added to your project? I believe the reviewers check for presence of that framework to determine if you're using the IDFA or not.

**Comment by geekydiamond** [comment]
We do not have the adsupport framework added to our project. We are awaiting further details from the Apple development team, but have been told this could take up to a week to be given to us :(

**Comment by rkotzy** [comment]
Since you're not using the RevenueCat attribution integrations any references to the `advertisingIdentifier` property would be unused / not required. You would be safe to remove it from the source and re-submit until we can come up with an official solution.

It sounds like this rejection depends on the app reviewer since there are other Kids category apps using this SDK. We had heard of a similar rejection once before but it was un-confirmed if the AdSupport framework was also imported.

**Comment by geekydiamond** [comment]
We also use Firebase and I've just found this thread as well
https://github.com/firebase/firebase-ios-sdk/issues/5153

So it could be either. When we get Apple feedback we'll let you know.

Kind regards,
Tom Bailey



*Thomas Bailey*

*Life Ninja co-founder & CTO*

lifeninja.net <https://www.lifeninja.net/>
+44 7776154526









The information in this email is confidential and solely for the use of the
intended recipient(s). If you receive this email in error, please notify
the sender and delete the email from your system immediately. In such
circumstances, you must not make any use of the email or its contents. Views
expressed by an individual in this email do not necessarily reflect the
views of Life Ninja. Computer viruses may be transmitted by email. Life
Ninja accepts no liability for any damage caused by any virus transmitted
by this email. E-mail transmission cannot be guaranteed to be secure or
error-free. It is possible that information may be intercepted, corrupted,
lost, destroyed, arrive late or incomplete, or contain viruses. The sender
does not accept liability for any errors or omissions in the contents of
this message, which arise as a result of e-mail transmission.

Life Ninja Limited t/a Life Ninja.

Studio 109, 109b Marton Road, Middlesbrough, England, TS1 2DU. Registered
Number: 09253857

**Comment by rkotzy** [comment]
Great, please keep us posted.

**Comment by om-ha** [comment]
For the record, it's fine for an included third-party library (like RevenueCat) to have AdvertisingIdentifier, though "AdSupport.framework" framework should not be linked.

See more info in this [stackoverflow answer](https://stackoverflow.com/a/51150111).

Shameless plug: please [Expose `originalPurchaseDate` from `purchases-ios`](https://github.com/RevenueCat/purchases-flutter/issues/34) :)

**Comment by aboedo** [comment]
@geekydiamond did you figure this out?

**Comment by aboedo** [comment]
I'm closing this out due to inactivity, but feel free to reopen if the issue was indeed related to RevenueCat. It does seem to have been related to Firebase, though
