### ISSUE TITLE
Presenting the promo code sheet crashes [macos M1]

### ISSUE THREAD

**Issue by joecks** [RevenueCat/purchases-flutter#380]
https://github.com/RevenueCat/purchases-flutter/blob/8937a1fc82a89649cc54be9ae53018daff69782e/ios/Classes/PurchasesFlutterPlugin.m#L356

Version: 3.9.5
OS: MacOS 12.3 

With macos 12.3 it ios possible to run iOS apps on MacOS. But there seems to be an issue with the present promo code sheet method, which crashes the App:

```
Runner	-[SKPaymentQueue presentCodeRedemptionSheet]: unrecognized selector sent to instance 0x156ef3440
```

**Comment by beylmk** [comment]
@joecks 👋 thanks for alerting us to the crash. Unfortunately, even though the Apple docs say this is available for the mac runtime, it's not, and causes a crash. We fixed the crash by logging an error instead in our native iOS library [here](https://github.com/RevenueCat/purchases-ios/pull/1198/files), but that fix hasn't made it into our Flutter SDK yet.

I've created a ticket for us to port this fix to our hybrid SDKs!
