### ISSUE TITLE
Is 4.0.0 ever going to be released?

### ISSUE THREAD

**Issue by BWhiteApps** [RevenueCat/purchases-flutter#391]
It seems like I've been hearing "coming soon" for over a month now. Can you at least release a beta for in in pub.dev? We use 90+ packages in our project and purchases_flutter is the only one that is incompatible with the latest freezed. Sorry to complain but we do pay monthly to use this product.

Thanks!

**Comment by aboedo** [comment]
My apologies @BWhiteApps, we caught a blocker in Amazon store support that set us back unexpectedly, due to assumptions that Amazon's SDK makes about app lifecycle. 

We're working on updating that, but in the meantime, I'll post a beta tomorrow with that bug marked as a Known issue, so that you can start using that version.

**Comment by BWhiteApps** [comment]
Thanks, we appreciate it!

**Comment by aboedo** [comment]
just opened up https://github.com/RevenueCat/purchases-flutter/pull/392, I'll post again once it gets reviewed and published to pub.dev

**Comment by MinseokKang003** [comment]
Hi, I'm sorry to complain and I appreciate your efforts but I've also been waiting for the 4.0.0 update and it's delaying our app release. Could you please look into this issue?

**Comment by aboedo** [comment]
@MinseokKang003 I published `4.0.0-beta.1` to pub.dev.
This should allow you to get started on adopting the new version. We'll be publishing the final version soon. 

I realize that these delays are not ideal, but we're trying to take our time to make sure that what we release is stable and robust.

**Comment by CalHoll** [comment]
Is it safe to use the Beta if we don't use Amazon or is there more work/testing planned?

**Comment by aboedo** [comment]
There isn't any more non-amazon work planned, but we're still in the final stages of testing. I would recommend holding off from publishing to production until a non-beta release is out.

**Comment by CalHoll** [comment]
> There isn't any more non-amazon work planned, but we're still in the final stages of testing. I would recommend holding off from publishing to production until a non-beta release is out.

Appreciate the insight, any push to get v4 out would be much appreciated, I've got other deps that have necessary upgrades that are incompatible with v3. Thanks team!

**Comment by vegaro** [comment]
We just released version 4.0.0 https://github.com/RevenueCat/purchases-flutter/releases/tag/4.0.0

Please let us know if you have any issues. 

Thanks for your patience on this

**Comment by revenuecat-circleci-ios-certs** [comment]
👀 [TST-24] We've just linked this issue to our internal tracker and notified the team. Thank you for reporting, we're checking this out!
