### ISSUE TITLE
App crash on iOS when calling makePurchase() with non-existing product ID 

### ISSUE THREAD

**Issue by magnuswikhog** [RevenueCat/purchases-flutter#4]
I noticed that if I call `makePurchase(productID)` on iOS with a product ID that does not exist in App Store Connect (but that does exist in `Google Play Store`), the entire app crashes. Usually there is no error message, only a 

    Lost connection to device.

A few times I've seen this kind of output as well

    Failed to send request: {"jsonrpc":"2.0","id":"41","method":"resume","params":{"isolateId":"isolates/707523504"}}
    Lost connection to device.

I'm not sure what's going on, but a guess is that something is crashing in the native iOS code? Not sure why it causes the entire app to crash instead of generating a `PlatformException` though. 

This has only happened on iOS, and I'm testing it on an iPad Mini with iOS 12.4. This is the output from `flutter doctor`:

	Doctor summary (to see all details, run flutter doctor -v):
	[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-SE)
	 
	[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
	[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
	[✓] iOS tools - develop for iOS devices
	[✓] Android Studio (version 3.3)
	[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
	[✓] Connected device (1 available)

**Comment by vegaro** [comment]
This should have been fixed in https://github.com/RevenueCat/purchases-flutter/releases/tag/0.3.0

Thanks for reporting!
