### ISSUE TITLE
Paywall does not appear 70% of time on iOS Offer Code Redemption Sheet

### ISSUE THREAD

**Issue by nialljawad96** [RevenueCat/purchases-flutter#411]
- [✓] I have updated Purchases SDK to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [✓] I have searched the [Community](https://community.revenuecat.com)
- [✓] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [✓] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

## Environment ##
- [x] Output of `flutter doctor`:
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
[✓] VS Code (version 1.64.2)

- [x] Version of `purchases-flutter`:
purchases_flutter: ^3.10.0

- [x] Testing device version e.g.: iOS 15.5, Android API 30, etc :
iPhone X, iOS 15.6, Real Device

- [x] How often the issue occurs- every one of your customers is impacted? Only in dev?:
In about 30 tries happens 70% of the time. 

- [x] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue:
Unable to as I am on a real device (Testing offer codes via Purchases.presentCodeRedemptionSheet() - which only launches when app is on the App Store itself. 

- [x] Steps to reproduce, with a description of expected vs. actual behavior:
1) Launch Code Redemption Sheet.
2) Enter Offer Code, pre-configured via App Store Connect.
3) When I select redeem code, sometimes the paywall does not appear. There is no consistency behind it - sometimes it appears, sometimes it does not appear.

## Describe the bug ##
I am launching the code redemption sheet on iOS. So far, so good. When I get enter the offer code, it is accepted, and brings me to the page below in the image. When I click "Redeem Offer", the paywall sometimes appears, but 70% the time it does not appear.

There are 2 Entitlements we have - Proton Standard and Proton Ultra. There are 2 auto-renewable subscriptions - Proton Standard and Proton Ultra - each have a 1 week free trial. 
The Offer Codes are to give a subscription for 1 Year on Proton Ultra. 

In the incident above, it is done from a completely unsubscribed state (not currently on either entitlement, nor on a Trial.)

I have uploaded a In-App Purchase Key as per RevenueCat documentation. 

## Additional context ##

![Image from iOS (8)](https://user-images.githubusercontent.com/64364012/182413962-08bf19a1-3bac-408a-9868-7dd28295ec7a.png)

**Comment by aboedo** [comment]
Hi! 👋 Thanks for reporting!

`presentCodeRedemptionSheet` has proven to be a very unreliable API on StoreKit's side. Our SDK only bridges that API, so there's not much we can do to improve it on our side, sadly. 

We no longer recommend using that API directly because of this. [See our updated docs here.](https://docs.revenuecat.com/docs/ios-subscription-offers#2-redeeming-an-offer-code)

Instead, we recommend linking to the App Store app and having customers redeem through there, since that seems to work more reliably.

**Comment by nialljawad96** [comment]
Hi @aboedo, thanks a lot for your prompt reply!

Happy to do it through App Store instead and indeed from my testing it works more reliably. 

My only concerns are:

1) If a user redeems through the App Store route, and then starts the App up cold, how would I link this to their RevenueCat User ID - as the SDK won't know that they've done this externally through the App Store. The benefit of the `presentCodeRedemptionSheet` is that we can use the `addPurchaserInfoUpdateListener` to listen to the outcome. Would I have to call a `Purchases.restoreTransactions()` off the cuff to link the newly bought subscription on that Apple ID to the RevenueCat ID?

2) How would this work if a user redeemed through the App store route, whilst the App is in the foreground? Would a `addPurchaserInfoUpdateListener` called in the main() pick that up when the app is eventually resumed?

**Comment by nialljawad96** [comment]
Sorry just reopening this until the above is clarified - thanks.

**Comment by nialljawad96** [comment]
Sorry just reopening this until the above is clarified - thanks.

**Comment by aboedo** [comment]
To answer both questions: it will work regardless, and you'll get updates through the `purchaserInfoListener`.

What's going on under the hood:
When the redemption does go through in the App Store, the OS sends an update to the `SKPaymentQueue` in the app. Our SDK is observing the `SKPaymentQueue`, so it gets a notification that there was a successful transaction. We then get the updated receipt, validate it, and call the listener with the new `PurchaserInfo`. 

So when the code is redeemed through the App Store, your app still gets notified through the listener, just like if it was redeemed through the redemption sheet in-app.

**Comment by nialljawad96** [comment]
Brilliant thanks a lot for your help!
