### ISSUE TITLE
Error restoring purchase on Android: getPurchaseHistory() failed. Response code: 6

### ISSUE THREAD

**Issue by nemoryoliver** [RevenueCat/purchases-flutter#43]
```
D/[Purchases] - DEBUG( 1601): Restoring purchases
D/[Purchases] - DEBUG( 1601): Querying purchase history for type subs
W/BillingClient( 1601): getPurchaseHistory() failed. Response code: 6
W/[Purchases] - INFO( 1601): Error receiving purchase history. DebugMessage: An internal error occurred.. ErrorCode: ERROR.
E/[Purchases] - ERROR( 1601): There was a problem with the Play Store. | Error receiving purchase history. DebugMessage: An internal error occurred.. ErrorCode: ERROR.
I/flutter ( 1601): 💡  DebugTestingScreen - error: PlatformException(2, There was a problem with the Play Store., {code: 2, message: There was a problem with the Play Store., readableErrorCode: StoreProblemError, readable_error_code: StoreProblemError, underlyingErrorMessage: Error receiving purchase history. DebugMessage: An internal error occurred.. ErrorCode: ERROR.})
```

**Comment by nemoryoliver** [comment]
> D/[Purchases] - DEBUG( 8789): POST /receipts
> D/[Purchases] - DEBUG( 8789): POST /receipts 503
> E/[Purchases] - ERROR( 8789): There was a problem with the Play Store. | Google Play Error: The purchase token does not match the package name.
> E/[Purchases] - ERROR( 8789): Error restoring purchase: PurchaseHistoryRecordWrapper(isConsumable=false, purchaseToken=

**Comment by nemoryoliver** [comment]
Sorry for my dumb Opened Issue. I actually made a mistake in my package name setup in RevenueCat > Settings. Corrected and now the error is gone!

**Comment by scullabyte** [comment]
@nemoryoliver thanks for posting this. I had the exact same error, and it was from the name in Settings. I probably would have spent a long time trying to track this down if I didn't read this!
