### ISSUE TITLE
Entitlement is still active even after REFUNDED and REVOKED via Google Play

### ISSUE THREAD

**Issue by nemoryoliver** [RevenueCat/purchases-flutter#44]
I tested to purchase a lifetime entitlement, refunded and revoked it after, waited for the 5 minutes cache for the purchases SDK to be updated, then tried to call the restore purchases function, and still, I can restore or the entitlement is still active.

**Comment by nemoryoliver** [comment]
I've enabled logging. Here are the logs

```
D/[Purchases] - DEBUG(16550): POST /receipts
W/FirebaseRemoteConfig(16550): No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
D/[Purchases] - DEBUG(16550): POST /receipts 200
D/[Purchases] - DEBUG(16550): Consuming purchase with token mnabolibpghoegpijckhlkgf.AO-J1OzRWu2vKxrHFnlSrh9-kM0mWGns6zp6FUxF5-zrb51kZ5x4upSzrm_FbPO4cC1RYjFec-cRqVdhbEVcy9xWoOGfwM_mNafaZfTuJiiccw8fDhBfOzbO_dm_7gtdSeLZDkpWjQovC-aqSO0w6auxGqW29bowm-Ro_fQOHqhpAOE-veKY_F0
D/[Purchases] - DEBUG(16550): Purchase PurchaseHistoryRecordWrapper(isConsumable=true, purchaseToken=mnabolibpghoegpijckhlkgf.AO-J1OzRWu2vKxrHFnlSrh9-kM0mWGns6zp6FUxF5-zrb51kZ5x4upSzrm_FbPO4cC1RYjFec-cRqVdhbEVcy9xWoOGfwM_mNafaZfTuJiiccw8fDhBfOzbO_dm_7gtdSeLZDkpWjQovC-aqSO0w6auxGqW29bowm-Ro_fQOHqhpAOE-veKY_F0, purchaseTime=1588991694728, sku=bluer.facebook.pro.iap.lifetime, purchaseHistoryRecord=PurchaseHistoryRecord. Json: {"productId":"bluer.facebook.pro.iap.lifetime","purchaseToken":"mnabolibpghoegpijckhlkgf.AO-J1OzRWu2vKxrHFnlSrh9-kM0mWGns6zp6FUxF5-zrb51kZ5x4upSzrm_FbPO4cC1RYjFec-cRqVdhbEVcy9xWoOGfwM_mNafaZfTuJiiccw8fDhBfOzbO_dm_7gtdSeLZDkpWjQovC-aqSO0w6auxGqW29bowm-Ro_fQOHqhpAOE-veKY_F0","purchaseTime":1588991694728,"developerPayload":null}, type=INAPP) restored

W/BillingClient(16550): Error consuming purchase with token. Response code: 8
D/[Purchases] - DEBUG(16550): Error consuming purchase. Will retry next queryPurchases. DebugMessage: **Item is not owned by the user.. ErrorCode: ITEM_NOT_OWNED.**
```

**Comment by loregr** [comment]
Same here 👍 . follow

**Comment by rkotzy** [comment]
Google refunds can't be detected programmatically, so RevenueCat never removes the entitlement. 

There's the option to revoke subscriptions through the dashboard that RevenueCat can then pick up but this doesn't apply to non-subscriptions: https://docs.revenuecat.com/docs/customer-history#refunding-subscriptions

We may be able to add some support on the server to grant non-subscription refunds in the future.

**Comment by nemoryoliver** [comment]
> Google refunds can't be detected programmatically, so RevenueCat never removes the entitlement.
> 
> There's the option to revoke subscriptions through the dashboard that RevenueCat can then pick up but this doesn't apply to non-subscriptions: https://docs.revenuecat.com/docs/customer-history#refunding-subscriptions
> 
> We may be able to add some support on the server to grant non-subscription refunds in the future.

The revenuecat sdk detects the **item is not owned** flag through logs so I guess it's possible in the future this will be detetected by the sdk soon?

**Comment by nemoryoliver** [comment]
> Google refunds can't be detected programmatically, so RevenueCat never removes the entitlement.
> 
> There's the option to revoke subscriptions through the dashboard that RevenueCat can then pick up but this doesn't apply to non-subscriptions: https://docs.revenuecat.com/docs/customer-history#refunding-subscriptions
> 
> We may be able to add some support on the server to grant non-subscription refunds in the future.

Sorry for my late response. So what is best to do to remove the entitlement after refunding the user?

**Comment by arthurdenner** [comment]
@nemoryoliver, did you manage to solve this? I'm facing the same behaviour.

**Comment by nemoryoliver** [comment]
> @nemoryoliver, did you manage to solve this? I'm facing the same behaviour.

Hi @arthurdenner the solution they suggested to me was to manually delete the user in RC. But they're also working on a better solution they said.

**Comment by arthurdenner** [comment]
@nemoryoliver, I'm still a bit confused about how to accomplish this as the `ITEM_NOT_OWNED` error is logged but not thrown - so I could do something about it.

I'll investigate it a bit further as I'm implementing in-app purchases for the first time and create a new issue/discussion if needed.

Sorry for jumping on your issue and thank you for the quick reply! 😃

**Comment by ndhbr** [comment]
Are there any updates on this?

**Comment by javier-textmei** [comment]
I have been facing this same issue, the problem detecting refunds from the Google Play Android Developer API, it's that the in-app billing API will be getting the ITEM_ALREADY_OWNED, so if we remove the pro features, the user won't be able to purchase the item again.

**Comment by rkotzy** [comment]
@javier-textmei if you're refunding through the Google API, you may not necessarily be revoking so the user may still have access. RevenueCat never generates an ITEM_ALREADY_OWNED error directly, it's only forwarded from Google. 

I'm going to close this out since it's not a Flutter SDK issue exactly. There should be a dashboard UI and REST API available to support non-subscription purchases by the end of the month.

**Comment by armandojimenez** [comment]
Any updates on this? I used just bought lifetime and then google refunded them, still has the entitlement on RV

**Comment by armandojimenez** [comment]
Do you mean for non-renewal purchases? Users still has the entitlement after refund by google or me in the dashboard

**Comment by manuhook** [comment]
@aboedo I have the same problem : Users still has the entitlement active when the refund goes straight through Google (no action from our part).

You are saying there's no way to detect it programmatically but why Revenuecat doesn't manage that through Google Real-time developer notifications ?

After a subscription is refunded two realtime-events get sent. First, a SUBSCRIPTION_CANCELED event is sent, followed by a SUBSCRIPTION_REVOKED event.

https://developer.android.com/google/play/billing/rtdn-reference

**Comment by aboedo** [comment]
The Realtime developer notifications do allow us to revoke the entitlement, but we can't unequivocally distinguish a regular cancellation from a refund by relying on those events, unfortunately. 

@manuhook do you have Google Realtime Developer Notifications set up with RevenueCat for your app?

**Comment by fotiDim** [comment]
@aboedo why is it important to distinguish between a regular cancellation and a refund? In both cases, shouldn't the entitlement be revoked?

**Comment by aboedo** [comment]
@fotiDim re-reading my previous response I don't think I was clear. 

We do revoke the entitlement in both cases, so the only annoying part here would be that in analytics it won't correctly show up as a refund unless the refund was started through our dashboard or API endpoint.

**Comment by fotiDim** [comment]
@aboedo do you refer to subscriptions or non-subscriptions? Based on your [documentation],(https://www.revenuecat.com/docs/refunds) `If a non-subscription refund is granted by Google or initiated through the Google Play console, it will not be detected as a refund in RevenueCat, and the purchase will remain active`. Is that not accurate?

**Comment by aboedo** [comment]
Sorry, my comment was for subscriptions. We don't revoke access for non-subscriptions, but you can revoke from the dashboard or API endpoint.

**Comment by fotiDim** [comment]
@aboedo the OP talked about a lifetime entitlement so I guess this is the scope of this issue. This was closed as a non Flutter SDK issue which indeed it isn't but the proposed solution to use the dashboard or API endpoint only covers a fraction of the use cases as users can be granted refunds directly through Google. Therefore I think the issue should be revisited either here or in the native Android SDK.

The question that I have in my head is, since Google provides a way to [verify purchases](https://developer.android.com/google/play/billing/security#verify) why isn't that adopted by RevenueCat? 
In the scenario that I filled this gap myself, is there a way to revoke an entitlement through the SDK or API?

**Comment by rglanz-rc** [comment]
Hi @fotiDim, we do verify purchases to revoke entitlements when a user cancels or receives a refund. For _analytics_, a refund through Google looks the same as a cancellation on our end.

You cannot directly revoke an entitlement if the user paid for it, but you can offer a refund of a purchase through our dashboard. Alternatively, you can use [this API endpoint](https://www.revenuecat.com/reference/refund-a-google-subscription).

**Comment by fotiDim** [comment]
> we do verify purchases to revoke entitlements when a user cancels or receives a refund.

@rglanz-rc thanks for the clarification. It seems contradicting though to your documentation: `If a non-subscription refund is granted by Google or initiated through the Google Play console, it will not be detected as a refund in RevenueCat, and the purchase will remain active.` Which one holds true?

**Comment by rglanz-rc** [comment]
Both are correct. For subscriptions, we handle the entitlement. 

For [non-subscription purchases](https://www.revenuecat.com/docs/non-subscriptions) we leave handling the entitlement to the developer, as there are many ways to design non-subscription purchase logic (lifetime unlocks, tokens, etc).

**Comment by fotiDim** [comment]
@rglanz-rc I thought the scope of the topic was lifetime unlocks as per the original post... Anyway, if we are to verify the receipt ourselves this would require a server-side component which kind of defeats the whole purpose of using RevenueCat. 
Let's assume that we do go though that trouble and setup a service that our app calls to verify receipts and we find out that a certain purchase has been refunded. Is the go to strategy to revoke the entitlement using the [refund](https://www.revenuecat.com/reference/refund-a-google-subscription) endpoint?

**Comment by engineerbaraazakariya** [comment]
I still need this in 2025, so if the user bought the product then got a refund and then tried to re-get it the user can not ?! and the app will still say you have the product while they do not?
Also I think I deleted all the 'Customers' from the RevenueCat dashboard (sandbox) then I still get this error even after deleting the whole app local data and refund everything on Google Play Console side, I am on "@revenuecat/purchases-capacitor": "^10.3.0"

Any help? how to make this user know they don't have the product and re-enable the user to be able to buy this product any more times they like?
