### ISSUE TITLE
Expose method to check if purchases are available 

### ISSUE THREAD

**Issue by Brazol** [RevenueCat/purchases-flutter#48]
https://docs.revenuecat.com/docs/making-purchases#checking-if-purchases-are-available

This one is currently not supported in Flutter, right? I guess it should be easy to expose it via channels since there are examples for both Swift and Kotlin. Do you have it in backlog or maybe there is something that I'm missing?

**Comment by aboedo** [comment]
Hi! 👋 You're correct, it's not exposed yet. We're discussing options for the best implementation of this method that makes sense in a cross-platform environment (iOS and Android have different ways of handling this, with Android being a ton more granular when it comes to what's available). 
We're going to expose the method soon, though.

**Comment by bm888** [comment]
It would be great to see this flutter call in revenuecat soon! Thanks for the consideration.

**Comment by stea1thbear** [comment]
Without the canMakePayments iOS method supported in RevenueCat for Flutter you have to call it natively in iOS xcode. This  method is required by Apple in order to get approval for purchases. To say RevenueCat offers support for Flutter currently is misleading since you can't get approval for your iOS builds without this method from my understanding.

**Comment by rkotzy** [comment]
@stea1thbear this shouldn't cause any issues with app review. The method is mostly used by kids apps to show a UI if a parent disabled purchases. 

A different workaround to know if purchases are disabled could be looking out for `PURCHASE_NOT_ALLOWED` errors when trying to purchase and showing a UI there if that's a requirement for you.

**Comment by chirag-chopra** [comment]
Anyone please help me in implementing this plugin.
I am getting this error
[Invalid Play Store credentials errors](https://docs.revenuecat.com/docs/creating-play-service-credentials)

I tried this solution but still getting same error. There is already a project in **Google Cloud Platform**(that is created automatically by **firebase** when I implemented google login using firebase) but when I go to **Google Play Console** to link that project then I am unable to find that project in **existing projects** in **Api Access** section of **Google Play Console**. I don't know what's wrong I am doing.

Do I need to do anything special to make that existing Google Cloud Platform to see in **Api Access** of my google play console?
Please HELP...!

**Comment by aboedo** [comment]
@chirag-chopra the best place to figure out your issue is to contact our support at https://support.revenuecat.com. They'll be able to provide you with detailed assistance and step-by-step instructions. 

We reserve GitHub issues for bug reports only.

**Comment by chirag-chopra** [comment]
I also tried revenue cat support also but they didn't responded. I am so sorry that I am asking for help like this. But I am roaming here and there on internet for some support. Please help me. I will always remember you.

**Comment by armandojimenez** [comment]
I’m a little lost, I’m about to implement this package but here it says the method mentioned in the docs is not available for flutter? How do I know if a user is a premium user?

**Comment by aboedo** [comment]
@armandojimenez this thread refers specifically to a method called `canMakePayments`, which tells you if the user is able to make payments (for example, a parent may have restricted access to their child so that they can't buy items). 
In order to know if a user is a premium user, you check their subscription status ([docs here](https://docs.revenuecat.com/docs/purchaserinfo))

**Comment by aboedo** [comment]
Update here: this feature has been added in https://github.com/RevenueCat/purchases-flutter/pull/193, and will be a part of the next release. 

Sorry for the long wait for this one!

**Comment by beylmk** [comment]
This is included in the latest release, 3.3.0: https://github.com/RevenueCat/purchases-flutter/releases/tag/3.3.0

Going to close the ticket for now, but please re-open if you run into any issues!
