### ISSUE TITLE
iOS Unable to made a purchase on cancelled subscription still in the sandbox

### ISSUE THREAD

**Issue by yostrokon** [RevenueCat/purchases-flutter#50]
During integration after move from the in_app_purchases plugin getting error on trying to made reactivation of the subscription previously cancelled in the sandbox during tests with previous plugin

this is a log received in console

![Untitled-1](https://user-images.githubusercontent.com/41853897/82347170-fbe4af80-99ff-11ea-964e-71580cc4e45a.png)

Please advise

**Comment by aboedo** [comment]
@yostrokon did you get a chance to figure this out?
