### ISSUE TITLE
Fatal error: Unexpectedly found nil

### ISSUE THREAD

**Issue by manhpv-1697** [RevenueCat/purchases-flutter#506]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [ ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

# ‼️ Required data ‼️ #

## Environment ##
- [ ] Output of `flutter doctor`
- [ ] Version of `purchases-flutter` : 4.3.0
- [ ] Testing device version e.g.: iOS 15.5
- [ ] How often the issue occurs- every one of your customers is impacted? Only in dev?
- [ ] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
- [ ] Steps to reproduce, with a description of expected vs. actual behavior
**Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

## Describe the bug ##
PurchasesHybridCommon/CommonFunctionality.swift:77: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

**Comment by codykerns** [comment]
Hey @manhpv-1697, I'm not sure we have enough information here. It looks like that line might be related to collecting [ad identifiers](https://github.com/RevenueCat/purchases-hybrid-common/blob/main/ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift#L77). Are you able to provide the output of `flutter doctor` and some code snippets that are crashing?

**Comment by manhpv-1697** [comment]
@codykerns this is my flutter doctor
`[✓] Flutter (Channel stable, 3.3.4, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.3.4 on channel stable at /Users/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`
I just run app and it crash and receiver errorr : 
`PurchasesHybridCommon/CommonFunctionality.swift:77: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

 This is my code :
`if (Platform.isIOS) {
      Purchases.enableAdServicesAttributionTokenCollection();
    }
    await Purchases.configure(
        PurchasesConfiguration("***"));
    final userID = await Purchases.appUserID;
    analytics = FirebaseAnalytics.instance;
    await analytics?.setUserProperty(name: "revenuecat_id", value: userID);`

**Comment by manhpv-1697** [comment]
i remove Purchases.enableAdServicesAttributionTokenCollection() and project is not crash

**Comment by aboedo** [comment]
@manhpv-1697 Sorry that the error wasn't very clear, I'll make a note to improve it. 
But the issue is that you can only call that method _after_ the SDK is configured. Could you move that line to after the configure call?

**Comment by aboedo** [comment]
I opened up [this PR](https://github.com/RevenueCat/purchases-hybrid-common/pull/253) to improve the error message so it's  clearer

**Comment by aboedo** [comment]
Thanks for reporting!!
