### ISSUE TITLE
FatalException *** -[__NSCFConstantString stringByAppendingString:]: nil argument -[NSPlaceholderString initWithCharactersNoCopy:length:freeWhenDone:]

### ISSUE THREAD

**Issue by owenkealey** [RevenueCat/purchases-flutter#51]
Hi,

I have an app with about 800 users and the library works for 99% of people, but I saw this in Crashlytics today.
<img width="951" alt="Screen Shot 2020-05-19 at 7 34 56 PM" src="https://user-images.githubusercontent.com/26207512/82388705-3a7e6800-9a08-11ea-8bfe-a2e8ba37d473.png">

Any thoughts? I can provide more info if needed.

**Comment by aboedo** [comment]
Is your app deleting `NSUserDefaults`? If so, that would explain the crash.
If that is the case, there are a couple of workarounds, like only deleting the keys your app uses, or configuring RevenueCat with a separate instance of NSUserDefaults. Let me know if this is your case and I can elaborate more.

**Comment by owenkealey** [comment]
I have no idea honestly, I just setup the purchases library as was
instructed in the Flutter documentation for Revenue Cat.

**Comment by aboedo** [comment]
I see. My thinking is that there might be a plugin or something (or the app itself) that's deleting user defaults. 
I'm working on https://github.com/RevenueCat/purchases-flutter/issues/49, which will allow for a quick workaround for this issue on flutter. I'll keep you posted. 
In the meantime, are you using any plugins like [shared_preferences](https://flutter.dev/docs/cookbook/persistence/key-value) that might be causing this?

**Comment by owenkealey** [comment]
I am using flutter_secure_storage

**Comment by aboedo** [comment]
thanks for the info. That one _should_ be safe, since it internally uses the keychain for storage (from their docs). 
I'm not sure what might be causing NSUserDefaults getting cleared in your case, but I'll let you know as soon as I get the workaround out. 
in #49 there's another workaround that might help, although that one involves a bit more work on the dev side
