### ISSUE TITLE
iOS Unknown error - The operation is already in progress for this product

### ISSUE THREAD

**Issue by Yegair** [RevenueCat/purchases-flutter#538]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

## Environment ##
- [x] Output of `flutter doctor`
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.4 21F79 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```
- [x] Version of `purchases-flutter`
```
purchases_flutter: 4.4.1
```
- [x] Testing device version e.g.: iOS 15.5, Android API 30, etc.
```
iPhone XS iOS 15.6.1
```
- [x] How often the issue occurs- every one of your customers is impacted? Only in dev?
```
Production only, never seen in Sandbox or with StoreKit testing
```
- [ ] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
Unfortunately we have no logs, since it happens in production only

- [x] Steps to reproduce, with a description of expected vs. actual behavior

```
PlatformException: PlatformException(0, Unknown error., {userCancelled: false, message: Unknown error., readableErrorCode: UNKNOWN, readable_error_code: UNKNOWN, code: 0, underlyingErrorMessage: The operation is already in progress for this product.}, null)
```

## Describe the bug ##
Sometimes when a users purchases an auto-renewable subscription in production, the purchase succeeds, but we see the above error.

## Additional context ##
So far we have no idea what might be the cause

**Comment by michaelAtRC** [comment]
Hello, Does this user already have a subscription that they are trying to purchase? 

`underlyingErrorMessage: The operation is already in progress for this product.`
This error code usually is triggered when the there is multiple current attempts at creating the purchase. 

Since this issue isn't happening with more than just this customer and is not able to be reproduced, can you please open a support ticket by filling out this form here: https://www.revenuecat.com/contact/
