### ISSUE TITLE
How to unsubscribe ? 

### ISSUE THREAD

**Issue by nitneuq33000** [RevenueCat/purchases-flutter#54]
Hello, it's possible to use revenuecat futter sdk to call unsubscribe fonction to the store ? I don't see this function. New android rules force the develloper to be clear about informations, and show easy solution for the user to cancel subsription. thank you

**Comment by vegaro** [comment]
The right way of doing this would be to point the users to the Play Store section where they can cancel subscriptions. 

We have a feature in progress that will expose the URL in the PurchaserInfo, but for now, you can do it yourself by opening `https://play.google.com/store/account/subscriptions` using a plugin like https://pub.dev/packages/url_launcher

**Comment by friebetill** [comment]
Is there any news about this? Also, how do you do this on iOS?

**Comment by aboedo** [comment]
@friebetill yes! There's a property in `PurchaserInfo` called `managementURL` (https://github.com/RevenueCat/purchases-flutter/blob/develop/lib/purchaser_info_wrapper.dart#L53), which will provide you with the correct URL for the user, whether they purchased through Google Play or App Store.
