### ISSUE TITLE
Slow test card: RangeError (index): Invalid value: Not in range 0..18, inclusive: 20

### ISSUE THREAD

**Issue by liri2006** [RevenueCat/purchases-flutter#59]
Hi, I'm testing purchases with "Slow test card" on Android and right after payment window is closed the Exception is thrown "RangeError (index): Invalid value: Not in range 0..18, inclusive: 20"

Code:

```
try {
    final purchaserInfo = await Purchases.purchasePackage(package);
} on PlatformException catch (e) {
    var errorCode = PurchasesErrorHelper.getErrorCode(e); //<--- error here
    if (errorCode != PurchasesErrorCode.purchaseCancelledError) {
        print(e);
    }
}
```

It seems that code for the "The payment is pending." exception is 20.

**Comment by aboedo** [comment]
great catch! it seems like https://github.com/RevenueCat/purchases-flutter/blob/develop/lib/errors.dart has fallen out of sync with https://github.com/RevenueCat/purchases-android/blob/develop/purchases/src/main/kotlin/com/revenuecat/purchases/errors.kt#L29 and https://github.com/RevenueCat/purchases-ios/blob/develop/Purchases/Public/RCPurchasesErrors.h#L33. 

We'll fix it 👍

**Comment by aboedo** [comment]
@liri2006 this got fixed in https://github.com/RevenueCat/purchases-flutter/pull/64, thanks to @korzonkiee. 
it'll be a part of the next release!

**Comment by vegaro** [comment]
Release 1.2.0 will include this fix. Thanks for opening again!
