### ISSUE TITLE
Purchases.getEntitlements() results in PlatformException: Text cannot be parsed to a Period

### ISSUE THREAD

**Issue by magnus-lpa** [RevenueCat/purchases-flutter#6]
Since upgrading to 0.3.0, when I call `Purchases.getEntitlements()` I get this `PlatformException`:

	I/flutter ( 3369): PlatformException(error, Text cannot be parsed to a Period: , null) 
	I/flutter ( 3369): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
	I/flutter ( 3369): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
	I/flutter ( 3369): <asynchronous suspension>
	I/flutter ( 3369): #2      Purchases.getEntitlements (package:purchases_flutter/purchases_flutter.dart:96:24)
	I/flutter ( 3369): <asynchronous suspension>

	D/[Purchases] - DEBUG( 3369): Vending entitlements from cache
	E/MethodChannel#purchases_flutter( 3369): Failed to handle method call
	E/MethodChannel#purchases_flutter( 3369): java.lang.RuntimeException: Text cannot be parsed to a Period: 
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.PurchasesPeriod.parse(PurchasesPeriod.java:92)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.Mappers.putIntroPrice(Mappers.java:74)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.Mappers.map(Mappers.java:34)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.Mappers.map(Mappers.java:146)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.PurchasesFlutterPlugin.mapEntitlementsAndCacheProducts(PurchasesFlutterPlugin.java:188)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.PurchasesFlutterPlugin.access$100(PurchasesFlutterPlugin.java:41)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.PurchasesFlutterPlugin$3.onReceived(PurchasesFlutterPlugin.java:177)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases.Purchases$getEntitlements$$inlined$let$lambda$1.invoke(Purchases.kt:217)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases.Purchases$getEntitlements$$inlined$let$lambda$1.invoke(Purchases.kt:50)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases.Purchases.dispatch(Purchases.kt:779)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases.Purchases.getEntitlements(Purchases.kt:216)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.PurchasesFlutterPlugin.getEntitlements(PurchasesFlutterPlugin.java:174)
	E/MethodChannel#purchases_flutter( 3369): 	at com.revenuecat.purchases_flutter.PurchasesFlutterPlugin.onMethodCall(PurchasesFlutterPlugin.java:93)
	E/MethodChannel#purchases_flutter( 3369): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
	E/MethodChannel#purchases_flutter( 3369): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
	E/MethodChannel#purchases_flutter( 3369): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
	E/MethodChannel#purchases_flutter( 3369): 	at android.os.MessageQueue.nativePollOnce(Native Method)
	E/MethodChannel#purchases_flutter( 3369): 	at android.os.MessageQueue.next(MessageQueue.java:325)
	E/MethodChannel#purchases_flutter( 3369): 	at android.os.Looper.loop(Looper.java:142)
	E/MethodChannel#purchases_flutter( 3369): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
	E/MethodChannel#purchases_flutter( 3369): 	at java.lang.reflect.Method.invoke(Native Method)
	E/MethodChannel#purchases_flutter( 3369): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	E/MethodChannel#purchases_flutter( 3369): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**flutter doctor -v**

	[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-SE)
	    • Flutter version 1.7.8+hotfix.4 at /Users/Magnus/development/flutter
	    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
	    • Engine revision fee001c93f
	    • Dart version 2.4.0

	 
	[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
	    • Android SDK at /Users/Magnus/Library/Android/sdk
	    • Android NDK location not configured (optional; useful for native profiling support)
	    • Platform android-29, build-tools 28.0.3
	    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
	    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
	    • All Android licenses accepted.

	[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
	    • Xcode at /Applications/Xcode.app/Contents/Developer
	    • Xcode 10.3, Build version 10G8
	    • CocoaPods version 1.6.1

	[✓] iOS tools - develop for iOS devices
	    • ios-deploy 1.9.4

	[✓] Android Studio (version 3.3)
	    • Android Studio at /Applications/Android Studio.app/Contents
	    • Flutter plugin version 33.3.1
	    • Dart plugin version 182.5215
	    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

	[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
	    • IntelliJ at /Applications/IntelliJ IDEA.app
	    • Flutter plugin version 33.3.2
	    • Dart plugin version 183.5901

	[✓] Connected device (1 available)
	    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

	• No issues found!

**Comment by vegaro** [comment]
Thanks for reporting. There was a bug that has been fixed in https://github.com/RevenueCat/purchases-flutter/releases/tag/0.3.1
