### ISSUE TITLE
Handle Slow card purchases

### ISSUE THREAD

**Issue by liri2006** [RevenueCat/purchases-flutter#60]
I'm using a "Slow card" option to test a purchase. Is there a way to get a purchase status when it finishes (in order to show success/error message or direct user to unlocked page, etc)? 

I do receive a callback in PurchaserInfoUpdateListener after transaction finished, but I'm not able to say if purchase succeeded or not.

**Comment by aboedo** [comment]
you're correct, the listener will only get a value for the updated purchaserInfo. 

The purchasePackage and purchaseProduct methods, however, do optionally send an error. 
If there's no error, you should be able to assume that the purchase went through correctly. If there's an error, it might be due to a user cancellation. The methods also throw a PlatformException if the purchase was unsuccessful.

**Comment by liri2006** [comment]
The issue here is that in case of slow purchases payment can go through/fail after few minutes. User can navigate away from the paywall to all different sorts of pages where getPurchaserInfo is called. 
And now there is no way to tell why PurchaserInfoUpdateListener was triggered - was it because purchase went through (and which one for that matter) or subscription expired, or some other purchase was made on other device.

_PS. Thank you guys for this lib and RevenueCat in general - the service is just great! I was fighting with official flutter plugin for few days - it is such a buggy mess! Then I found RevenueCat and implemented the whole thing in few hours._

**Comment by aboedo** [comment]
> PS. Thank you guys for this lib and RevenueCat in general - the service is just great! I was fighting with official flutter plugin for few days - it is such a buggy mess! Then I found RevenueCat and implemented the whole thing in few hours

You made my day 😃

Thinking about your case: 
yeah, from the listener you wouldn't have a way to find out _why_ the `purchaserInfo` got updated. And the listener itself doesn't contain the error messages either. 

So you would delegate all of that to the completion block of `purchasePackage` | `purchaseProduct`. 
So when that specific function is called (the completion block of the purchase method), you know, no matter where your app is, that it was called after receiving information about the status of the purchase, and you can react from there. You'll get the latest `purchaserInfo` as a param of the callback, as well as an error if one occurred.

**Comment by aboedo** [comment]
That said, if the purchase is `PENDING`, you'd only get `purchaserInfo` updated, but no callback. 
We're trying to figure out how to improve that behavior (https://github.com/RevenueCat/purchases-android/issues/160), since it's not ideal. See that ticket for details

**Comment by liri2006** [comment]
Well, while workaround "call purchasePackage -> store flag somewhere if PENDING -> assume that particular purchase has finished" can theoretically work but it is not 100% bullet proof.

User can make few purchases in a row, so after receiving purchaserInfo there is no way to know which feature to unlock (except storing previous state of purchaserInfo and comparing what changed on every update).

Adding some kind of purchase life-cycle event stream would give a developer flexibility to implement almost any kind of purchase workflow he wants.

**Comment by aboedo** [comment]
agreed. moving this to backlog since we'll integrate the fix as soon as we do it on `purchases-android`. However, I don't know when we'll get to tackle it since we have other items on our plate.

**Comment by stnguyen90** [comment]
Is there any workaround for handling these pending payments? I am also running into this.

**Comment by rkotzy** [comment]
You should be able to detect a pending payment when it occurs through a specific purchase error, but there isn't an officially supported way to determine if there is a pending payment from the PurchaserInfo object.

We have this on the backlog, and would like to develop a solution that works cross-platform since there are pending purchases on iOS as well. Since this is really a backend API feature and not a specific Flutter SDK issue I'm going to close this out for now.

**Comment by mangal-brovitech** [comment]
@rkotzy Is there any workaround for handling these pending payments completed? I am using react native for this ?

**Comment by Harteg** [comment]
I can't believe RevenueCat doesn't handle this properly
