### ISSUE TITLE
PurchasesHybridCommon/CommonFunctionality.swift:21: Fatal error: Purchases has not been configured. Please configure the SDK before calling this method

### ISSUE THREAD

**Issue by rmartinezifi** [RevenueCat/purchases-flutter#651]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

## Environment ##
- [x] Output of `flutter doctor`
```
[✓] Flutter (Channel master, 3.9.0-20.0.pre.90, on macOS 13.3 22E252
    darwin-arm64 (Rosetta), locale es-ES)
[✗] Android toolchain - develop for Android devices
    ✗ cmdline-tools component is missing
      Run 'path/to/sdkmanager --install "cmdline-tools;latest"'
      See https://developer.android.com/studio/command-line for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.77.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```
- [x] Version of `purchases-flutter`
4.11.1
- [x] Testing device version e.g.: iOS 15.5, Android API 30, etc.
iOS 16.4
- [x] How often the issue occurs- every one of your customers is impacted? Only in dev?
Occurs only on production builds
- [ ] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
The App crashes before output any log.
- [x] Steps to reproduce, with a description of expected vs. actual behavior
Open the App.

## Describe the bug ##
Just after opening the App crashes throwing `PurchasesHybridCommon/CommonFunctionality.swift:21: Fatal error: Purchases has not been configured. Please configure the SDK before calling this method`. The App runs randomly normal after few attempts, but the normal behaviour is a crash.

## Additional context ##
I'm only having this issue on production, if i run on debug mode works as expected.

**Comment by sid9841** [comment]
How was the issue solved? Can you let me know? I have the same issue

**Comment by rmartinezifi** [comment]
Yes it's solved, we were calling purchases on a function called after first layout, but in this function, the configuration wasn't init. We init purchases configuration in this function and it's already working. So i think, you have to look for where you init purchases configuration and where are you calling it.

**Comment by HaleyRevcat** [comment]
Hi, this issue arises if you are trying to call methods from the SDK before initializing it. So you want to make sure to call configure before trying to access any of the methods.

**Comment by sid9841** [comment]
Future<void> initPlatformState() async {

    await Purchases.setDebugLogsEnabled(true);

    PurchasesConfiguration configuration;
    if (Platform.isIOS) {
      configuration = PurchasesConfiguration('<APPLE KEY>');

    } else  {
      configuration = PurchasesConfiguration('<GOOGLE KEY>');

    }
    await Purchases.configure(configuration);

      setState(() {});
  }
  this is the init function for configuraton? still same issue

**Comment by rmartinezifi** [comment]
Hi, look where are you calling initPlatformState() maybe you are calling purchases before doing the init. I had a mixin that calls a function at end of frame and i had to init purchases on that function.
