### ISSUE TITLE
unknown errors - possible problems with the server

### ISSUE THREAD

**Issue by FetFrumos** [RevenueCat/purchases-flutter#718]
- [*] I have updated Purchases SDK to the latest version
- [+] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [+] I have searched the [Community](https://community.revenuecat.com)
- [+] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [+] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

## Environment ##
[ ] Output of `flutter doctor`
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.2.1 22D68 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] Network resources

[ ] Version of `purchases-flutter`
4.13.0 [#](https://pub.dev/packages/purchases_flutter/changelog#4130)

[ ] Testing device version e.g.: iOS 15.5, Android API 30, etc.
iPhone 7. -ios15.7.6, Samsung a10 - android 11

[ ] How often the issue occurs- every one of your customers is impacted? Only in dev?
the error appeared 4-5 days ago, it is in prod and dev

[ ] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

ios

`[Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST receipts

[Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
[Purchases] - DEBUG: ℹ️ SKReceiptRefreshRequest finished
[Purchases] - DEBUG: ℹ️ Loaded receipt from url file:///private/var/mobile/Containers/Data/Application/D1593594-6743-4414-BC41-E34FC5560BEE/StoreKit/sandboxReceipt
[Purchases] - DEBUG: ℹ️ Skipping products request for these products because they were already cached: ["myCode"]
[Purchases] - ERROR: 😿‼️ Unknown error.
[Purchases] - DEBUG: ℹ️ API request failed: POST /v1/receipts: Unknown error.
[Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Finished
[Purchases] - DEBUG: ℹ️ Serial request done: POST receipts, 0 requests left in the queue
[Purchases] - INFO: 💰 Finishing transaction '2000000346016019' for product 'myCode'
[Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Started
[Purchases] - INFO: ℹ️ Parsing receipt
[Purchases] - DEBUG: ℹ️ StoreKit1Wrapper (0x000000028009daa0) removedTransaction: myCode 2000000346016019 2000000154674445 1
[Purchases] - ERROR: 😿‼️ Unknown error.
[Purchases] - ERROR: 💰 Product purchase for 'myCode' failed with error: Error Domain=RevenueCat.ErrorCode Code=0 "Unknown error." UserInfo={rc_backend_error_code=0, NSLocalizedDescription=Unknown error.,`

then this cycle is repeated(POST /v1/receipts ->😿‼️ Unknown error)

sometimes it doesn't complete/hangs
`final purchaserInfo = await Purchases.getCustomerInfo();`

Android:

`PlatformException(10, Error performing request., {code: 10, message: Error performing request., readableErrorCode: NetworkError, readable_error_code: NetworkError, underlyingErrorMessage: Unable to resolve host "api.revenuecat.com": No address associated with hostname}, null)`

## Describe the bug ##
For android - this error does not appear every time but today very often. 4-5 days ago it was working

The subscription logic in my application is broken. I need urgent help

**Comment by mshmoustafa** [comment]
Hello,

For Android, it seems that the device isn't able to reach RevenueCat for some reason. Are you able to reach revenuecat.com via the browser on the device?

**Comment by usamawork61** [comment]
Any update on this?

**Comment by mshmoustafa** [comment]
I'm going to close this ticket out as it has become stale but @usamawork61 if you have a similar issue feel free to open a new issue with logs or reach out to support via [our contact form](https://app.revenuecat.com/settings/support).
