### ISSUE TITLE
IntroductoryPrice returns wrong cycles and periodUnit

### ISSUE THREAD

**Issue by RicardoRB** [RevenueCat/purchases-flutter#743]
## Environment ##
- [ ] Output of `flutter doctor`
``` bash
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Versi¢n 10.0.22621.1848], locale es-ES)
    • Flutter version 3.10.5 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (13 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
```
- [ ] Version of `purchases-flutter`
`purchases_flutter: ^5.1.0`

- [ ] Testing device version e.g.: iOS 15.5, Android API 30, etc.
`Android`
- [ ] How often the issue occurs- every one of your customers is impacted? Only in dev?
`Production`
- [ ] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
`I can't get logs from production`
- [ ] Steps to reproduce, with a description of expected vs. actual behavior
`Basically getting the offerings with intro price`
**Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

## Describe the bug ##
I'm getting wrong cycles and periodUnit in production when getting the offerings by revenuecat, currently I'm getting **1 Year** instead of **3 Months**. The configuration looks good on my side. I let you attach some screen (unfortunately in Spanish):

![image](https://github.com/RevenueCat/purchases-flutter/assets/3050311/57fb51a3-f459-4469-b718-41056898ec25)
![image](https://github.com/RevenueCat/purchases-flutter/assets/3050311/693bda21-34f8-4bdd-bb79-6cbe41736fbe)

Here is in revenuecat:

![image](https://github.com/RevenueCat/purchases-flutter/assets/3050311/73080a6f-416d-4fe4-a707-6630d3aaffe0)

## Additional context ##
I let you some of my code that I'm using in order to retrieve those offerings and packages:

bloc.dart
```dart
        final String result = _remoteConfig.getString('revenuecat_offering_id');

        final Offerings offerings = await Purchases.getOfferings();
        final Offering? foundOffering = offerings.getOffering(result);
        final Offering? offering = foundOffering ?? offerings.current;
        final purchaseUser = await Purchases.getCustomerInfo();
        final bool canUserHaveFreeTrial;
        if (Platform.isIOS) {
          final mapEligibility =
              await Purchases.checkTrialOrIntroductoryPriceEligibility(
                  purchaseUser.entitlements.all.keys.toList());
          canUserHaveFreeTrial = mapEligibility.values.any((element) =>
              element.status ==
              IntroEligibilityStatus.introEligibilityStatusEligible);
        } else {
          // user has had access to an entitlement which means
          // they're not eligible for the offer
          // or
          // user has never had access to any entitlements
          // show intro offer
          canUserHaveFreeTrial = purchaseUser.entitlements.all.isEmpty;
        }
        if (offering != null) {
          final List<Package> packages = offering.availablePackages;
          final sortedPrices = _sortPrices(packages);
          final int selectedIndex = _findIndexWithBiggestDiscount(sortedPrices);
          emit(PaywallLoadSuccess(
            packages: sortedPrices,
            selectedIndex: selectedIndex,
            canUserHaveIntroPrice: canUserHaveFreeTrial,
          ));
        }
```

widget.dart

```dart
                      Visibility(
                        visible: state.canUserHaveIntroPrice,
                        replacement: ElevatedButton(
                          style: ElevatedButton.styleFrom(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(18.0),
                            ),
                            minimumSize: const Size(double.infinity, 45),
                          ),
                          child: Text(
                            S.of(context).supermarketBtnContinue,
                            style: const TextStyle(
                              fontSize: 20,
                            ),
                          ),
                          onPressed: () {
                            _bloc.add(PaywallPaymentRequest(
                              product: selectedProduct,
                            ));
                          },
                        ),
                        child: ElevatedButton(
                          style: ElevatedButton.styleFrom(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(18.0),
                            ),
                            minimumSize: const Size(double.infinity, 45),
                          ),
                          child: Text(
                            _paymentButtonText(
                                selectedProduct.introductoryPrice),
                            textAlign: TextAlign.center,
                            style: const TextStyle(
                              fontSize: 20,
                            ),
                          ),
                          onPressed: () {
                            _bloc.add(PaywallPaymentRequest(
                              product: selectedProduct,
                            ));
                          },
                        ),
                      ),
```

method in the widget.dart

```dart
  String _paymentButtonText(final IntroductoryPrice? introductoryPrice) {
    if (introductoryPrice != null) {
      final translatedPeriod = _translatePeriodUnit(
          introductoryPrice.periodUnit, introductoryPrice.cycles);
      final periodString = '${introductoryPrice.cycles} '
              '$translatedPeriod'
          .toLowerCase();
      return S.of(context).paywallTxtFreeTrial(periodString);
    }
    return S.of(context).supermarketBtnContinue;
  }
```

**Comment by RicardoRB** [comment]
Adding some more information, it looks like it doesn't work specifically to 1 Year introduction price, the rest, works in my app:

![Imagen1](https://github.com/RevenueCat/purchases-flutter/assets/3050311/b0de3574-f5a0-43e7-b710-91e0e36d493a)
![Imagen2](https://github.com/RevenueCat/purchases-flutter/assets/3050311/93135a12-6668-4eea-a447-6be4d1623c05)
![Imagen3](https://github.com/RevenueCat/purchases-flutter/assets/3050311/ffdb62ad-2b5b-42d2-8b37-a25c20854c61)

**Comment by MarkVillacampa** [comment]
Hello @RicardoRB!

Thanks for your report. We've release version 5.2.2 which should fix your issue, please try it and let me know if you still experience any issue.

https://github.com/RevenueCat/purchases-flutter/releases/tag/5.2.2

**Comment by RicardoRB** [comment]
Hi @MarkVillacampa!

Thank you for the quick fix, but it still doesn't work... now it appears 1 Month in all the subscriptions instead of 3 Months in the 1-Year subscription... Here you have some screenshots again:

![Imagen de WhatsApp 2023-06-28 a las 14 54 18](https://github.com/RevenueCat/purchases-flutter/assets/3050311/6fa57cc8-ca44-42a2-995a-9359391b45f2)
![Imagen de WhatsApp 2023-06-28 a las 14 54 02](https://github.com/RevenueCat/purchases-flutter/assets/3050311/d7476a1b-9c15-4d5e-8720-d1ebfaf58688)
![Imagen de WhatsApp 2023-06-28 a las 14 54 36](https://github.com/RevenueCat/purchases-flutter/assets/3050311/d285fa34-32bd-47d5-b23b-0b9a3823e60c)

**Comment by purelogiq** [comment]
@MarkVillacampa confirming that this is still an issue on 5.2.3. The offering's `introductoryPrice` remains null. Thanks ahead of time! :pray:

**Comment by purelogiq** [comment]
@MarkVillacampa 5.2.3 is working after a flutter clean and rebuild, it's possible I missed something last night. Thanks!

![play-console-free-trial-config](https://github.com/RevenueCat/purchases-flutter/assets/7828780/24c184e2-9a4d-442d-9da3-5ee81f5bdf64)

**Comment by RicardoRB** [comment]
Hi there! It looks it's working still, maybe haven't I done something correctly?

**Comment by RicardoRB** [comment]
Something new here? :)

**Comment by MarkVillacampa** [comment]
Hello @RicardoRB

Have you tried with the latest [5.3.0](https://github.com/RevenueCat/purchases-flutter/releases/tag/5.3.0) version? We added a further [fix](https://github.com/RevenueCat/purchases-hybrid-common/pull/449) that could solve your issue.
