### ISSUE TITLE
Entitlement.willRenew not updated

### ISSUE THREAD

**Issue by kinex** [RevenueCat/purchases-flutter#75]
I am testing subscriptions in Android. Even if I cancel a subscription using the Play Store app, `Entitlement.willRenew` still returns true and `Entitlement.unsubscribeDetectedAt` is null. If I look at the subscription info in Play Store app, it shows the correct status (cancelled).

**Comment by vegaro** [comment]
Hi @kinex! Unfortunately, this type of subscription change is not caught in real time by RevenueCat, and it can take a few hours to be reflected. Most of the times, this delay can be improved by activating server to server notifications (https://docs.revenuecat.com/docs/server-notifications), even though we've seen cases in which they are also flaky. I hope that answers your question.

**Comment by vegaro** [comment]
If you are testing in Sandbox, the subscriptions renew every 5/10 minutes. 5 minutes is not time enough to ask Play Store from our servers for the status of the subscription. We could refresh the status of the subscriptions more often, but Google limits the number of times someone can hit their API. 

In production, subscription last for longer, and the subscription status will be refreshed every some hours.

We talk about why the dashboard might not show some renewals in this in this section of the docs https://docs.revenuecat.com/docs/google-play-store#working-with-subscriptions. The same applies for your case.

**Comment by kinex** [comment]
In my subscription status page I was planning to show status text e.g. "Valid, renews on 30th June 2021" or "Cancelled, expires on 30th June 2021" depending on the `willRenew` flag. In the same page there is a button for managing the subscription (launches the Play Store app where user can cancel or restore a subscription). User can launch the Play Store app for cancelling a subscription and then navigate back to my subscription status page. So in my planned use case any delay above few seconds is too long, I cannot show to user invalid status like "Valid, renews on 30th June 2021" if user just cancelled a subscription few seconds ago.

It seems I have to accept that with RevenueCat it is not possible to show to user the subscription renewal date or expiration date. You can show reliably to user only that subscription is valid up to some date. What happens after that is not known for sure...

**Comment by vegaro** [comment]
You can enable https://docs.revenuecat.com/docs/server-notifications for your app. That will allow us to get the information from Play Store almost at real time instead of every a few hours.
