### ISSUE TITLE
PurchaserInfo not updated on subscription downgrade

### ISSUE THREAD

**Issue by rahulraj64** [RevenueCat/purchases-flutter#77]
The **PurchaserInfo** is working as expected when we try to purchase a single subscription. It properly returns the entitlements on calling **Purchases.getPurchaserInfo()** as well as **Purchases.purchasePackage(package)**. But when trying to downgrade a subscription in the same **subscription group**, the PruchaserInfo is not properly updated with the latest values in **Purchases.getPurchaserInfo()** as well as **Purchases.purchasePackage(package)** calls. 

When we purchase a subscription upgrade or downgrade, it is expected to return the most recent subscription state, since it is made from the same device and we are already aware of the cache. I tried, force quitting the app, still, the recent subscription state is not updated. Since this is a sandbox testing, I am also unable to check whether this is updating properly after a few hours or so, because, in that buffer time, the subscription will be automatically ended. 

Platform: Tested on iOS
Library: purchases_flutter: 1.1.1
Subscription Type: Both are monthly subscriptions with different rates.

To reproduce this,

1. Purchase a subscription from a group. (Then **Purchases.purchasePackage(package)** call will return the correct subscription state)
2. [optional] Call Purchases.getPurchaserInfo() (Then it returns the correct subscription state)
3. Purchase a subscription downgrade from the same group (Then **Purchases.purchasePackage(package)** returns the result same as **step 1**)
4. [optional] Call Purchases.getPurchaserInfo() (Then it returns the result same as **step 1**)
Expected: The most recent subscription state in all subscripion purchase, upgrade & downgrade

**Comment by owenkealey** [comment]
Not sure if this is related(seems like it might be) but `addPurchaserInfoUpdateListener` doesnt seem to execute ever, or at least when its first set like the docs say it will. Code:

```
  /// Configures premium status
  Future<void> configurePremiumStatus() async{
    print("CALLING FUNCTION");
    Purchases.addPurchaserInfoUpdateListener((PurchaserInfo purchaserInfo) {
      print("Callback executing");
      if(globals.firebaseUser.uid == "Kcd218TyeQTFQwx48MnNh4OhOnf1"){
        globals.premiumUser = true;
      }
      else if(purchaserInfo.entitlements.all["Premium"] != null && purchaserInfo.entitlements.all["Premium"].isActive){
        globals.premiumUser = true;
      }
      else if(purchaserInfo.entitlements.all["Premium"] == null || !purchaserInfo.entitlements.all["Premium"].isActive){
        globals.premiumUser = false;
      }
    });
  }```

Output:
````
flutter: CALLING FUNCTION
```

**Comment by rkotzy** [comment]
Upgrades / downgrades aren't supported in the current iOS sandbox so that sounds like what could be going on here.
