### ISSUE TITLE
Support for stripe subscriptions

### ISSUE THREAD

**Issue by KieranLafferty** [RevenueCat/purchases-flutter#8]
For real world goods and services it's possible to use stripe subscriptions instead of apple's IAP subscriptions. Given that Stripe subscriptions are in beta on RevenueCat it would be great if this package would support fetching/purchasing using Stripe in place of the native platform subscription

**Comment by dimdomsum** [comment]
This would be really, really great!

**Comment by dimdomsum** [comment]
This would be really, really great! Right now we can't take purchases online at all.

**Comment by dimdomsum** [comment]
This would be really, really great. My company is starting to use Flutter for web and want to use RevenueCat. I can't make the case for RevenueCat on web if there's no Stripe integration.

**Comment by vegaro** [comment]
The product team has this in their thoughts. We don't have plans of adding Stripe support to our SDKs in the near future though as we are focusing on Google and Apple IAPs for mobile.
Since this is more a feature request than an issue I am going to close this to keep the repository tidy.
