### ISSUE TITLE
Flutter plugin example v 1.2.1. not working

### ISSUE THREAD

**Issue by integramus** [RevenueCat/purchases-flutter#85]
Hi

Getting Errors when i try to run the Flutter plugin example v 1.2.1. Any ideas?

Launching lib/RevenueCatExample.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                           26.8s
Configuring the default Firebase app...
6.27.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
Configured the default Firebase app __FIRAPP_DEFAULT.
6.27.0 - [Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
6.27.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60601000 started
6.27.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
Waiting for iPhone Xʀ to report its views...
6.27.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
Debug service listening on ws://127.0.0.1:64736/KaJJYKx05a0=/ws
Syncing files to device iPhone Xʀ...
6.27.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
[Purchases] - DEBUG: Debug logging enabled.
[Purchases] - DEBUG: SDK Version - 3.4.0
[Purchases] - DEBUG: Initial App User ID - (null)
[Purchases] - DEBUG: GET /v1/subscribers/$RCAnonymousID:02abcbccebf7473fa58bcd51a8cba9a9
[Purchases] - DEBUG: GET /v1/subscribers/$RCAnonymousID:02abcbccebf7473fa58bcd51a8cba9a9/offerings
[Purchases] - DEBUG: Delegate set
[Purchases] - INFO: There is an instance configured, posting attribution.
[Purchases] - DEBUG: AdSupport framework not imported. Attribution data incomplete.
[Purchases] - DEBUG: POST /v1/subscribers/$RCAnonymousID:02abcbccebf7473fa58bcd51a8cba9a9/attribution
[Purchases] - DEBUG: No cached purchaser info, fetching
[Purchases] - DEBUG: GET /v1/subscribers/$RCAnonymousID:02abcbccebf7473fa58bcd51a8cba9a9 401
[Purchases] - ERROR: There was a credentials issue. Check the underlying error for more details.
[Purchases] - ERROR: There was a credentials issue. Check the underlying error for more details.
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(11, There was a credentials issue. Check the underlying error for more details., {code: 11, message: There was a credentials issue. Check the underlying error for more details., underlyingErrorMessage: Invalid API Key., readable_error_code: INVALID_CREDENTIALS, readableErrorCode: INVALID_CREDENTIALS})
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      Purchases.getPurchaserInfo (package:purchases_flutter/purchases_flutter.dart:271:24)
#4      _MyAppState.initPlatformState (package:stonematch/RevenueCatExample.dart:34:51)
<asynchronous suspension>
#5      _MyAppState.initState (package:stonematch/RevenueCatExample.dart:26:5)
#6      StatefulElement._firstBuild <…>
[Purchases] - DEBUG: GET /v1/subscribers/$RCAnonymousID:02abcbccebf7473fa58bcd51a8cba9a9/offerings 401
[Purchases] - ERROR: There was a credentials issue. Check the underlying error for more details.
[Purchases] - INFO: Error fetching offerings - Error Domain=RCPurchasesErrorDomain Code=11 "There was a credentials issue. Check the underlying error for more details." UserInfo={readable_error_code=INVALID_CREDENTIALS, NSLocalizedDescription=There was a credentials issue. Check the underlying error for more details., NSUnderlyingError=0x600001378900 {Error Domain=RCBackendErrorDomain Code=7225 "Invalid API Key." UserInfo={NSLocalizedDescription=Invalid API Key.}}}
[Purchases] - DEBUG: POST /v1/subscribers/$RCAnonymousID:02abcbccebf7473fa58bcd51a8cba9a9/attribution 401
[Purchases] - ERROR: There was a credentials issue. Check the underlying error for more details

**Comment by rkotzy** [comment]
`INVALID_CREDENTIALS` error sounds like you may not be configuring the SDK with your Public SDK key. More info here: https://docs.revenuecat.com/docs/authentication

Going to close this out since we try to reserve Github issues for bugs. For support I'd recommend our [online community](https://spectrum.chat/revenuecat) and/or [Help Center](https://support.revenuecat.com/hc/en-us) 👍
