### ISSUE TITLE
Change the name of the Purchases class and package name

### ISSUE THREAD

**Issue by lukepighetti** [RevenueCat/purchases-flutter#855]
The name of the package is generic and confusing. I have received this feedback from multiple developers. I would like to recommend a renaming exercise to improve the developer experience and better connect the product to the brand. The most critical one to rename is the `Purchases` class to `RevenueCat`

|              | Before            | After              |   |
|--------------|-------------------|--------------------|---|
| Class name   | Purchases         | RevenueCat         | ⭐️ |
| Package name | purchases_flutter | revenuecat_flutter |   |
| Repo name    | purchases-flutter | revenuecat_flutter |   |

A possible way forward is to perform the rename and then add a deprecated typedef to make it a non-breaking change, with the goal to be removing it eventually. 

```dart
@Deprecated("Use RevenueCat instead of Purchases")
typedef Purchases = RevenueCat;
```

**Comment by vegaro** [comment]
Thanks for the feedback @lukepighetti 

I've passed it along to the team and we agree it can be confusing, but we don't think we will be changing the name of the class any time soon. All our SDKs have the same Purchases class and doing the rename across all the SDKs would take a big effort and break a lot of devs' code. Even if we add a deprecation warning it's still a breaking change we don't want to introduce at the moment. We also didn't want to tie our SDK to our brand name when we decided on the name of the main class.

I am going to be closing this issue so we keep things tidy, but thanks again for the feedback.
