### ISSUE TITLE
Unable to determine if user is subscribed

### ISSUE THREAD

**Issue by jp555soul** [RevenueCat/purchases-flutter#88]
Using the code from the docs and example yet I'm unable to get the data showing the user is Active even though it is present. 

1. Environment
    1. Platform: **Android Studio**
    2. SDK version: **^1.2.0**
    3. OS version: Catalina **10.15.5**
    4. XCode/Android Studio version: **4.0.1**
    5. How widespread is the issue. Percentage of devices affected. **All**
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
    `I/flutter ( 8990): Not Pro`
     `I/flutter ( 8990): PurchaserInfo{entitlements: EntitlementInfos{all: {pro: EntitlementInfo{identifier: pro, isActive: true, willRenew: true, periodType: PeriodType.normal, latestPurchaseDate: 2020-08-04T00:30:03.000Z, originalPurchaseDate: 2020-08-04T00:16:07.000Z, expirationDate: 2020-08-04T00:35:03.000Z, store: Store.playStore, productIdentifier: com.jmpaul.curingcrystals.1month, isSandbox: true, unsubscribeDetectedAt: null, billingIssueDetectedAt: null}}, active: {pro: EntitlementInfo{identifier: pro, isActive: true, willRenew: true, periodType: PeriodType.normal, latestPurchaseDate: 2020-08-04T00:30:03.000Z, originalPurchaseDate: 2020-08-04T00:16:07.000Z, expirationDate: 2020-08-04T00:35:03.000Z, store: Store.playStore, productIdentifier: com.jmpaul.curingcrystals.1month, isSandbox: true, unsubscribeDetectedAt: null, billingIssueDetectedAt: null}}}, latestExpirationDate: 2020-08-04T00:35:03.000Z, allExpirationDates: {com.jmpaul.curingcrystals.1month: 2020-08-04T00:35:03.000Z}, allPurchaseDates: {com.jmpaul.curingcrystals.1`
`I/flutter ( 8990): false`

3. Code
```     
 var isPro = _purchaserInfo.entitlements.active.containsKey(_paidEntitlementKey);
      if (isPro) {
        print("Is Pro");
      } else {
        print("Not Pro");
        print(_purchaserInfo);
        print(_purchaserInfo.entitlements.all[_paidEntitlementKey] != null && _purchaserInfo.entitlements.all[_paidEntitlementKey].isActive);
      }
```

**Comment by vegaro** [comment]
What's the value of `_paidEntitlementKey`?

**Comment by jp555soul** [comment]
@vegaro the entitlements associated products id - `com.jmpaul.curingcrystals.1month`

**Comment by jp555soul** [comment]
@vegaro thank you! It's supposed to be the entitlement identifier of `pro` for me...

**Comment by vegaro** [comment]
Yes! That's what I was going to say. Happy you got that fixed! The beauty of this system is that you don't need to ship an update to your app if you ever want to offer another product, you just change the product id associated with the `pro` entitlement in our dashboard. So you shouldn't have to hardcode any product ID when using RevenueCat 😸
