### ISSUE TITLE
presentPaywallIfNeeded always return Null

### ISSUE THREAD

**Issue by imSaharukh** [RevenueCat/purchases-flutter#886]
```
  if (Platform.isIOS) {
    //get all Entitlement
    var purchaserInfo = await Purchases.getCustomerInfo();
    var entitlements = purchaserInfo.entitlements.all;

    log("entitlements $entitlements");

    var result = await Purchases.presentPaywallIfNeeded(
        entitlements.values.first.identifier);

    log("result $result");

    return;
  }
```

i'm always getting flutter: type 'Null' is not a subtype of type 'FutureOr<bool>' error

**Comment by tonidero** [comment]
Hi @imSaharukh, thanks for reporting this. Indeed this is a problem in the current beta of paywalls. We're working on a fix and will update this issue once it's shipped.

In the meantime, we suggest handling this error as a non-fatal exception. Not ideal, but we hope to have it fixed soon.

**Comment by BorisKest** [comment]
Same here. BTW are you going to make it possible to use a paywall from different offerings rather than the current one?

**Comment by NachoSoto** [comment]
Thanks for reporting! A few questions:
- Is this happening on Android, iOS, or both?
- Are you seeing anything in the logs?

Looking at the code, if this is Android only, I believe what might be happening is that your `MainActivity` probably still inherits `FlutterActivity`, and you need to change it to inherit from `PurchasesFlutterActivity` to support paywalls.

I just updated the implementation so an error is forwarded instead: 704bd671816f2793835306b59d9ab2120fb2f4da

**Comment by tonidero** [comment]
Hi everyone! We're aware of this issue. #916 should fix it temporarily by removing the return value from `presentPaywall`/`presentPaywallIfNeeded`. We plan to add a more future-proof API later so we can receive more data of what happened with the paywall.

**Comment by tonidero** [comment]
> Same here. BTW are you going to make it possible to use a paywall from different offerings rather than the current one?

Hi @BorisKest, sorry for missing this! Yeah, that's part of the roadmap but might not be in V1 of paywalls for flutter.
