### ISSUE TITLE
The item that you were attempting to purchase could not be found

### ISSUE THREAD

**Issue by HassanBalousha** [RevenueCat/purchases-flutter#90]
![Screenshot_2020-08-19-15-44-29-077_com android vending](https://user-images.githubusercontent.com/47014491/90636756-c08e9280-e233-11ea-98d5-621ca021b48b.jpg)

**Retrieved all products but when you purchase this message appears**

**Comment by elyfran** [comment]
same here

**Comment by rafaelbanhos** [comment]
same here

**Comment by aboedo** [comment]
Is this happening consistently? We saw something similar happening internally a couple of days ago, and it turned out that for some reason our test user wasn't registered on the play console anymore, we re-added and it got fixed.

**Comment by rafaelbanhos** [comment]
Me and other developer are testing now. On my smartphone it's working, but on the other developer's smartphone it's not working.

**Comment by vegaro** [comment]
Make sure the tester is added as a license tester and to the closed track testers list

**Comment by rkotzy** [comment]
Closing this out since it's a server error from Google related to Play Store configuration.

**Comment by 3052** [comment]
https://github.com/3052/google/issues/39
