### ISSUE TITLE
[Problem] In-app billing API version 3 is not supported on this device.

### ISSUE THREAD

**Issue by HassanBalousha** [RevenueCat/purchases-flutter#92]
Show message : In-app billing API version 3 is not supported on this device.

**Comment by vegaro** [comment]
Google throws that error when the device is not logged in to Play Store. Make sure that the emulator has the Play Store and that you are logged in with a testing email.

You can choose an image of the emulator with Play Store when creating a new device:
<img width="264" alt="Screen Shot 2020-09-28 at 10 01 57 AM" src="https://user-images.githubusercontent.com/664544/94463387-b7b5a880-0171-11eb-9c42-dc5ef18fb62f.png">
