### ISSUE TITLE
Exception: _TypeError (type 'Null' is not a subtype of type 'String' in type cast) on allPurchaseDates field on iOS for Android Prepaid Subscriptions

### ISSUE THREAD

**Issue by amuehleder** [RevenueCat/purchases-flutter#988]
- [ ✓] I have updated Purchases SDK to the latest version
- [ ✓] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [ ✓] I have searched the [Community](https://community.revenuecat.com)
- [ ✓] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ ✓] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

# ‼️ Required data ‼️ #
**Do not remove any of the steps from the template below. If a step is not applicable to your issue, please leave that step empty.**

There are a lot of things that can contribute to things not working. Having a very basic understanding of your environment will help us understand your issue faster!

## Environment ##
- [ ✓] Output of `flutter doctor`

[✓] Flutter (Channel stable, 3.19.0, on macOS 14.3.1 23D60 darwin-arm64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.86.0)
[✓] Connected device (6 available)            
    ! Error: Browsing on the local area network for Kiew. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.

- [ ✓] Version of `purchases-flutter` => 6.21.0
- [ ✓] Testing device version  => iPhone 15 Pro Simulator (iOS 17.0)
- [  ✓ ] How often the issue occurs- every one of your customers is impacted? Only in dev?
Every time fetching the CustomerInfo.

- [✓ ] [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue

<img width="704" alt="image" src="https://github.com/RevenueCat/purchases-flutter/assets/58145561/97ff0d63-23ff-4373-ab78-73c657ed26bd">
<img width="589" alt="image" src="https://github.com/RevenueCat/purchases-flutter/assets/58145561/ba2d1368-0f00-46a8-8fa1-ce3c72ecc30b">

- [ ✓] Steps to reproduce, with a description of expected vs. actual behavior
Configure a prepaid subscription in the Google Play Console (3 months). Buy this subscription via android and try to fetch the CustomerInfo afterwards on iOS.
Seems highly related to this https://github.com/RevenueCat/purchases-flutter/issues/738

**Comment by tonidero** [comment]
Thanks for reporting this @amuehleder!

We haven't been able to reproduce the issue with your steps but we did notice that this may cause a crash when the purchase date is null, which is a supported case in our native SDKs, so we are working on a fix: #989

**Comment by amuehleder** [comment]
Hy @tonidero, 

thanks for fixing the issue so quickly. I saw that you merged the PR, unfortunately in Release 6.21.1 the issue is still present.

<img width="893" alt="image" src="https://github.com/RevenueCat/purchases-flutter/assets/58145561/fb452e04-4779-4d5d-be49-e7a48629c285">

Could you please have a look? Thanks in advance!

**Comment by tonidero** [comment]
Hi @amuehleder, 

6.21.1 was released before the fix was merged. The next release should contain the fix though. Sorry for the confusion!

**Comment by amuehleder** [comment]
Whoops, my bad - thx for the clarification 👏🏻
